### ISSUE TITLE
Editing functionality

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#140]
- [x] Add bps
 - [x] Delete bps
 - [x] Replace bps
 - [x] Copy annotated sequence

**Comment by njhillson** [comment]
Will not test until start working on full VectorEditor edition.

**Comment by njhillson** [comment]
Delete works, but only with the backspace key. Does not seem to work with delete key.

**Comment by tnrich** [comment]
added delete key

**Comment by njhillson** [comment]
This is working now, revealed another issue. I will create a ticket for it.

**Comment by XimeMora** [comment]
@tnrich @njhillson where can I find the options to add/delete/replace bps and copy annotated sequence?

**Comment by XimeMora** [comment]
Editing functionality is working nicely.
