### ISSUE TITLE
Find/Search

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#142]
- [x] Highlight all
 - [x] Jump to highlight
 - [x] Ambiguous dna search 
 - [x] Protein search 
 - [x] Show number of matches,
 - [x] Color search match highlights differently
 - [x] Search Reverse Strand
 - [x] * not being searched for with amino acid search
 - [x] ambiguous amino acid search not working

**Comment by tnrich** [comment]
Hey @njhillson 
A couple questions about the search tool:
1. Should the search also include searching the reverse strand by default or should that be another option? 
2. Does ambiguous search only make sense for DNA searches?
2.5. If so, should we not give the "ambiguous" option for protein searches? 

Thanks!

**Comment by njhillson** [comment]
Search should be for both strands. Not sure you need option to only search
one strand or the other.
There are both ambiguous DNA and protein characters, so both should be
supported.
http://www.dnabaser.com/articles/IUPAC%20ambiguity%20codes.html

**Comment by njhillson** [comment]
Jump to highlight not scrolling correctly, but that is covered in ticket XXX.

**Comment by XimeMora** [comment]
@njhillson or @tnrich can you please explain to me how ambiguous dna and amino acid search should work?

**Comment by njhillson** [comment]
There are ambiguous codes for protein and DNA. See for example:
http://www.dnabaser.com/articles/IUPAC%20ambiguity%20codes.html

for DNA, search for things including the character 'N' which should match
any base, or 'R' that should match A or G (for example).

for protein, search for things including the character 'X' which should
match any amino acid, or 'B' that should match D or N (for example).

**Comment by XimeMora** [comment]
All the items listed above for Find/Search tool are working correctly.
