### ISSUE TITLE
Properties View

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#143]
- [x] Feature properties
 - [x] Cutsite properties
 - [x] Part properties
 - [x] Orf properties
 - [x] Primer properties
 - [x] Genbank file preview

**Comment by tnrich** [comment]
Things definitely could use a bit more design work but basic functionality is working. 

Note: New/Edit  Part/Translation/Primer is not yet working.

**Comment by njhillson** [comment]
In ICE VV, properties view generally looks ok. I will create another ticket XXX for an issue I see wherein the app crashes if I try to search.

**Comment by XimeMora** [comment]
Properties View looks good, bugs that I found will be addressed in a new ticket.
