### ISSUE TITLE
Save Hook

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#144]
- [x] Hook for global editor onSave event where JBEI and others can convert and save the sequence info

**Comment by njhillson** [comment]
I will not test until we are working on full VectorEditor. Not relevant in VectorViewer context.

**Comment by njhillson** [comment]
Several issues.
I do not see any visual feedback to the user that the sequence has been saved.
I can save feature changes, but sequence changes are not saved (not sure if VE or ICE issue - Hector looking in to this).

**Comment by tnrich** [comment]
@hplahar I think it might be appropriate on your end to trigger a little toaster message alerting the user that the save we successful.

**Comment by tnrich** [comment]
@hplahar what do you think? Either you could trigger a toaster message on successful save or my onSave hook could await a truthy response from your code and trigger a "Sequence saved successfully" message. Thoughts?

**Comment by hplahar** [comment]
I typically prefer to use messages when something went wrong. What does everyone think about have the save button enabled when there are changes needing to be saved and then disabled on successful save? .....otherwise I can send the response from my end. 

On the topic of toaster messages, it will also be nice at some point to provide an option to route the messages to the embedding application (in this case ICE) so that it handles displaying it.

**Comment by tnrich** [comment]
@hplahar I agree with you that disabling the save button is the way to do it. It is a little bit complicated to do but I tried to implement a solution similar to how it is done in our current TG app.

I added a unique state-tracking ID to every unique state the editor has. On initial load, the state is assumed to be saved and the lastSavedId = initialStateId. 

After an edit is made the sequence state gets a new unique ID, but the lastSavedId = initialStateId so the save will be enabled. 

If the user hits undo, the save button will be disabled once again because reverted state keeps its initialStateId and lastSavedId = initialStateId still holds. 

Upon successful save, the lastSavedId is set to the state that is being saved. This requires that you return a promise from the onSave function in order for us to properly handle error cases. 

That is kind of technical, but all you need to do is return a promise and the rest should be automagically handled on the OVE side. Does that all sound good to you?

**Comment by tnrich** [comment]
@hplahar also note that I can provide a callback interface as well if that is easier. Same idea applies though :)

**Comment by hplahar** [comment]
Sounds good. Thanks.

**Comment by tnrich** [comment]
Any update on this one @hplahar ?
