### ISSUE TITLE
Support sanger / alignments

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#147]
- [ ] Support ability to do alignments

@njhillson could you point me to an existing tool that supports sequence alignments and maybe describe the sort of functionality we'll want the editor to be able to support? 

Thanks!

**Comment by njhillson** [comment]
ICE has this currently in sequence analysis tab. Uses BLAST to do pairwise
alignment, parses results, renders arcs around circular plasmid or line
above linear construct. colors green where good red where bad. Below visual
is the actual DNA alignment. Check it out in JBEI public ICE. If you have
questions, ask Hector Plahar. We can show it to you during DIVA developers
meeting this afternoon.

**Comment by tnrich** [comment]
Awesome thanks @njhillson !
