### ISSUE TITLE
Add OVE menu bar

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#148]
- [x] Add the option to have a standard menu bar 
 - [x] It should support al the functionality of the toolbar, just in a menu bar

**Comment by tnrich** [comment]
@mfero  

Hey @jpcarzolio, you're doing some work making menu bars for lims/hde, right? 

Could you point me toward where the MenuBar is being developed and could we maybe expose that one in teselagen-react-components so that OVE could take advantage of it too? 

Thanks!

**Comment by AdamZMc** [comment]
Menu bar does not appear to have been implemented.
![screen shot 2018-09-03 at 11 40 12 pm](https://user-images.githubusercontent.com/36317055/45014291-dc5ee680-afd2-11e8-9151-e6de1a6cc420.png)

**Comment by XimeMora** [comment]
There is a menu bar now and it's working. There is also a new ticket created by Mike with some issues with this menu so I'll move this ticket along in favor of that other one in hde https://github.com/TeselaGen/hde/issues/2299
