### ISSUE TITLE
Add undo/redo functionality

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#149]
- [x] The user should be able to undo/redo their actions 
 - [x] onUndo/onRedo hooks should be supported as well in case end-users would like to auto-save

**Comment by XimeMora** [comment]
Undo/Redo is working correctly.

**Comment by njhillson** [comment]
I am only testing the read-only view for ICE VectorViewer right now. Will not test this until I progress to the full VectorEditor.
