### ISSUE TITLE
When features are turned off, the yellow circle becomes a little....big

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#152]
![](https://lh3.googleusercontent.com/-5UGkrk0n8so/Wfi2uFHNHZI/AAAAAAAAAW0/JJpSZaLhCwQOvU2wVU5g-x4SQW7C96opQCL0BGAYYCw/h548/no%2Bfeatures.png)

It should take up less total space.

**Comment by njhillson** [comment]
Seems ok without features on at all. Note that if I have features on but feature labels off, the circle is still just as big! Failing for that condition.

**Comment by tnrich** [comment]
Can we pass this and create a new ticket for the issue you're seeing @njhillson ?

**Comment by njhillson** [comment]
Please do

**Comment by tnrich** [comment]
Okay I'll create a new ticket and pass this one (unless I'm misunderstanding what you want)

**Comment by njhillson** [comment]
Yes. Please do. I am on plane now and can’t do it myself. Please move to ready for qa2 for Ximena.

**Comment by XimeMora** [comment]
Looks good!
