### ISSUE TITLE
Toolbar tooltip overlaps the dropdown menu.

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#153]
![](https://lh3.googleusercontent.com/-GhiMAatng6w/Wfi3P4y0kTI/AAAAAAAAAXA/Jnho857E94EQ-WIpHJ0Ilx2RGSzWD9kkwCL0BGAYYCw/h1317/tooltip_overlap.png)

**Comment by njhillson** [comment]
This looks fine. The tool tip is now above the dropdown.

**Comment by XimeMora** [comment]
Looks good!
