### ISSUE TITLE
When you show the cutsites, it changes the type of font (jbei only right now? )

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#154]
When you show the cutsites, it changes the type of font (this might be a css conflict but I am not sure. 

Before: 

![](https://lh3.googleusercontent.com/-aRncnI1m5q0/Wfi1zAnD7HI/AAAAAAAAAWM/YpUkUO9bEgQdjYGBWyhcSb_FFAB_44nKwCL0BGAYYCw/h510/with_cutsites.png)

After: 

![](https://lh3.googleusercontent.com/-SipdD_nUwTM/Wfi1vs14uhI/AAAAAAAAAWM/T6aVZCact6gXQBrX74RE5lvOmChsiE1AQCL0BGAYYCw/h517/features.png)

**Comment by tnrich** [comment]
@hplahar if you can investigate more into this to see if it has to do with a certain os/browser that would be really helpful! I haven't been able to reproduce on ICE yet but the current build on ICE doesn't appear to have the toolbar so I can't really check. Thanks!

**Comment by hplahar** [comment]
Isn't happening on my Mac. Just happens on my ubuntu install. Don't have a windows machine to test it on though.

**Comment by tnrich** [comment]
@hplahar any chance you could check to see if this is still happening for you?

**Comment by hplahar** [comment]
Still happening

**Comment by tnrich** [comment]
@hplahar is this still happening?

**Comment by hplahar** [comment]
@tnrich No. Looks fine now

**Comment by tnrich** [comment]
Awesome thanks @hplahar
