### ISSUE TITLE
 Show/Hide features button starting state funkiness

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#155]
Show/Hide features button is "off" by default but the features are showing (which is what I want). But you have to click the button to "show" the features and then click again to then hide it. (Hope my description makes sense)

**Comment by tnrich** [comment]
@hplahar can you point me to your source code where you set up the editor? I am having trouble reproducing locally. Also is there any chance you can make your demo server not locked by VPN?

**Comment by tnrich** [comment]
@hplahar I figured out how to reproduce this issue locally.

**Comment by njhillson** [comment]
I think this is looking good now.

**Comment by XimeMora** [comment]
This is working fine.
