### ISSUE TITLE
Import button

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#157]
Generic fasta/genbank upload to view tool

You should be able to drag and drop fasta/gb and view it in the tool as well

**Comment by njhillson** [comment]
I am only testing the read-only view for ICE VectorViewer right now. Will not test this until I progress to the full VectorEditor.

**Comment by njhillson** [comment]
In the context of ICE< there is no import button. Will not test. @XimeMora you can test outside of ICE context.

**Comment by XimeMora** [comment]
@tnrich for HDE and LIMS should we have an option inside VE to upload a sequence? or is it just the option from the respective tool like from the Sequences library in HDE?

**Comment by tnrich** [comment]
Probably we'll just not show this tool for the time being.
