### ISSUE TITLE
Smooth scrolling in row view

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#158]
The row view should not be super "janky" when scrolled. Different improvements can make this possible: 

 - [x] Cache rows that have already been rendered (speeds up subsequent renders)
 - [x] Don't render super heavy layers immediately (wait until the rest of the "lighter" layers have been rendered so scrolling isn't blocked)
  - Note only doing this for the "translation" layer currently (it is noticeably slightly delayed)
 - [x] Fix issues inherent to trying to scroll variably sized element which don't have precomputed heights (add a scrollParent.scrollBy(offsetBetweenEstimatedSizeAndActualSize) that triggers right after the element has made it into the DOM)

**Comment by njhillson** [comment]
Scrolling looks good in general in ICE - VV. At least for a smallish plasmid. I will be sending @tnrich a genome sized sequence to play around with. This is in ticket XXX. See also other tickets XXX and XXX regarding not scrolling correctly during sequence search and an annoying autoscroll back to selection issue.

**Comment by XimeMora** [comment]
Looks good.
