### ISSUE TITLE
Resizable Panels

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#159]
- [x] Allow the circular view/ row view to be resized by dragging a "splitter" element between them. 
 - [x] Allow the properties view to slide in from the right  as another resizable panel.

**Comment by njhillson** [comment]
This is not working for me in ICE - VV. Failing.

**Comment by njhillson** [comment]
This is working now. Duplicate of ticket #179.

**Comment by XimeMora** [comment]
Looks good!!!
