### ISSUE TITLE
Make sure all layers can be right clicked as expected

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#160]
- [x] The selection layer should be rendered behind annotations
 - [x] The selection layer should still be right-clickable when clicked at the same height as an annotation (so long as you're not clicking the annotation itself)
- [x] All annotations should be right clickable

**Comment by njhillson** [comment]
Looks good to me.

**Comment by XimeMora** [comment]
This is working fine. There is just an issue with right-clicking that will be addressed in a new ticket.
