### ISSUE TITLE
find tool amino acid matches should show amino acids

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#162]
Find tool amino acid matches should show amino acid translation

**Comment by njhillson** [comment]
Failing. I am not seeing any translations when doing the amino acid matches. I don't see any relevant visibility options for this... I can only see those translations in ORF regions if I have ORF translations visible - but the search translations should be for any regions, not just within ORFs, and not only if ORF translations are visible.

**Comment by tnrich** [comment]
Hey Nathan, sorry I jumped the gun a little bit. The publishing process
takes about 5-10 minutes for changes to propagate and I moved the card over
before that has happened I take it.

**Comment by njhillson** [comment]
This is looking good now.

**Comment by XimeMora** [comment]
This is working fine.
