### ISSUE TITLE
ICE - VectorView Status Bar Needs Conditional Display

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#163]
Within ICE, the VectorViewer needs conditional displays of the following:

 - [x] 2. Selecting from X to X - only show if a subsequence has been selected.

 - [x] 3. Inserting between X and X - do not show - read only mode makes this irrelevant.

**Comment by njhillson** [comment]
Within ICE, the VectorViewer needs conditional displays of the following:

Select Inverse button - only show if a subsequence has been selected.

Selecting from X to X - only show if a subsequence has been selected.

Inserting between X and X - do not show - read only mode makes this irrelevant.

**Comment by tnrich** [comment]
Hey @njhillson  I'm not sure I agree with #1 and #2 100%. Here's my thinking: 

#1: 
- It seems like users might want to select the inverse when there is only a caret down (no selection) 

#2: 
- It is nice to know that nothing is being selected 
- it is a lot of text to have jumping in and out of the toolbar as you click and drag around the editor. 

I went ahead and implemented #3 :)

**Comment by njhillson** [comment]
I can see benefit of select inverse without selection, so I guess I am okay with that (#1), although it still seems a bit weird to be, but I guess it still is the inverse. Regarding #2, if concern is having text jump in and out, maybe just have text like "Nothing selected" etc. I wouldn't mind text jumping in our out, so I would still prefer it to be conditional.

**Comment by njhillson** [comment]
This looks good now. Note new ticket #186 concerning ordering of selection numbering.

**Comment by XimeMora** [comment]
This is working nicely.
