### ISSUE TITLE
ICE - VV - no linear/rail view option

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#165]
In ICE - VV, for linear sequences, I should be seeing the linear/rail view instead of the plasmid map. The circular/linear distinction should be determined by ICE.

**Comment by njhillson** [comment]
When I turn on the linear rail view in addition to the plasmid or sequence view, the bottom information (read only, selection, select inverse, length) seems to be flowing off the bottom of the page. When I don't have linear rail view on, or when only linear rail view is on, it seems to look ok. Failing.

**Comment by njhillson** [comment]
This issue is still happening to be. @tnrich please get together when possible with @XimeMora to be able to figure out a way for you to reproduce...

**Comment by tnrich** [comment]
Let's pass this because the buggy-ness of the linear view is addressed by #192

**Comment by njhillson** [comment]
Going to pass this, given ticket #192 but note that @hplahar still needs to set default view to linear for linear sequences in ICE.

**Comment by XimeMora** [comment]
Moving this ticket along but I noticed another issue with the Linear Map view that will be addressed in a new ticket.
