### ISSUE TITLE
ICE - VV - cut sites options insufficient

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#167]
The cut sites should support all of REBASE, and the selection menu needs to be improved. Please use existing VectorEditor and even Sarah Lafrance's VEjs for better versions.

**Comment by tnrich** [comment]
@njhillson Does the option to add additional enzymes make this one acceptable? 


![image](https://user-images.githubusercontent.com/2730609/38217028-9eaefb60-3681-11e8-945b-0c20ba01e364.png)
