### ISSUE TITLE
ICE - VV - single cutters labels should be in red

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#168]
For restriction enzyme label display, single cutters should be shown in red.

**Comment by tnrich** [comment]
Single cutters are now red
Double cutters are blue
All other enzymes are light grey

**Comment by XimeMora** [comment]
@tnrich I would feel bad if I failed this ticket after your poetry 🤣 so I better ask... is the demo page and the rest of the instances not updated? Because I'm not seeing the colors 😞

**Comment by tnrich** [comment]
Hmm I'll let you know when I'm sure it is deployed

**Comment by XimeMora** [comment]
I can see the colors now 😄 Looks good!

**Comment by AdamZMc** [comment]
Colors have been implemented.
