### ISSUE TITLE
ICE - VV - show features button icon poor choice

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#169]
Instead of a ribbon, the features button icon should look more like a recognizable shape, like a coding sequence pentagon (the way that the feature arcs are rendered in the plasmid map, for example).

**Comment by tnrich** [comment]
![image](https://user-images.githubusercontent.com/2730609/38648701-94f3b412-3da7-11e8-9c97-06cc2e7795ee.png)

**Comment by XimeMora** [comment]
Looks good.

**Comment by AdamZMc** [comment]
Looks good. Moving along.
