### ISSUE TITLE
ICE - VV - get rid of show/hide primers button.

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#171]
This is non standard and non-necessary for ICE - VV

**Comment by njhillson** [comment]
@tnrich - should this be in ready for qa? Does it require Hector to change the config on the ICE side to not display it? I am still seeing it right now in ICE - VV.

**Comment by tnrich** [comment]
Oh, I thought that Hector had updated the config but I guess he hasn't yet.
Please move it back if it isn't ready. Sorry about that!

**Comment by njhillson** [comment]
Hector just updated the config. Looks good now.

**Comment by XimeMora** [comment]
Show/hide primers button is no longer there.
