### ISSUE TITLE
ICE - VV replace ORF toggle button icon

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#172]
The ORF toggle button icon is a poor choice. A circle confuses the user, as this is the icon for an origin of replication or circular view. The icon for the ORF should look more like a single arrow, or some other sensible choice, to match the arcs rendered for ORFs.

**Comment by tnrich** [comment]
![image](https://user-images.githubusercontent.com/2730609/38648705-9666186c-3da7-11e8-8211-8e4be714861d.png)

**Comment by AdamZMc** [comment]
Looks good!
