### ISSUE TITLE
ICE - VV - rescale display size according to real estate available?

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#173]
Is it possible to rescale the VV size according to the real estate available? It is annoying not to have the full vertical length of the VV tool visible at once. I currently have to scroll up and down to see either the top tool button bar or the bottom status bar.

**Comment by tnrich** [comment]
I could add an option to make the height of the tool fit exactly the height of the browser window. When embedded in ICE you would still have to scroll down to fit it all in, but once you where in that position, it would be taking up the entire screen. Is that what you want @njhillson?

**Comment by njhillson** [comment]
@tnrich, in ICE context, browser window height is not the right length, since ICE has a header and footer margin. I think it would need to be specifically the real estate it actually has to use in the ICE context.

**Comment by tnrich** [comment]
Closing as this is now deprecated. We went with a preview/fullscreen approach in lims.
