### ISSUE TITLE
ICE - VV - search for DNA sequence - find not scrolling to correct place

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#174]
In ICE - VV, if I search for a DNA sequence e.g/ "ggtctc", it should scroll in the sequence panel so that the first found match is shown, ideally in the middle of the sequence panel view. Currently, the sequence panel is not rotating to the correct place. If I click to see the next match, the sequence panel should again move so that I can see it.

**Comment by njhillson** [comment]
In general, this is working much better, so I am going to pass. I am creating a new ticket #187 to cover issue where the search paging is first going through top strand matches and then going through bottom strand matches.

**Comment by XimeMora** [comment]
Looks good.
