### ISSUE TITLE
ICE - VV - clicking on sequence search match highlighted region should select that region

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#175]
Sequence search is working, and it highlights the found region with a redish background. However, I can not click to select the highlighted redish region in the sequence panel.

**Comment by njhillson** [comment]
I just heard from a JBEI user that this is also causing an issue for him. Going to set priority to high.

**Comment by njhillson** [comment]
This is working now.

**Comment by XimeMora** [comment]
Looks good!
