### ISSUE TITLE
ICE - VV can not click to select forward direction feature shape in sequence panel

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#176]
If I try to click select a feature shape in the sequence panel for forward direction features, nothing happens. Reverse direction features seem to work okay, and forward direction features in the plasmid map panel seem fine too. This seems to be a focus issue, possibly, and it doesn't always seem to be happening. I can reproduce pretty consistently, for example, by toggling on the search for sequence tool, or clicking around various subpanels to change focus, etc. If you have a hard time reproducing this, I can develop more explicit instructions.

**Comment by njhillson** [comment]
This seems to be much better now.

**Comment by XimeMora** [comment]
This is working fine.
