### ISSUE TITLE
ICE - VV sequence panel autoscrolls back to selection region

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#177]
This is extremely annoying. If I select a sequence region, and then scroll around in the sequence panel, the panel will auto scroll away from where I want to see and take me back to the selected region. This autoscroll activity should only occur, for example, after I click on a feature in the plasmid map view, or if I click to advance through sequence matches. The sequence panel should not be sticky on the selected region after I am initially taken there.

**Comment by tnrich** [comment]
@njhillson  can you see if you can still reproduce this one?

**Comment by njhillson** [comment]
this is looking so much better now. I don't see any autoscroll issue now.

**Comment by XimeMora** [comment]
Scrolling is working fine.
