### ISSUE TITLE
ICE - VV visibility display option issues

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#178]
Several issues here. Feel free to break into separate tickets.

 - [x] Cutsite labels - does nothing. Only cutsite view seems to do anything.

 - [x] Parts labels - remove, irrelevant currently.

 - [x] Parts - remove, irrelevant currently.

 - [x] Axis numbers - if I toggle this it crashes the app. I can see how this could be useful though.

**Comment by njhillson** [comment]
Looking much better now.

**Comment by XimeMora** [comment]
These issues are now fixed.
