### ISSUE TITLE
ICE - VV critical - copy/paste object off by one sequence selection interval

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#181]
In ICE VV, if I select a sequence, and copy it to clipboard, and then paste into DeviceEditorjs in DIVA, the selection bp numbering pasted in to DeviceEditorjs is off by one. E.g. instead of the interval 289 to 1098, the interval rendered in DeviceEditor is 288 to 1097. This is a critical issue.

**Comment by XimeMora** [comment]
@njhillson or @tnrich can you please help me with the steps for testing this? what I don't know how to do is to select a sequence and copy it to the clipboard (I don't see a button or an option to do that in ICE VV). Also I'm not familiar with the DeviceEditorjs in DIVA.

**Comment by njhillson** [comment]
@XimeMora you can test as follows. (Note: you may need to be VPN'd in to LBNL to get access to the DIVA server). Select a sub-sequence in ICE VV - on https://registry-test2.jbei.org . Copy the sub-sequence. Go to DEjs in DIVA - on https://registry-test1.jbei.org. Open any design (or create a new one) for which you have edit privileges. Open the design in DeviceEditor. Right click any empty part location and do a map from clipboard. After following the steps, you should see a modal to specify the part definition. You should be looking for several key things: 1) that the start and stop bp match what is presented in VV, 2) that the source data - which should look like a Genbank file - contains all of the features you expect, 3) that that part source field matches the name of the source sequence, and 4) after finishing the creation of the part that the part info tab for the part has a link to ICE in the ICE Display ID field. I am happy to do a screenshare to walk you through it if you would like.

**Comment by XimeMora** [comment]
The 4 things to check described by Nathan are working correctly!
