### ISSUE TITLE
ICE - VV selection numbering has larger number followed by smaller number

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#186]
In ICE VV, if I select a subsequence that does not wrap around the origin, I get something that looks like "Selecting 810 bps from 1098 to 289". Note that the higher number is first. It should be the other way around. Conversely, if I select a subsequence that wraps around the origin, I get something that looks like "Selecting 295 bps from 189 to 2499". Note that the lower number is first. It should be the other way around. It looks like the underlying data is fine, since if I try to copy/paste into DEjs in DIVA, it does have the correct start and stop bps.

**Comment by tnrich** [comment]
Whoops! Nice catch!

**Comment by njhillson** [comment]
Looks good now.

**Comment by XimeMora** [comment]
Looks good!
