### ISSUE TITLE
ICE - VV sequence search paging order does top strand then bottom strand locations

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#187]
When paging through sequence search locations, it would be nice to progress through them from the first bp to the last bp, on both strands. Currently, it goes first bp to last bp on the top strand, and then last bp to first bp on the bottom strand.

**Comment by tnrich** [comment]
This should be fixed although it seems like the jumping/numbering of stuff might be slightly off..

**Comment by njhillson** [comment]
This looks better now.

**Comment by XimeMora** [comment]
Looks good!
