### ISSUE TITLE
add hotkeys for common actions

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#189]
List of hotkeys to make:
- [x] Create new digest

**Comment by XimeMora** [comment]
@tnrich what is the hotkey for this one?

**Comment by XimeMora** [comment]
@tnrich just to confirm... I think this is the one, right?

![screen shot 2018-04-30 at 12 01 16 pm](https://user-images.githubusercontent.com/21211903/39444984-59b116c6-4c6e-11e8-8de1-11eade3cf497.png)

**Comment by tnrich** [comment]
Hey @XimeMora yep that is the one. We'll need to go back over our hotkey implementation in a little while once I've implemented the stuff Juan's been working on. Maybe I'll just close this for right now. Not a great ticket..
