### ISSUE TITLE
ICE - VV: Selecting "Toggle Linear View" is causing a buggy behavior with the scrolling

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#192]
To reproduce I uploaded a sequence from the TeselaGen main app "pj5_00001.gb" then I clicked Show View Options > Toggle Linear View and scroll down the page:

![buggy linear view](https://user-images.githubusercontent.com/21211903/33581731-a3407428-d917-11e7-8661-e9939a4936c7.gif)

Also when opening and closing the Properties the bar at the bottom disappears, it seems to go further down but even when scrolling all the way to the bottom I can't see it (this might be related to the first issue):

![no bottom toolbar](https://user-images.githubusercontent.com/21211903/33581839-191a702c-d918-11e7-805d-3263e34c1265.gif)

**Comment by njhillson** [comment]
I am no longer seeing this issue.

**Comment by XimeMora** [comment]
This issue is not happening anymore.
