### ISSUE TITLE
ICE - VV translate selection incompatible view with ORF translations

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#193]
If I select a sub-sequence and right click to translate, I see the translation. However, if I then turn on view ORF translations, the selection translation view goes away. If I turn off the ORF translation view, the selection translation view re-appears. Both should be visible at the same time.

**Comment by njhillson** [comment]
Looking better now.

**Comment by XimeMora** [comment]
Looks good.
