### ISSUE TITLE
ICE - VV ORF prediction start codon

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#194]
The ORF prediction algorithm likely currently assumes that all start codons are "ATG". However, "GTG" and "CTG" start codons are also possible. It would be nice to have a toggle for ORF predictions (in same UI drop down as minimum ORF length) that enables GTG and CTG start codons.

**Comment by njhillson** [comment]
Seems to be working well.

**Comment by XimeMora** [comment]
This is working fine.
