### ISSUE TITLE
ICE - VV view all 6-frame translations

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#195]
A JBEI user has requested the ability to turn on 6-frame translations for the full sequence (not just sub-sequence or ORF translation). This is currently a feature in most Vector Viewer/Editor software including the FLEX version of VE.

**Comment by tnrich** [comment]
this is now available via a right click on the background of any view

**Comment by njhillson** [comment]
Great!

**Comment by XimeMora** [comment]
Looks good!
