### ISSUE TITLE
ICE - VV sequence search using edit-distance mismatch search

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#197]
A JBEI user requested a feature enhancement to sequence search, in which mismatches (e.g. substitutions, insertions, deletions) are allowed. One way of specifying the number and types of mismatches may be specified by an "edit-distance" threshold. Nathan and Ernst will put together a spec for how an edit-distance should be specified by the user, and how this spec would impact the search results.

**Comment by hplahar** [comment]
I will follow up with Ernst and Nathan tomorrow

**Comment by tnrich** [comment]
Closing until we get more info on this
