### ISSUE TITLE
ICE - VV properties translations table issues

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#198]
In the properties translations table, there are multiple issues. These include:
ORF translations not shown.
Size is in DNA bp rather than protein aa.
Strand is not shown.
Name and type fields empty and not clear how these would be derived.

**Comment by tnrich** [comment]
@njhillson should the orf translations show up here? There is already a dedicated Orf panel: 

![image](https://user-images.githubusercontent.com/2730609/34076940-e8f4b314-e298-11e7-9864-ff4718a6d6b7.png)

**Comment by njhillson** [comment]
The ORFs table doesn't have the size in AAs. But good point I suppose. I am going to pass this ticket because it is improved, but I will create new tickets #204 and #205 to cover ORFs table not showing size in AAs, and for new/edit buttons which don't seem to do anything.

**Comment by XimeMora** [comment]
Looks good!
