### ISSUE TITLE
ICE - VE edit can not paste annotated sequence

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#199]
If I attempt to paste in a copied sequence, I lose all the annotations. I should be able to copy and paste and retain the features. There may be some discussion around retaining partial features or not, and I am okay pasting in partial features by default, or at least this should be allowable through some type of a properties setting.

**Comment by tnrich** [comment]
Hey @hplahar I am getting close to having a fix for this one but in order for you to be able to paste from jbei DE into the openVE and vice versa you'll need to do some coercion on your end. Here is what that should look like: 


```
       //this will go right below your existing onCopy method:
       onPaste: function(event, editorState) {
          //the onPaste here must return sequenceData in the teselagen data format
          const clipboardData = event.clipboardData;
          let jsonData = clipboardData.getData("application/json")
          if (jsonData) {
            jsonData = JSON.parse(jsonData)
            if (jsonData.isJbeiSeq) { //or whatever flag you use to tell if the user has copied some jbei sequence 
              jsonData = convertJbeiToTeselagen(jsonData)
            }
          }
          const sequenceData = jsonData || {sequence: clipboardData.getData("text/plain")}
          return sequenceData
        },
```

Please let me know if you have any questions. You should be able to plug this in now and I'll let you know when the code has been pushed on my side so it will actually work.

**Comment by njhillson** [comment]
Hi Thomas. I think that I reported this issue in the context of copy/pasting within VE itself. I don't think we were thinking about copying from DE into VE. Copying from VE to DE (mapping a part) was already capturing the features.

**Comment by tnrich** [comment]
@njhillson I think regardless of that we'll still want to rely on the same clipboard "application/json" api as is used for copying in which case we'll be using the jbei sequence format being stored in the clipboard. So the above code should still apply. 

This will allow you to paste in annotated sequence from DE -> VE in the future if you ever want to or from some other location into VE.

**Comment by njhillson** [comment]
I can't test this effectively right now due to blocking ticket #220 that I am about to create. Seems like a ICE context isseu.

**Comment by njhillson** [comment]
Looks good now for forward/reverse features as well as partial features.

**Comment by XimeMora** [comment]
Copying/Pasting within VE is copying the annotations correctly but if I copy from a sequence in VV (it has the same copy options as VE) to paste into another sequence in VE it is not copying the annotations:

![copy paste](https://user-images.githubusercontent.com/21211903/36119638-6c0d2b26-0ff5-11e8-98b3-bbed4c869d40.gif)

**Comment by njhillson** [comment]
for @hplahar to fix on the VV side

**Comment by hplahar** [comment]
Fixed

**Comment by njhillson** [comment]
This is working for me now. Copied a feature in VV and pasted into another browser tab VE. The feature was maintained.

**Comment by XimeMora** [comment]
This is working fine for me too!
