### ISSUE TITLE
ICE - VE can only delete feature through properties features table

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#200]
I should be able to right click a feature to delete it, or delete should be available from the edit feature modal. Currently, I can only delete a feature through the properties features table.

**Comment by tnrich** [comment]
publishing now, should be ready in 10 minutes

**Comment by njhillson** [comment]
looks good now. Can right click a feature to delete it. Note I can only do this from the sequence panel  or rail view. Right clicking on a feature or feature label in plasmid map doesn't do anything for me because seems to default to browser context menu instead of VE specific one. I will create a ticket for that.

**Comment by XimeMora** [comment]
This looks good.
