### ISSUE TITLE
ICE - VE create feature ignores selection start and stop

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#201]
If I highlight a sub-sequence and right click to create a feature, the modal ignores the selection start and stop and instead defaults to start of 1 and stop of 1. It should default instead to the start and stop of the selection.

**Comment by tnrich** [comment]
publishing now, should be ready in 10 minutes

**Comment by njhillson** [comment]
looks better now.

**Comment by XimeMora** [comment]
Looks good!
