### ISSUE TITLE
ICE - VV copy revese complement copies forward strand

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#202]
If I highlight a sub-sequence and right click to copy reverse complement, the reverse complement is not actually copied. Instead, the forward strand is copied. This is misleading and may lead to errors.

**Comment by tnrich** [comment]
@njhillson interesting this one appears to be caused by the "hooks" I added to allow jbei to manipulate the clipboard's json data. Should be fixable. Nice catch!

**Comment by tnrich** [comment]
Publishing now. The fix should be live in 10 minutes or so

**Comment by njhillson** [comment]
This is still not working  for me.

**Comment by tnrich** [comment]
Looks like Hector pinned registryTest2 to a specific version of openVE again.
Please don't QA until that gets fixed.

**Comment by njhillson** [comment]
This is working now. See, however ticket #199 regarding not being able to paste features.

**Comment by XimeMora** [comment]
This is working fine.
