### ISSUE TITLE
ICE - VE bad autoscroll to search hit region when an addtional feature selected

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#208]
Reported by a JBEI user and related to ticket #177 possibly. To reproduce, open a sequence with a sequence feature. In the view, activate both the plasmid map and the sequence panel. Downstream of a sequence feature, select a sub-sequence (long enough for it to be unique within the sequence - 20 bp should be fine) and then right-click copy it. Open the search tool, and paste the sequence to search for it. Now click to select a feature upstream of the searched-for sequence. Now, if you try to scroll down below, or scroll up above, the selected sequence, the sequence panel will autoscroll to the end of the selection. This is very annoying and makes the tool unusable.

**Comment by tnrich** [comment]
good catch. This was caused by some sloppy copy pasting.

**Comment by njhillson** [comment]
This looks better now

**Comment by XimeMora** [comment]
The issue is not happening now.
