### ISSUE TITLE
Find/Search location - top of page

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#209]
The find/search bar is used often enough to be placed at the top of the page, where it can be accessed quickly and efficiently.

**Comment by tnrich** [comment]
Hey George, here is what the search bar for openVE looks like right now: 
![image](https://user-images.githubusercontent.com/2730609/34692241-55cc98e8-f474-11e7-81cc-197fd61cf5ac.png)

Did you want the search bar moved to the top right or left?

**Comment by gmcarthuriv** [comment]
@tnrich, I would say probably best in the top left, either 1) within the map panel (still below the tool bar) or 2) above the map panel (and part of the tool bar).

**Comment by tnrich** [comment]
@gmcarthuriv sounds good I'll try those locations out

**Comment by tnrich** [comment]
Here's what it looks like on the top left below the tool bar: 

![image](https://user-images.githubusercontent.com/2730609/34779488-34b1e4f8-f5d5-11e7-8822-fcef6dfe483c.png)


Thoughts?

**Comment by gmcarthuriv** [comment]
Very nice, IMO.

**Comment by njhillson** [comment]
Failing. This doesn't work in the ICE - VV context (in the ICE page itself) - it isn't visible at all. And in full ICE - VE context the search tool bar location is too high up and too far to the right.

**Comment by tnrich** [comment]
hmm nice catch @njhillson I thought I had set the z-index to a high value but that work must not have gotten saved. It should work as expected now.

**Comment by njhillson** [comment]
Failing this one. Please test in the ICE context both VV and VE before putting back to ready for QA. In VV, I can now see the search bar, but it is at the top right of the whole ICE entry page, and is no longer rendered within the space allocated for VV. In VE, the placement is too high and too far to the right in the modal. It is obscuring the close button at top right.

**Comment by tnrich** [comment]
Hey @njhillson I am thinking that especially for ICE, it might make sense to have the Find Tool rendered inline: 

![image](https://user-images.githubusercontent.com/2730609/35464691-3145c328-02ac-11e8-9800-69f56ff06d56.png)

![image](https://user-images.githubusercontent.com/2730609/35464709-5707a504-02ac-11e8-8b76-08f1d0c9a50f.png)

The options would need to be in a popover in this case to save space: 

![image](https://user-images.githubusercontent.com/2730609/35464694-3b3b159a-02ac-11e8-808b-7930f120f01f.png)


@gmcarthuriv I'm not sure if this would be your preference over having it docked at the top of the page, but it would be easy to have both as options. 

Any thoughts either of you?

**Comment by njhillson** [comment]
I like the inline just fine and that would address both VV and VE contexts in ICE.

**Comment by gmcarthuriv** [comment]
It looks excellent and is within easy reach (so to speak) - very nice.

**Comment by tnrich** [comment]
The find bar is now inline by default

**Comment by njhillson** [comment]
so much better!

**Comment by XimeMora** [comment]
Looks good! There's only a minor rendering issue that will be addressed in a new ticket.
