### ISSUE TITLE
Improve view options

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#211]
I think the current view options is close to being nice, but it is an awkward experience using that little view dropdown. I think a smoother experience would be to give each view tab a "title" and allow them to be dragged around. 

This could also be a nice way to display additional tools, like a digest result or a sequence alignment or a crispr scoring list.

I went ahead and made a first pass of this to see what it would be like. Here's a gif of that: 

![untitled](https://user-images.githubusercontent.com/2730609/34839719-7ccdf078-f6b7-11e7-8f1d-0fed1bc0a1e1.gif)

This will allow us to get rid of the properties toggle button and the view options toggle button. 

@njhillson @hplahar @mfero any thoughts on this change?

**Comment by njhillson** [comment]
Hi Thomas, I agree that there could be a better way of doing it. Your mock
up doesn't seem so intuitive to me, though. Particularly, I wouldn't think
to click to drag one of the options, or how to create the new panel or
remove an existing panel by dragging to a new area or dragging it back to
an existing panel. Nathan

**Comment by tnrich** [comment]
Hmm I think that with a couple minor tweaks we can make it an intuitive experience.

**Comment by njhillson** [comment]
Ok, happy to look.

**Comment by njhillson** [comment]
Now that I know how this works, I like it quite a bit. Perhaps not entirely intuitive, but having the hover over cursor change to a move icon, and indicating where to drag it to add a new tab is nice. Right click to open in split screen also works.

**Comment by XimeMora** [comment]
I agree that this looks much better, although it wasn't very intuitive for me at the beginning.
