### ISSUE TITLE
Add a general properties tab

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#215]
Adding a general properties tab where users can edit the sequence name, if it's linear/circular, if it is read-only or not, and see its length: 

![image](https://user-images.githubusercontent.com/2730609/35191720-0a4ecaae-fe37-11e7-8a5e-5a26dfc05054.png)

**Comment by njhillson** [comment]
This appears to be disabled in the ICE context. Going to fail. @tnrich please comment if this is expected and I will just leave in Ready for QA.

**Comment by tnrich** [comment]
This will need to be hector implemented: https://github.com/TeselaGen/openVectorEditor/blob/master/UPGRADE_INSTRUCTIONS.md#v111

**Comment by hplahar** [comment]
Added to registry-test2

**Comment by njhillson** [comment]
The properties tab has been added. I will create another ticket regarding default tab on load issue.

**Comment by XimeMora** [comment]
The Properties tab > General is not saving the changes: "Circular/Linear" and "Is Editable" selections go back to the previous one after changing tabs and "Name" goes back to the original one after closing and reopening the plasmid.

![ve properties](https://user-images.githubusercontent.com/21211903/35826222-f921e62a-0a6c-11e8-8b32-7f27daa12bf2.gif)

**Comment by tnrich** [comment]
Okay, those should be disabled correctly now (let 10 minutes pass for the CDN to be updated)

**Comment by njhillson** [comment]
I am passing this ticket, but am going to create 2 new tickets, ticket and ticket for related issues.

**Comment by XimeMora** [comment]
The fields are disabled in the Vector Viewer but I'm going to fail this ticket because in the Vector Editor even after clicking Save button the Name and Circular/Linear fields are not being saved. 

![properties general](https://user-images.githubusercontent.com/21211903/36116439-228dd96e-0feb-11e8-8e75-1f3b045249f2.gif)

**Comment by tnrich** [comment]
It is up to @hplahar to handle the sequence name/circularity saving on the jbei onSave hook. @hplahar do you have any questions for implementing that? Both .circular and .name should be on the sequenceData object.

**Comment by njhillson** [comment]
In the context of ICE, where we are not displaying the general properties tab anymore, this functionality is no longer relevant. @tnrich when you address @XimeMora issue, go ahead and put into ready for qa, and I will just immediately pass on to her.

**Comment by tnrich** [comment]
@njhillson let's close this one as jbei is no longer using it?

**Comment by njhillson** [comment]
Ok
