### ISSUE TITLE
ICE - VE collapse icon rendering issue

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#219]
The collapse icon is rendering in a weird way. Going to attach a screen shot.

**Comment by njhillson** [comment]
![screen shot 2018-01-24 at 4 40 28 pm](https://user-images.githubusercontent.com/4064717/35364729-9370b1b2-0125-11e8-9416-59439e8e1b32.png)

**Comment by tnrich** [comment]
Hmm yeah something is up with the blueprint <Icon> component that I'll need to look into. It looks good for me locally.

**Comment by njhillson** [comment]
Looks better to me now.

**Comment by XimeMora** [comment]
@tnrich I see this 3 lined icon to the far right, is here the only place where I should see it?

![collapse icon](https://user-images.githubusercontent.com/21211903/36690968-c5b96b64-1ae8-11e8-86c3-3f7fdf5d88c7.PNG)

**Comment by XimeMora** [comment]
The collapse icon on New Digest tab looks good now.

![close icon](https://user-images.githubusercontent.com/21211903/37308344-057e5814-25fb-11e8-8454-16c3dca57123.PNG)
