### ISSUE TITLE
ICE - VE can not paste sequence

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#220]
I think that this is likely an ICE context issue. To reproduce open the full VE from an ICE entry page. Open a sequence panel view. Click to select a feature. Right click selection to copy selection. [Aside - and related to this context issue I think - the right click context menu never goes away...] I get a toaster message that the selection was copied - great! However, if I click to select an insertion point in the sequence, and then try to paste - either by keyboard short cut or through browser edit->paste, nothing happens. I would have expected by copied sequence to have pasted.

Now, if I just am in VV in the ICE entry page itself, and I try to do the same thing, I am marginally more successful in pasting (either through keyboard shortcut but not through browser edit->paste), since I at least get a new toaster notification letting me know that the sequence is read-only.

**Comment by tnrich** [comment]
@hplahar this issue is most likely being caused by a null pointer in the code you use to go from jbei json to teselagen json

**Comment by hplahar** [comment]
This is fixed

**Comment by njhillson** [comment]
Looks good now.

**Comment by XimeMora** [comment]
This is working nicely.
