### ISSUE TITLE
Enable possibility to set initial tab view

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#221]
Currently, it appears that the properties tab is viewed by default. This is probably the least interesting and useful tab. It would be good to enable a parameter that can configure the initial tab view (e.g. circular or linear) upon app launch. Setting to high priority/bug, because opening in properties tab mode just seems wrong.

**Comment by tnrich** [comment]
@hplahar should be able to configure this already :) 

Just choose which tabs you want to see and their ordering and active status:

https://github.com/TeselaGen/openVectorEditor#universal-usage 

```
panelsShown: [
		[
			{
				id: "sequence",
				name: "Sequence Map",
				active: true
			}
		],
		[
			{
				id: "circular",
				name: "Plasmid",
				active: true
			},
			{
				id: "rail",
				name: "Linear Map",
				active: false
			},
			{
				id: "properties",
				name: "Properties",
				active: false
			}
		]
	],
```

**Comment by njhillson** [comment]
This is looking good now

**Comment by XimeMora** [comment]
The tab viewed by default is the Plasmid tab, looks good.
