### ISSUE TITLE
Highlight corresponding codon(s) when AA(s) is/are selected

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#223]

**Comment by tnrich** [comment]
Below is an image of a feature being hovered over.

@gmcarthuriv just to be sure we're on the same page, you're suggesting that we highlight the AA's similarly to how we do features when they're being hovered over?


![image](https://user-images.githubusercontent.com/2730609/36042268-1f91b6d0-0d80-11e8-8039-316eba9c85a4.png)


Or do you want to be able to click an AA chain and have them stay selected?

**Comment by gmcarthuriv** [comment]
@tnrich, I'm suggesting that when you click on an AA residue, the three-nucleotide codon is selected. This happens already in Peony's VE. However, it's not possible in the current VE to select multiple AA residues. It would be very nice to have multiple codons selected when multiple AA residues are clicked (using "shift"). This is analogous to how GenBank feature(s) is/are clicked and the corresponding nucleotide sequence is selected (as sequences can be selected by holding down "shift" and clicking multiple feature labels).

![image](https://user-images.githubusercontent.com/17152701/36057116-52dbb24a-0dbf-11e8-8076-93fc93348db4.png)

**Comment by tnrich** [comment]
@gmcarthuriv thanks for the clarification. I think we can implement it the way you're suggesting :)

**Comment by XimeMora** [comment]
Highlighting corresponding AA's codons is working nicely.
