### ISSUE TITLE
Add amino acid indexing/numbering

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#224]
Being able to quickly find a position/residue is helpful. An easy way to do this is to number the amino acids. I've included a screenshot from Benchling as an example.

![image](https://user-images.githubusercontent.com/17152701/35591505-0dd33d38-05bf-11e8-8c05-a7604d676fc7.png)

**Comment by gmcarthuriv** [comment]
Could be shown when hovered over

**Comment by tnrich** [comment]
![image](https://user-images.githubusercontent.com/2730609/36006569-9f4d7c8a-0cf2-11e8-854e-4016245f2c26.png)

@gmcarthuriv how does that look?

**Comment by gmcarthuriv** [comment]
It looks beautiful, @tnrich - but what exactly am I looking at here, just the AA sequence? I realize this is a mockup, but the amino acid translation doesn't match the correct open reading frame. However, overlooking that, it looks great! :D

**Comment by tnrich** [comment]
Hey @gmcarthuriv you're seeing an arbitrary section of the sequence translated here. You can right click and hit "View Translation" on any selection layer to translate whatever you want.

**Comment by njhillson** [comment]
I am seeing the tooltip index number now.

**Comment by XimeMora** [comment]
Looks good!
