### ISSUE TITLE
Rotate to here

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#225]
Implement the "Rotate to here" feature from the flash based version of Vector Editor which allows selection of a base pair and rotating it to the origin

**Comment by tnrich** [comment]
Should we be able to rotate a linear sequence?

**Comment by hplahar** [comment]
Yes

**Comment by XimeMora** [comment]
@tnrich as I saw in ticket #296 we are not allowing to rotate a linear sequence, right?

**Comment by XimeMora** [comment]
"Rotate to here" is working nicely.

**Comment by AdamZMc** [comment]
Looks great!
