### ISSUE TITLE
Shift click to select multiple features

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#227]
Enable the ability to shift click to select multiple features (and the base pairs in between). This will expand a selection and not result in multiple independent selections (a la ctrl click)

**Comment by tnrich** [comment]
A question for @njhillson - should this be for features only, or should the same sort of "expand selection" functionality apply for features/orfs/parts/cutsites?

**Comment by tnrich** [comment]
Hmm @hplahar it looks like this functionality already exists within the tool :) check it out

**Comment by njhillson** [comment]
It does seem to be working already for me too. There may be some behavior
nuances that we'd want to look more closely into, but Hector please look
too.

**Comment by hplahar** [comment]
Working for me also. There are a few instances, where, for some reason it did not work but I think that can be a separate ticket when I am able to reproduce it reliably

**Comment by XimeMora** [comment]
It seems to be working but I also noticed that sometimes it didn't, I tested several times but I couldn't figure out why sometimes it's not working.
