### ISSUE TITLE
ICE - VE - context menu doesn't go away if you don't select any option

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#229]
Context menu doesn't disappear if you don't select any option from that menu. This is happening in all the tabs: Sequence Map, Plasmid and Linear Map.

![context menu](https://user-images.githubusercontent.com/21211903/35832041-a1423aa4-0a80-11e8-9034-51ee28d91a5f.gif)

**Comment by njhillson** [comment]
looks much better now.

**Comment by XimeMora** [comment]
Looks good!
