### ISSUE TITLE
ICE - VV -> Right-clicking in the Sequence Map makes the panel do a little jump

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#230]
Just by right-clicking in the Sequence map the panel makes a weird jump. If something is selected it makes the selection to lose focus.

![right click jump](https://user-images.githubusercontent.com/21211903/35837517-6a18977e-0a9b-11e8-857c-aed7978f9ba2.gif)

**Comment by tnrich** [comment]
Hmm very strange. I am not able to reproduce this issue locally. I'll probably need you to help me debug what's going on here. It looks like something is maybe getting added to the DOM that's causing the width of the editor to expand/shrink as it gets added/removed.
