### ISSUE TITLE
ICE - VE backspace key triggers browser to go to previous page

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#231]
I was testing ticket #140, which relates to enabling the user to delete a highlighted sequence using the backspace key. At least for me in FireFox in OSX, it appears that the browser is listening for the backspace key, and goes to the previous page if it hears it. This is not great behavior, because that means that I lose all my edits in VE. Can you over-ride the default browser behavior so that it does not trigger the previous page action? In parallel, Hector will be working on ticket that if the current sequence has been edited, that it will ask the user if she really wants to close the modal or leave the current page before saving...

**Comment by njhillson** [comment]
This seems better for me now.

**Comment by XimeMora** [comment]
This is working fine.
