### ISSUE TITLE
ICE - VV/VE feature colors not set correctly

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#232]
Right now, it looks like VE is randomly setting feature colors, and even using different colors for the same feature type. We want the JBEI color palette to be used. Hector tried to send VE the color to use for each feature, but VE is appearing to ignore these directives.

**Comment by tnrich** [comment]
@njhillson can you check and see if this one is working correctly for you now? I've set things up to obey a passed in color first, and then use the standard feature type colors secondarily.

**Comment by njhillson** [comment]
Coloring looks bad still on
registry-test2.jbei.org

CDS for example should be orange.

**Comment by njhillson** [comment]
Ok, this is looking better now on registry-test2.jbei.org. Colors as expected for the most part. Some feature types have different coloring than I expected (e.g. primer features are light green instead of grey), but at least they appear consistent for each feature type, and the colors are expected for the important feature types (e.g. CDS orange).

**Comment by XimeMora** [comment]
@njhillson the colors are consistent for each feature type and I can see that the CDS is orange but I'm not sure which ones are the most important feature types and their respective colors, could you share a list of those? or just checking that they are consistent is enough for now?

**Comment by njhillson** [comment]
hi @XimeMora; perhaps basic summary here:
CDS orange
promoter green
terminator red
RBS grey
misc_feature blue
ori grey
selectable_marker turqoise
Looks like the RBS isn't grey, so you can fail for that if you'd like.
Otherwise mostly looks reasonable to me right now...

**Comment by XimeMora** [comment]
Thanks @njhillson. A few more questions... Is "ori" the same as "oriT" because that's the similar one that I found. I don't see any "selectable_marker", does it have another name? And the "misc_feature" and "misc_binding" look the same color to me, is it the same for you?

**Comment by njhillson** [comment]
origin feature type should cover oriT as well.

misc_marker may be the type for the marker type.

misc_feature and misc_binding are find to both be blue.

Nathan

**Comment by XimeMora** [comment]
As @njhillson said RBS isn't grey and oriT is not grey either so I will fail it.

**Comment by tnrich** [comment]
I have changed both of those from gray in response to George Macarthur requesting that there be fewer feature types that defaulted to gray.

**Comment by njhillson** [comment]
That is fine for Arzeda, but not for JBEI.

**Comment by tnrich** [comment]
We need a way for consumers to pass color preferences for feature types. Let's make a new issue and pass this one?
