### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#235]
![double_scroll_bar](https://user-images.githubusercontent.com/1694026/36053873-670e1d6e-0da8-11e8-8bc6-385b454ddf15.png)
With version 1+, scrollbars are now visible in the view area. This results in double vertical scrollbars when viewing the sequence map only. See attached

**Comment by tnrich** [comment]
@XimeMora can you help me try to reproduce and debug this issue. I'm not able to see this on my computer unfortunately

**Comment by XimeMora** [comment]
@tnrich I tried to reproduce it but I am only seeing one vertical scrollbar:

![2018-02-20](https://user-images.githubusercontent.com/21211903/36443570-00340ad4-162e-11e8-9f23-e9a80706feac.png)

@hplahar can you check if this is still happening on your end?

**Comment by hplahar** [comment]
Looks better now. Not happening anymore

**Comment by XimeMora** [comment]
Perfect! I'll move this ticket along then.
