### ISSUE TITLE
Find/Search tool > Literal/Ambiguous field not big enough

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#237]
In the Find/Search tool after clicking the pencil icon the Literal/Ambiguous field box is smaller and the selection arrows are partially left outside the box:

![literal](https://user-images.githubusercontent.com/21211903/36117111-5bcddd62-0fed-11e8-9054-8f56c2b1c918.PNG)

**Comment by njhillson** [comment]
This seems fine to me now.

**Comment by XimeMora** [comment]
Looks good.
