### ISSUE TITLE
Undo/Redo buggy behavior after deleting bps

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#238]
I selected some bps and created a feature, then select some bps that were right before the newly created feature and deleted them using the backspace key, then click the Undo button and the delete action was undone but the feature that I created earlier moved from its original place, so clicking Redo now is buggy too because of this feature moving from its original bps.

![undo redo](https://user-images.githubusercontent.com/21211903/36120716-e8c5b2f2-0ff8-11e8-8e94-c47707ec5297.gif)

I think this is happening with an existing feature too, you don't need to create a new one.

**Comment by tnrich** [comment]
Nice catch @XimeMora this should be fixed shortly.

**Comment by njhillson** [comment]
This looks better now.

**Comment by XimeMora** [comment]
This is working nicely.
