### ISSUE TITLE
ICE - VE properties tab should default to first tab if no tab found

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#239]
In ICE, we have disabled the general properties tab, and so when I click on the properties tab, no subtab is active. I have to click, for example, on features for something to render. It would be nice to have the first tab (e.g. features) active on load if the general properties tab is missing.

**Comment by njhillson** [comment]
Looks good now.

**Comment by XimeMora** [comment]
This looks good!
