### ISSUE TITLE
Ability to toggle letter case for DNA sequence

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#240]
Currently, the openVE displays DNA sequences in lowercase letters. Some may like this, but I prefer uppercase DNA sequences. It would be nice to be able to toggle between upper and lowercase.

**Uppercase example**
![image](https://user-images.githubusercontent.com/17152701/36134041-1afeb352-1037-11e8-950a-cb7701caf813.png)

**Comment by tnrich** [comment]
@gmcarthuriv currently OVE displays the sequence as either upper or lower case depending on how it is imported into our system. For example it can display upper and lower case letters simultaneously: 

![image](https://user-images.githubusercontent.com/2730609/36360955-1f9fa66e-14dd-11e8-9a2b-064b298c85fe.png)

That being said, I can add an option to always display the sequence as just upper/lower case, but that would be display only -- it wouldn't affect how it would be exported or saved. Does that sound okay to you?

**Comment by gmcarthuriv** [comment]
@tnrich - sounds good to me. When I created the ticket, it was based on what I saw in the demo openVE. Soon after, I saw my sequences in the LIMS openVE displayed in uppercase, which is great.

It's cool that you allow both upper or lowercase - very useful for communicating mutations, for example. Maybe your toggle tool simply inverts the case (i.e., all uppercase letters are converted to lowercase and vice versa). That way you can keep the explicit differences while allowing stylistic preferences.

**Comment by gmcarthuriv** [comment]
@tnrich,

In ApE, the keyboard shortcut '**Cmd =**' toggles between upper and lower case. It's very handy. :D

**Comment by tnrich** [comment]
Hey George I'll make it happen :)

**Comment by XimeMora** [comment]
Ability to toggle between upper and lowercase is working nicely.
