### ISSUE TITLE
Editor jumping when embedded in lims

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#241]
I am guessing that the scroll jumping for the Sequence View is somehow spilling over.

**Comment by tnrich** [comment]
@tgreen7 let me know when the full-screen enabled editor is in there and we can close this!

**Comment by tgreen7** [comment]
@tnrich The preview mode has been added

**Comment by tnrich** [comment]
I'll close this one. Do you know if there is a linked issue in lims @tgreen7
