### ISSUE TITLE
Default settings for translation-to-AAS

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#242]
Currently, amino acid sequences (AASs) translated from _predicted_ ORFs are displayed by default. I think that these should be off by default - and then toggled on by the user if desired. 
 - [x] orf translations off by default

However, for _annotated_ CDSs (i.e., GenBank feature = CDS), I think these AASs should be displayed by default.
- [x] features of type cds on by default

**Comment by tnrich** [comment]
Ahh interesting. Okay, I can make that happen. Keep the great suggestions coming!

**Comment by tnrich** [comment]
Okay, these should both be in the latest OVE version

**Comment by XimeMora** [comment]
This is working correctly.
