### ISSUE TITLE
Reveal GenBank feature type when hovered over

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#243]
Currently, only the feature name and start/end positions are displayed when a GenBank feature is hovered over. It would be nice to also display the feature type (e.g., CDS) upon hovering. This is enabled in the current app (Peony) and the JBEI VE (shown in the screenshot below).

![image](https://user-images.githubusercontent.com/17152701/36346996-6d3185a6-1400-11e8-930a-9e12ee497c3a.png)

**Comment by tnrich** [comment]
This should be fixed whenever lims and hde update to open-vector-editor@1.1.32

 @tgreen7 @craftjk

**Comment by njhillson** [comment]
This is looking good

**Comment by XimeMora** [comment]
Looks good on hde and lims!
