### ISSUE TITLE
VE and/or DE > ability to merge two GenBank features

### ISSUE THREAD

**Issue by mfero** [TeselaGen/openVectorEditor#246]
_From @gmcarthuriv on January 26, 2017 18:10_

Assembled constructs may need to have their feature annotation "cleaned up" due to a variety of factors. One case is the splitting of a GenBank feature into two because it spans two or more Parts. Another case is a discontinuous GenBank feature because it is the literal result of two features (and Parts) being joined together. For example, a CDS (and Part) without a stop codon may need to have "TAA" Part added for proper function. The "TAA" is a Sequence and a Part - and could also be a GenBank feature (at least, that's the way I would work with it). The resulting construct would have the annotated CDS followed by "TAA," which I would also annotate as a CDS feature. It would be nice to able to merge these two features into one within VE and possibly even describe this in DE before the job is run.

**VE workflow**
* Assembled construct sequence is viewed in VE
* Two adjacent features are selected
* Right-click and select "merge features"
* Option to name new concatenated feature one of the existing names or a new name
* Two features would become one

**DE workflow**
* Select two adjacent columns in the Design
* Right-click and select "merge adjacent features of same type"
* The resulting assembled construct(s) would display the merged feature

_Copied from original issue: TeselaGen/ve#3477_

**Comment by tnrich** [comment]
@mfero @gmcarthuriv

What do you all think about the following interface?

![image](https://user-images.githubusercontent.com/2730609/39893721-8a35b782-5459-11e8-878a-99fb8476222b.png)

Hovering the plus button looks like: 
![image](https://user-images.githubusercontent.com/2730609/39893741-96ea2f9e-5459-11e8-9f9d-df7e695788e8.png)

**Comment by mfero** [comment]
Should we have the option of keeping original annotation and adding new?

**Comment by tnrich** [comment]
I'm not sure I fully understand @mfero. What are you saying exactly?

**Comment by mfero** [comment]
A checkbox to "keep original annotation". So the original annotation does not get replaced.

**Comment by tnrich** [comment]
Oh I see. Yep I'll add that option in there!

**Comment by XimeMora** [comment]
This functionality is working fine, I just noticed some issues related with it that will be addressed in a new ticket.

**Comment by craftjk** [comment]
@XimeMora you can open this up as a Arzeda ticket in hde

**Comment by XimeMora** [comment]
This issue was moved to TeselaGen/hde#1574

**Comment by XimeMora** [comment]
There is a ticket now in hde for the DE workflow described above https://github.com/TeselaGen/hde/issues/1574

I also created the following tickets for issues related with the Merge Features functionality: #324 #325 and #326
