### ISSUE TITLE
VE > Map panel > include alternative start codons for ORF prediction

### ISSUE THREAD

**Issue by mfero** [TeselaGen/openVectorEditor#247]
_From @gmcarthuriv on April 27, 2016 0:15_

It may be useful to some users to be able to modify ORF prediction to include alternative start codons such as GTG.

_Copied from original issue: TeselaGen/ve#1841_

**Comment by tnrich** [comment]
![image](https://user-images.githubusercontent.com/2730609/36697743-d66bee28-1afc-11e8-9546-3cdf576a26fb.png)

This feature exists in OVE already
