### ISSUE TITLE
VE > not able to find very long DNA sequences

### ISSUE THREAD

**Issue by mfero** [TeselaGen/openVectorEditor#248]
_From @gmcarthuriv on September 13, 2016 6:19_

I was searching for a rather long sequence of DNA (5201 bp of a 5636 bp plasmid - most of the plasmid) and found that the search/find function wasn't working as expected. The tool couldn't "find" my long sequence; VE was telling me that the sequence was not present. Strangely, it would highlight the sequence if I clicked on the "Highlight All" button (as shown below).

![image](https://cloud.githubusercontent.com/assets/17152701/18463307/0a58fa80-793e-11e6-8e2e-824e78376848.png)

_Copied from original issue: TeselaGen/ve#2605_

**Comment by mfero** [comment]
Is this also and issue on OVE? moving this ticket to that repo.

**Comment by tnrich** [comment]
This does not look like it is an OVE issue @mfero
