### ISSUE TITLE
VE > Annotations that span the entire sequence don't have its label connector line

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#249]
_From @XimeMora on February 26, 2018 20:59_

### Describe what's going wrong/what needs to change.
Annotations that span the entire sequence don't have its label connector line.
### Steps to reproduce the behavior
Create a feature/part that is the same length of the sequence
### Screenshots/gif of issue
![no annotation lines](https://user-images.githubusercontent.com/21211903/36694930-9ff349a2-1af4-11e8-9c03-082c214838be.PNG)

_Copied from original issue: TeselaGen/hde#854_

**Comment by XimeMora** [comment]
_From @mmatena on March 1, 2018 18:15_

This should probably be an `open-vector-editor` ticket.

**Comment by tnrich** [comment]
@XimeMora can't reproduce, are you able to? If so can you attach a failing .gb file? Thanks!

**Comment by XimeMora** [comment]
Yes, it's still happening to me on hdedev. Try using the context menu from the sequence library "Create Part/Feature from Sequence", or it is also happening creating a part/feature inside the vector editor (only for the annotations that span the entire sequence) And for features, I can see a very short label connector line:
[Sequences.zip](https://github.com/TeselaGen/openVectorEditor/files/1878467/Sequences.zip)
Feature
![connector line](https://user-images.githubusercontent.com/21211903/38346161-27e2c0fc-3848-11e8-9ec0-e281ee842005.PNG)

Part
 
![connector line2](https://user-images.githubusercontent.com/21211903/38346193-52587e4e-3848-11e8-85d7-2d934b9e36c9.PNG)

**Comment by tnrich** [comment]
Thanks Xime I'll check it out

**Comment by tnrich** [comment]
Hey @XimeMora I don't think that file you sent me has the messed up label drawing in question. Could you make sure it is correct and send it again?

**Comment by XimeMora** [comment]
@tnrich sure!:

For the sequence's part:
[pj5_00001.gb.zip](https://github.com/TeselaGen/openVectorEditor/files/1965339/pj5_00001.gb.zip)

For the sequences's feature:
[pj5_00001.gb.zip](https://github.com/TeselaGen/openVectorEditor/files/1965344/pj5_00001.gb.zip)

**Comment by tnrich** [comment]
Oof finally! I figured out why it wasn't working. I'll push a fix soon.

**Comment by tnrich** [comment]
Fix is pushed!
