### ISSUE TITLE
File importing

### ISSUE THREAD

**Issue by jakecoble** [TeselaGen/openVectorEditor#25]
Should support FASTA, Genbank, and SBOL

**Comment by tnrich** [comment]
@jakecoble , @mfero, @njhillson @nixonpjoshua 

Teselagen has a very modular set of import/export functionality that we could potentially open souce and use with this project. 

@mfero, any thoughts on this?

It works very well with genbank/fasta and does handle SBOL, but not as well as the jbei sbol - genbank converter does.

**Comment by tnrich** [comment]
I talked with @mfero and got the okay to open source our import/export functionality. Whoever ends up working on this should talk with me about what needs to be done to hook up to our import/export system. 

Also this might be something that isn't added into the core of the editor, and instead we simply expose hooks to plug into various import/export systems.

**Comment by hplahar** [comment]
@tnrich That will be preferred. When it is integrated with ICE, it will have to rely on the server side for the sequence type support.

**Comment by tnrich** [comment]
Sounds good. It'll be import/export agnostic
