### ISSUE TITLE
ICE - VE rendering of feature (color) should be re-rendered after feature type changed

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#250]
In VE (in ICE context at least), if I edit a feature, and change its type (e.g. from promoter to terminator), it doesn't look like the view is being re-rendered, so the feature color is not updated. This is confusing.

**Comment by njhillson** [comment]
This is looking better now. I noticed that the sequences changes don't seem to be saving back to ICE, but I am following up on this with Hector.

**Comment by XimeMora** [comment]
This is working correctly.
