### ISSUE TITLE
Under Properties, double-clicking an entry should jump the Sequence Map to it

### ISSUE THREAD

**Issue by laueste** [TeselaGen/openVectorEditor#253]
For easier navigation of longer sequences, when you open the Properties tab on the right side and are looking at various lists of "interesting locations" (aka Features, Cutsites, Parts, Primers, ORFs, etc.), double-clicking on an entry in the list on the right should make the Sequence Map on the left jump to that region of interest. (Otherwise you have to scroll around to find it, or search explicitly for the nucleotides, and that's way less fun).
Similarly and in the other direction, perhaps clicking on a feature/cutsite/other sequence map object in the Sequence Map window (which right now highlights/selects the whole object and its sequence) should _also_ highlight its entry in the appropriate Properties list, so you can see exactly which one you've clicked on.

**Comment by njhillson** [comment]
This looks good. Seems like ORF translation rendering is currently broken. Will create another ticket for that.

**Comment by XimeMora** [comment]
This is working for Features and ORFs but not for Cutsites and it is working in one direction (clicking on an entry in the Properties tab highlights the object in the Sequence Map) should we have the same but in the other direction working too (clicking on an object in the Sequence Map highlights its entry in the Properties tab)?
I also noticed the Translations rendering is broken.

**Comment by tnrich** [comment]
Closing for now. We can open a new issue for remaining issue.
