### ISSUE TITLE
Alignments > fix scroll issues up down

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#255]
![image](https://user-images.githubusercontent.com/2730609/37050943-0f974c14-212a-11e8-8e43-5adde78fbb77.png)

scrolling should be improved

**Comment by XimeMora** [comment]
@tnrich what was exactly the problem with the scrolling? The alignment that I'm seeing looks different than your image above. Also it is placed at the bottom of the page leaving a blank space at the top:

![screen shot 2018-04-25 at 3 38 33 pm](https://user-images.githubusercontent.com/21211903/39276818-aaab04e2-489f-11e8-9ec9-d6e8810940ba.png)

**Comment by tnrich** [comment]
@XimeMora this one is old. Closing
