### ISSUE TITLE
Alignments > make the zoom work smoothly

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#257]
![image](https://user-images.githubusercontent.com/2730609/37051044-5381bbee-212a-11e8-827e-ed4e996507d2.png)

Currently the yellow viewing region indicator overflows the bounds of the minimap when zoomed out all the way. 

Also we should add an option to drag the sides of the yellow indicator to adjust the zoom to a particular region :)

**Comment by XimeMora** [comment]
I'm failing this one because when toggling between full screen and back the adjusted zoom is not preserved and is behaving different. 
Also you can move the yellow indicator but not drag the sides to adjust the zoom.
(I'll add the gif...)

**Comment by tnrich** [comment]
@XimeMora can you pass this one and make new issues for what you mentioned please :)
