### ISSUE TITLE
Alignments > Add option to toggle which parts of the sequence track you're interested in seeing

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#258]
![image](https://user-images.githubusercontent.com/2730609/37051226-b027ff34-212a-11e8-8f57-8ed595a8b2a8.png)
Probably next to the name there should be a little button with a context menu allowing you to select Features/Parts/Orfs/Axis/etc

**Comment by XimeMora** [comment]
There is an eye icon with the visibility options. Looks good.

![screen shot 2018-04-25 at 6 26 47 pm](https://user-images.githubusercontent.com/21211903/39280830-5e3a9d04-48b6-11e8-922d-927a7beaef52.png)

**Comment by AdamZMc** [comment]
Looking good.
