### ISSUE TITLE
Implement autosave functionality

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#260]
We need autosave functionality in vector editor.

**Comment by tnrich** [comment]
For HDE or LIMS or both? @craftjk @tgreen7 I'd be happy to work on this together at some point.

**Comment by tnrich** [comment]
I believe this has been implemented in HDE

**Comment by XimeMora** [comment]
Autosave is working in HDE! 👍

**Comment by AdamZMc** [comment]
Looks good!
