### ISSUE TITLE
Alignments > give users option to auto-trim before aligning

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#261]
![image](https://user-images.githubusercontent.com/2730609/37067615-7a0ec74a-215f-11e8-9472-9865595a1440.png)

If the user is uploading sequences to be aligned, and those sequences have confidence scores associated with them, let's have the option to have those sequences be auto-trimmed before they are aligned

**Comment by tiffanydai** [comment]
![screen shot 2018-06-26 at 4 11 38 pm](https://user-images.githubusercontent.com/35508772/41944298-09bf7552-795c-11e8-8dde-93c216480459.png)

**Comment by tiffanydai** [comment]
Sample .ab1 files attached for QA (unzip before use). For alignment options, select template to be Lib89.gb as shown in screenshot below, and check 'Align Sequencing Reads' & 'Auto-Trim'. 

[Sampleab1files.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5e81f1544df200117dae6f/125516c66e82c728ace21e0d46db9597338e86a88db8b94aa858e3d665043761260ea62864c7b96aea142a570b5a18ff415c5f44fcfc8d23a6b63c76d85d0ee9c3714d36976345f3e5db55ea43a82a994e8cbcbd8f4fc0e0342def838f463d1a1755.zip)

![42006844-2dcd4d90-7a31-11e8-8c64-377b87ee37b3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5e81f1544df200117dae6f/125516c66e82c728ace21e0d46bcc6ca73d4dbfddba4ed47a759a49070166a242857f26621d4e670f21a78575b424dab460a5743a9ac8a2cf4b52e6c981c49b28b380c30d43703a9be8319eb04ec738b4b85b6bc8f48c8e83d25e1d98e4a3a0c190acbae0361ffc412820db459eb5f54ac193766e5763e754f9c18762a626e34e6.png)

**Comment by XimeMora** [comment]
This is working nicely!
