### ISSUE TITLE
Figure out API for jbei to load in their own alignments

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#263]
We'll need to talk with @njhillson and @hplahar and show them what our current alignment tool is looking like and figure out how to allow them to load their existing alignment data into our tool.

**Comment by tnrich** [comment]
Here is a little description of how alignments will work in OVE (jbei will probably only use part of the entire flow): 

User hits the alignment tool and can see a list of their saved alignments and start new alignments: 
![image](https://user-images.githubusercontent.com/2730609/37068065-bc1f4d92-2161-11e8-8179-95948303c223.png)

After hitting Create New Alignment they're brought to a modal where they can upload files they'd like to align or insert them manually as text: 

![image](https://user-images.githubusercontent.com/2730609/37068097-de6eeab0-2161-11e8-81f3-bd8c9bfb9e7f.png)

When they hit Create Alignment, the sequences are sent to the Teselagen j5server and are aligned via mafft or muscle depending on what the user wants. If a sequence has confidence scores associated with it, a little confirmation box pops up asking if the user wants to have the sequence be auto-trimmed before alignment. 

After the aligned sequences come back from the server, the user is shown a new tab that contains the alignment: 

![image](https://user-images.githubusercontent.com/2730609/37068176-47954a16-2162-11e8-8784-631038150ef7.png)

The alignment is driven by an array of "tracks" structured like so: 
```
[ {
sequenceData
alignmentData
}, {
sequenceData
alignmentData
}, ...etc]
```

The alignmentData and sequenceData both adhere to the teselagen sequence data format 
(aka {sequence: "atagaccatac", features: [{start: 10, end: 4}], ...etc}

The only difference is that the sequence of the alignmentData may contain gap characters: {sequence: "at--ag--acca----tac"} and the alignment data features/parts/etc. are ignored in favor of the features/parts/etc on the sequenceData. 

All of the "tracks" being passed to the alignment view are assumed to have the same length alignmentData.sequence.

Using this info, we're able to show the user a view that looks like so: 

![image](https://user-images.githubusercontent.com/2730609/37068402-5e444b12-2163-11e8-8235-ae01e14d9196.png)

(note the above screenshot is still very rough right now and will look nicer with real data)

Within the alignment view, the user is able to scroll around to various points in the alignment using the minimap, as well as toggle on and off various annotations that they are interested in like features/translations etc. 

Optionally the user will be able to trim the aligned sequences further if they are unsatisfied with the alignment and send the alignment to the server again for re-aligning.

Does this all makes sense to you @njhillson and @hplahar

**Comment by njhillson** [comment]
Hector will need to coordinate and make sure it can work for us. Once I see it presenting our sequence alignment data starting with sanger and then eventually miseq consensus I will give you feedback.

**Comment by njhillson** [comment]
It would be good for you to demo this in the next TeselaGen/JBEI zoom
meeting this coming Monday. Would be very nice for you to present with an
actual JBEI sequence and Sanger reads, e.g. from entry:
https://public-registry.jbei.org/entry/226/sequences

**Comment by XimeMora** [comment]
@tnrich should we move this ticket back?
