### ISSUE TITLE
Alignments > minimap axis not overflowing/displaying nicely

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#265]
![image](https://user-images.githubusercontent.com/2730609/37117481-3ae9efa2-2206-11e8-9784-d33dcc993aaf.png)

**Comment by XimeMora** [comment]
It still looks the same to me:

![screen shot 2018-04-25 at 4 03 37 pm](https://user-images.githubusercontent.com/21211903/39277380-48fd0c2e-48a2-11e8-8650-5362cad542e6.png)

**Comment by tnrich** [comment]
Closing as this is too vague
