### ISSUE TITLE
Alignments > Only show "saved alignments" if the user sets it up

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#267]
If the OVE consumer doesn't specify a way for alignment data to be loaded we should probably not even show the little tool dropdown: 

![image](https://user-images.githubusercontent.com/2730609/37168945-4970786a-22bb-11e8-8a5e-7d9e1ede4490.png)

Instead we should jump them directly to the "Create Alignment" dialog

**Comment by XimeMora** [comment]
I don't see that option now. There is a ticket with a fix/enhancement related to this #301

**Comment by AdamZMc** [comment]
Looks good.
