### ISSUE TITLE
Show number of annotations within the sequence in visibility toggle tool

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#272]
![image](https://user-images.githubusercontent.com/2730609/37436721-9306ab94-27a6-11e8-8c35-8ba82c17d777.png)

We should for example say that there are 11 Features and 12 parts

**Comment by tnrich** [comment]
Do the same thing for the alignment visibility toggle but it should be cumulative across annotation types

![image](https://user-images.githubusercontent.com/2730609/37436751-bfeedac8-27a6-11e8-9f2d-8a590da2336c.png)

**Comment by tnrich** [comment]
It should now look like this: 
![image](https://user-images.githubusercontent.com/2730609/37623553-52ef3668-2b82-11e8-9614-20546a91aeb0.png)

**Comment by njhillson** [comment]
I see the numbers.

**Comment by XimeMora** [comment]
Number of annotations is there.
