### ISSUE TITLE
ICE VE/VV - ORF translation rendering broken

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#276]
In the current dev version on registry-test2.jbei.org at least, it looks like ORF translation rendering is broken. It looks like there is vertical space (a track) getting added, but the actual AA renderings are not there. Looks like in the versions on the JBEI and ABF ICE instances, that this is still working, so likely a recent change that broke this.

**Comment by tnrich** [comment]
This will be fixed once blueprint releases their fix: https://github.com/palantir/blueprint/issues/2272

**Comment by tnrich** [comment]
This broke when we added gap spacing for the alignment view. Should be better now.

**Comment by njhillson** [comment]
Looks like this has been fixed.

**Comment by XimeMora** [comment]
ORF translations are displaying correctly now.
