### ISSUE TITLE
ICE - VV/VE -> Toastr messages are too big and not centered

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#277]
After performing an action like copy or paste, the notification toastr messages are too big and not centered.

![2018-03-19 1](https://user-images.githubusercontent.com/21211903/37619106-a89f52da-2b75-11e8-9ca0-91b67a937d2e.png)

![2018-03-19 2](https://user-images.githubusercontent.com/21211903/37619179-ed62ae44-2b75-11e8-8dab-2ba040ff1753.png)

**Comment by tnrich** [comment]
This will be fixed once blueprint releases their fix: palantir/blueprint#2272

**Comment by XimeMora** [comment]
@craftjk this is happening in hde too so I guess we'll have to wait for that blueprint update?

**Comment by tnrich** [comment]
This should be fixed now in blueprint :)

**Comment by AdamZMc** [comment]
Looks good!
