### ISSUE TITLE
Editor Preview Mode fullscreen not working

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#279]
Hey @tgreen7 the fullscreen looks good but it doesn't update when the window changes sizes so you get weird looking things like so: 

![image](https://user-images.githubusercontent.com/2730609/37729626-b7e839a6-2cfa-11e8-8c01-55ff20b7a628.png)

![image](https://user-images.githubusercontent.com/2730609/37729691-f0780e54-2cfa-11e8-971a-f7c7d3fd7f93.png)

**Comment by tgreen7** [comment]
@tnrich This seems to happen when making tabs full screen as well. Would you want to pair on it at some point?

**Comment by tnrich** [comment]
I fixed this one. Should be good to go. Also made the fullscreen mode look nicer by having the height scale to fill the entire window:


![image](https://user-images.githubusercontent.com/2730609/38149787-d767a150-3410-11e8-9b80-94121684cd49.png)



@njhillson I think we should talk about improving the modal window approach you guys have taken to use the fullscreen mode instead. It should just generally look cleaner IMO.

**Comment by AdamZMc** [comment]
Looks good!

**Comment by XimeMora** [comment]
This is working fine.
