### ISSUE TITLE
Editor Preview Mode "View Fullscreen" button looks awkward

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#280]
![image](https://user-images.githubusercontent.com/2730609/37729827-49dea99e-2cfb-11e8-8877-dcf5e636d42f.png)

I definitely think it would look better if we did a little hover over type thing..

@tgreen7

**Comment by tgreen7** [comment]
@tnrich I pushed a fix

**Comment by tnrich** [comment]
![image](https://user-images.githubusercontent.com/2730609/38148467-860029fe-340b-11e8-9468-51b7dd02d32a.png)

much nicer :)

**Comment by XimeMora** [comment]
This looks much better now.

**Comment by AdamZMc** [comment]
Looks good!
