### ISSUE TITLE
HDE - Invalid characters should not be allowed in the sequence view

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#281]
We should not allow to insert invalid characters in the sequence view:

![copy paste ve](https://user-images.githubusercontent.com/21211903/38110444-86d36cda-3350-11e8-8220-3878d2f9baf1.PNG)

This is what VE in Peony does:

![2018-03-29](https://user-images.githubusercontent.com/21211903/38110458-96e02442-3350-11e8-8abe-285039316fc2.png)

**Comment by tnrich** [comment]
This should be fixed now

**Comment by XimeMora** [comment]
This looks good.

**Comment by AdamZMc** [comment]
Issue has been resolved!
