### ISSUE TITLE
HDE - Properties > General > Circular/Linear not saving

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#282]
Changing the sequence between circular and linear options in the Properties > General tab is not saving.

![circular-linear](https://user-images.githubusercontent.com/21211903/38111157-c299f548-3352-11e8-94f5-b86218cbff7c.gif)

**Comment by tnrich** [comment]
@mmatena is the sequence saving hooked up properly..? I'm not quite sure why this would be on HDE only. @XimeMora is it happening on lims/jbei as well?

**Comment by craftjk** [comment]
@tnrich we don't have the "General" tab for lims/jbei. I remember reporting this issue on JBEI-ICE but the tab was removed. Also I think hde may not be using the last version of ove.

**Comment by XimeMora** [comment]
Now that I involved Kyle in this one I will ask @craftjk do we still need that General tab?

**Comment by XimeMora** [comment]
This is working nicely now!

**Comment by AdamZMc** [comment]
Looks good!
