### ISSUE TITLE
Feature Properties "Action" buttons hidden in Firefox

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#283]
Reported by an ice user. See description below. The "New", "Edit", "Delete" button row is pushed out of view in firefox. This is not happening in chrome. Have not checked other browsers.

------user description------
Under vector editor, under properties, under features, the edit button isn't reachable in my Firefox browser. I have to go to "make tab full screen" to be able to see the button to click on it. "New" and "delete" are also not available except in full screen mode

**Comment by hplahar** [comment]
I couldn't test if this was happening on the latest version due to #284. We are currently using 2.0.3 in production for ICE

**Comment by tnrich** [comment]
I believe this has been fixed @hplahar . Closing
