### ISSUE TITLE
Browser Zoom in on map view messing everything up

### ISSUE THREAD

**Issue by mfero** [TeselaGen/openVectorEditor#285]
Try playing with browser zoom when looking at Open VE inside the HDE or LIMS. Things go bad quickly.  Zooming in on say, the map view only... magnifies a certain part of the map, but does not allow the user to move the map around like with window scroll bars. Either OVE or the implementation within another app needs a bit of work. No need to go into detailed descriptions of how to reproduce... it is very easy to mess up the view with just a bit of browser zoom manipulation. 

Also, ability to move tabs from one panel to the other is cute... but also messes up the interface. Why is that needed? Mess around with it for a while and it will get confused and you will loose all the tabs (see image below)

![image](https://user-images.githubusercontent.com/7561861/38206566-ba63f760-365f-11e8-8adc-1cff93b9a675.png)

![image](https://user-images.githubusercontent.com/7561861/38207115-88cf0206-3661-11e8-81a2-d0064e6a31ef.png)

**Comment by tnrich** [comment]
@mfero seems to look fine in LIMS: 

![image](https://user-images.githubusercontent.com/2730609/38207087-762753ce-3661-11e8-8349-f1bc725712f6.png)

![image](https://user-images.githubusercontent.com/2730609/38207096-7cd03d9e-3661-11e8-866d-803cd5141a48.png)

I would recommend that HDE folks update the editor to use the preview mode like in lims: 

```
<Editor
              previewMode
...etc />
```

**Comment by mfero** [comment]
Ok, Browser zoom just does not work well I guess... magnifies everything. I can get LIMS to look bad too. Can we disable in favor of in-app zooming? Also, dragging tabs works poorly... is it needed here?

**Comment by tnrich** [comment]
I don't think we should disable browser zoom. Let's triage and fix the necessary pieces of the app that look bad. I don't think it should be too hard to do, but clear screenshots of what looks bad on the various platforms will be necessary. 


What's the issue with dragging tabs (in OVE I assume?) that you're seeing? Is it zoom related? If it is a real issue let's make a new issue for it and discuss there.

Thanks for the feedback, keep it coming!

**Comment by mfero** [comment]
![image](https://user-images.githubusercontent.com/7561861/38218276-0b9733d8-3686-11e8-9453-ef4ab7abbaf3.png)

**Comment by mfero** [comment]
Hi Thomas! 
@tnrich maybe the focus should be to allow a zoom menu item for each panel that does not zoom external to the panel... HDE is doing something like this and it works well. In general OVE is lookin' pretty slick! Question for when we are embedding in HDE and LIMS... can we have a set of menu items like before? Those should be in the mother app to which OVE is the daughter right?

**Comment by tnrich** [comment]
Hey @mfero yeah I think either way should work fine. I would probably prefer baking a menu into OVE and exposing an interface so that lims/hde could modify it as necessary

**Comment by mfero** [comment]
Sounds good. Juan has started fleshing our Design editor menus, something similar for ove? Shall we loop him in?

**Comment by tnrich** [comment]
looped him in at https://github.com/TeselaGen/openVectorEditor/issues/148

**Comment by tnrich** [comment]
This seems to be working fairly well now: 
![image](https://user-images.githubusercontent.com/2730609/79166425-fd381200-7d99-11ea-8159-a2ba65509b25.png)
