### ISSUE TITLE
Get rid of cyan cut site representation

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#289]
From Mike's notes.

Get rid of cyan cut site representation in OVE... bad choice of color

**Comment by tnrich** [comment]
I'm not sure what this is referring to. Could you send a screenshot of this issue?

**Comment by tnrich** [comment]
@tgreen7 @mmatena this must be some custom css on hde or lims

**Comment by tnrich** [comment]
@mfero was this on hde or lims or both?

**Comment by XimeMora** [comment]
@tnrich I am seeing that cyan color only on hde. Lims cut site representations are black.
