### ISSUE TITLE
Make template sequence position fixed to top if alignment tracks overflow

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#291]
The alignment tracks should scroll below but the template sequence should be fixed on top

**Comment by XimeMora** [comment]
@tnrich does this have to work the same for when selecting "Create Pairwise Alignment" and when not? 

![screen shot 2018-04-25 at 7 28 02 pm](https://user-images.githubusercontent.com/21211903/39282592-d304378c-48be-11e8-9e54-2c7f7c900cb7.png)

This is how it is working now so the template sequence disappears when scrolling down:

![fixedtemplateseq](https://user-images.githubusercontent.com/21211903/39282699-68037654-48bf-11e8-93c3-f04dfaa44653.gif)

**Comment by tnrich** [comment]
@XimeMora this feature is only applicable if there is an explicit template (aka reference) sequence. For general Multi Sequence Alignments (MSAs) the top track should not be fixed.

**Comment by XimeMora** [comment]
It is working for the Pairwise Alignment so I'll pass this ticket.
