### ISSUE TITLE
Sequence match not highlighted on vector map

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#293]
When you search for a sequence on the sequence view, you get a red highlighted region. But this doesn't show up on the vector map, which is the default view. So you only see you have a match for your query if you look carefully at the little "1/1" next to your query.

**Comment by XimeMora** [comment]
Region is now highlighted on both Sequence and Plasmid views.

**Comment by AdamZMc** [comment]
Looks good!
