### ISSUE TITLE
Highlight/Caret should track with undo/redo

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#294]
Currently the highlight/caret doesn't change as undo/redo occurs, but it should!

**Comment by XimeMora** [comment]
@tnrich can you confirm if this is the behavior you are referring to?:

![highlight undo](https://user-images.githubusercontent.com/21211903/40468678-b57df4dc-5ef3-11e8-9a88-d5952f374d5f.gif)

If not, can you give an example?

**Comment by XimeMora** [comment]
Ok, so I'll move this ticket along 👍

**Comment by AdamZMc** [comment]
Looks good!
