### ISSUE TITLE
Rotate to position broken for certain features

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#296]
Details to come

**Comment by tnrich** [comment]
Okay, I figured out what the issue here is. We're allowing the sequence to be rotated, but the sequence is classified as a "linear" sequence. Thus when the rotation happens, the sequence data is cleaned and origin-spanning features are truncated. I think we have a few things we could do: 

 - 1. Make it more clear what the topology of the sequence is in the bottom status bar 
 - 2. Disable "rotate to" for linear sequences
 - 3. Allow "rotate to" for linear sequences but pop up a modal asking if they wish to change the sequence topology to circular
 - 4. Show the linear view by default and hide the plasmid view if the sequence is linear

I think we should do 1, 3 and 4

**Comment by gmcarthuriv** [comment]
@tnrich, would you mind attaching an example?

**Comment by tnrich** [comment]
[TEST2_000023.gb.zip](https://github.com/TeselaGen/openVectorEditor/files/1925770/TEST2_000023.gb.zip)

**Comment by hplahar** [comment]
My preference is for 1,2 and 4 with the understanding that I have to handle 4 when embedding.

**Comment by mfero** [comment]
1, 2, 4 would be my vote.

**Comment by tnrich** [comment]
Okay, 1 and 2 are in the latest OVE version. #4 will need to be implemented by the OVE consumer.

**Comment by XimeMora** [comment]
This is working nicely.

**Comment by AdamZMc** [comment]
Looks good!
