### ISSUE TITLE
Hover or highlight for bp pos in sequence

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#297]
Hover or highlight a nucleotide to see its base pair position in the sequence

**Comment by tnrich** [comment]
@tiffanydai highlighting a base pair already displays its position in the little status bar. Is the request supposed to be just for hovering?

**Comment by tnrich** [comment]
![image](https://user-images.githubusercontent.com/2730609/39266512-1097860c-487f-11e8-9610-18d1f31dabb8.png)

**Comment by XimeMora** [comment]
I see the bp position in the status bar at the bottom but not like a tooltip when hovering, @tiffanydai @tnrich should I see it in a tooltip too?

**Comment by XimeMora** [comment]
Not seeing the tooltip :(

**Comment by tnrich** [comment]
Hmm you have to hover for a little bit (it is a built in browser tooltip). I am looking on http://teselagen.github.io/openVectorEditor/ and see it now. Maybe check again?

**Comment by XimeMora** [comment]
I can see the tooltip now 👍

**Comment by AdamZMc** [comment]
Looks good.
