### ISSUE TITLE
Fullscreen a tab in OVE Dark Theme and the category buttons disappear

### ISSUE THREAD

**Issue by AdamZMc** [TeselaGen/openVectorEditor#299]
When using the Dark Theme, open OVE and fullscreen the Properties tab and see:

![ovenight](https://user-images.githubusercontent.com/36317055/39265977-91851452-487d-11e8-9977-3c62b71c1b10.gif)

**Comment by tnrich** [comment]
Closing as this has been fixed on OVE's demo page for a long time now: 

![image](https://user-images.githubusercontent.com/2730609/62503723-4a46fb80-b7aa-11e9-9ab0-29d757c0cd06.png)
