### ISSUE TITLE
Parts are being imported as Features

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#304]
When uploading a sequence that contains parts these are converted to features. This is happening on http://teselagen.github.io/openVectorEditor/ , LIMS and JBEI-ICE (HDE is importing the parts correctly).

This is the same sequence uploaded in each instance:

**HDE**

![screen shot 2018-04-25 at 10 44 22 pm](https://user-images.githubusercontent.com/21211903/39287799-3afe1450-48da-11e8-96ab-22cb096a4cdd.png)

**LIMS and Demo page**

![screen shot 2018-04-25 at 10 45 05 pm](https://user-images.githubusercontent.com/21211903/39287829-543dc578-48da-11e8-8413-6f4f40d7ac21.png)

**JBEI-ICE**

![screen shot 2018-04-25 at 10 45 55 pm](https://user-images.githubusercontent.com/21211903/39287859-72b369a4-48da-11e8-9b84-65b6fc51ba2f.png)

In this last one the "pS8c-vector_backbone" is being imported with errors, the length is different than the original. @tnrich should we just not import parts along with the sequence at all? I think JBEI doesn't need parts, right?

**Comment by tnrich** [comment]
@XimeMora can you revist this issue? I believe I have improved the part import workflow in our underlying parsers.. maybe it will just work as expected now? That is correct that jbei shouldn't know anything about parts. Ideally lims and hde should both auto-import "feature-parts" as parts.

**Comment by XimeMora** [comment]
@tnrich HDE and the stand alone OVE are handling parts correctly but LIMS is still displaying parts as features, maybe it is not updated @tgreen7 ?
As for jbei-ice parts are also displayed as features with the error mentioned above but I guess that is ok for now as they are not importing parts in their sequences?

**Comment by XimeMora** [comment]
I'll fail this one because LIMS is still importing parts as features.

**Comment by tnrich** [comment]
This one might be fixed when https://github.com/TeselaGen/lims/commit/9d6e6a0b26ad58d641b1530b895661d81f36748d makes it to dev.

**Comment by XimeMora** [comment]
LIMS is not importing parts, not even as features, is that what we want? @christopher-lamkin @tgreen7 

HDE
![screen shot 2018-07-30 at 9 10 16 pm](https://user-images.githubusercontent.com/21211903/43433515-4fd96272-943d-11e8-868f-faca6734c9ca.png)

LIMS
![screen shot 2018-07-30 at 9 10 34 pm](https://user-images.githubusercontent.com/21211903/43433516-53a274d4-943d-11e8-9037-00922f619583.png)

**Comment by tnrich** [comment]
@mfero @tgadam we want parts in LIMS, right?

**Comment by mfero** [comment]
@eabeliuk @thldev @tnrich, I guess this is tricky because the sequence and parts databases in DESIGN and BUILD are not unified or mirrored, and may not even follow the same schema? It seems like we can't solve the parts issue without a unified sequence/parts database? Should we ignore "parts" in LIMS for now? This is a good example of how the new architecture should be helpful. I don't see it happening on the time scale of this ticket. I would suggest interpreting them as features for now.

**Comment by thldev** [comment]
So the schemas actually should be mirrored albeit manually at the moment. We do have parts in LIMS though it appears they are not being used. It's also possible the data model has drifted out of sync.

**Comment by mfero** [comment]
@tnrich can you do some forensics and see what the status of the HDE vs LIMS schema looks like wrt sequences and parts?

**Comment by tnrich** [comment]
@mfero sure will do. I'll go ahead and try to get parts into LIMs.

**Comment by tnrich** [comment]
I believe parts have been added to lims. Can you verify @tgreen @tiffanydai ?

**Comment by XimeMora** [comment]
I see parts in lims' sequences now. Should we close this ticket then?

**Comment by tnrich** [comment]
Closing this as stale
