### ISSUE TITLE
Snap editor panes closed

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#306]
You should now be able to drag an editor pane to close it.

See the gif:

![untitled](https://user-images.githubusercontent.com/2730609/39329270-a51b0014-4952-11e8-80bf-116a9850966e.gif)

**Comment by AdamZMc** [comment]
Looks good.

**Comment by XimeMora** [comment]
Closing an editor pane by dragging it is working, but it is creating some issues with the scrolling, I'll create a new ticket for that.
