### ISSUE TITLE
Toolbar flashes when using it

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#307]
It's a bit hard to see in the gif, but when I click on the cutsites the Popover closes and re-opens really quickly:
![untitled](https://user-images.githubusercontent.com/2730609/39440149-da29e874-4c5e-11e8-99da-d89855523567.gif)

**Comment by XimeMora** [comment]
This has been fixed.

**Comment by AdamZMc** [comment]
This seems fixed to me. Moving along.
