### ISSUE TITLE
Scrolling broken in firefox for pairwise alignment

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#309]
When inspecting the track for a pairwise alignment, scrolling sideways in firefox doesn't work.

**Comment by XimeMora** [comment]
@tnrich @hplahar is this the scrolling that you are referring to?:

![scrolling](https://user-images.githubusercontent.com/21211903/40949595-a2bcb89a-6823-11e8-8bc6-a50844861097.gif)

**Comment by hplahar** [comment]
yes

**Comment by XimeMora** [comment]
The scrolling is working now, it is a little slow though.
