### ISSUE TITLE
Scrolling issue after closing editor panes by dragging

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#310]
After closing an editor pane by dragging it the scrollbar increases its length so the menu bar at the bottom goes very far down leaving a blank space and you have to scroll down to see it.

![dragpane](https://user-images.githubusercontent.com/21211903/39456672-1f0e23f4-4c9d-11e8-8597-8aaa9ff3bd67.gif)

**Comment by tnrich** [comment]
Dang, can't reproduce locally. Let's pair together in the SF office and solve this one.

**Comment by tnrich** [comment]
@XimeMora has this one been fixed already?

**Comment by XimeMora** [comment]
It seems fixed now 👍

**Comment by AdamZMc** [comment]
Looks good!
