### ISSUE TITLE
Fix alignment view firefox bugs

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#315]

**Comment by tnrich** [comment]
@XimeMora could you give the alignment view a one over on firefox and see if it works like it does in chrome? Thank you!

**Comment by XimeMora** [comment]
It seems to be working fine, but there are some scrollbars that are covering the view of some elements like the tab titles and the bottom of the alignment panel above the mini map.

![tab names](https://user-images.githubusercontent.com/21211903/40941295-41418ea2-67ff-11e8-8e63-4a56ea8b940c.PNG)






![scrollbars2](https://user-images.githubusercontent.com/21211903/40941306-4979deda-67ff-11e8-92da-3199b82e6358.PNG)

**Comment by tnrich** [comment]
Hmm yeah.. It would be nice to have those hidden but there isn't a simple
drop in solution to that. Maybe sometime down the line!

**Comment by tiffanydai** [comment]
hey @XimeMora, I just downloaded firefox, and I don't see the two scrollbars. maybe firefox updated their scrollbars? can you check it on your firefox browser to see if it's still there (and if it is still there, see if updating firefox changes anything)? 

![screen shot 2018-11-01 at 1 42 57 pm](https://user-images.githubusercontent.com/35508772/47879270-6a8df800-dddd-11e8-988e-e67f317e0419.png)

**Comment by tnrich** [comment]
I've experimented a fair amount now with hiding the scrollbars but haven't found a very satisfactory manner of doing so. I can hide the scrollbars via react but doing so adds a significant amount of jank to the page (that can be seen here: https://github.com/TeselaGen/openVectorEditor/tree/scroll2). I'm going to close this issue for now because it doesn't seem like it is important enough given the amount of effort needed to fix it.
