### ISSUE TITLE
Add info helpers to find tool explaining literal/ ambiguous

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#320]
![image](https://user-images.githubusercontent.com/2730609/40327878-422e8614-5cf9-11e8-89aa-95e6ab8f8f95.png)

**Comment by XimeMora** [comment]
Ambiguous substitutions info added 👍

**Comment by AdamZMc** [comment]
Info helper explaining Ambiguous substitutions has been added.
