### ISSUE TITLE
Alignments > Chromatogram data not rendering at certain zoom levels

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#322]
![screen shot 2018-05-21 at 1 49 25 pm](https://user-images.githubusercontent.com/35508772/40329299-f3b233dc-5cfd-11e8-82e1-4f2d22eef06c.png)
![screen shot 2018-05-21 at 1 49 43 pm](https://user-images.githubusercontent.com/35508772/40329304-f592f380-5cfd-11e8-917e-47e975f6b36c.png)

**Comment by tiffanydai** [comment]
Sample .ab1 files attached for QA (unzip before use). 

[GFPab1files.zip](https://github.com/TeselaGen/openVectorEditor/files/2171492/GFPab1files.zip)

**Comment by XimeMora** [comment]
This looks good!
