### ISSUE TITLE
Undoing after merging features is not bringing back the original unmerged features

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#324]
When using the option to merge features if I don't select Preserve features option and then click Undo the new merged feature disappears but the two original ones don't come back.

![undo merge feat](https://user-images.githubusercontent.com/21211903/40333565-0039d686-5d0e-11e8-92af-2e4d2505722b.gif)

**Comment by XimeMora** [comment]
This is now working correctly 👍

**Comment by AdamZMc** [comment]
Looks good!
