### ISSUE TITLE
Closing the Merge Features window does not close it but it moves the window upwards instead

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#325]
Clicking the "X" at the top right of the Merge Features window is moving the window upwards instead of closing it.

![merge feat x](https://user-images.githubusercontent.com/21211903/40333670-8bcee31c-5d0e-11e8-9ea9-aac3f2d2dec9.gif)

**Comment by XimeMora** [comment]
This issue is still happening.

**Comment by tnrich** [comment]
Hmm I'm not able to reproduce this. We'll maybe need to pair on this..?

**Comment by tnrich** [comment]
Hopefully we can get a fix from https://github.com/bokuweb/react-rnd/issues/209

**Comment by tnrich** [comment]
This should now be able to be fixed! https://github.com/bokuweb/react-rnd/issues/209#issuecomment-399761141

**Comment by tnrich** [comment]
This should now be able to be fixed! https://github.com/bokuweb/react-rnd/issues/209#issuecomment-399761141

**Comment by XimeMora** [comment]
This looks fixed, but I'm testing on a laptop now, I don't have a larger screen to test with and that's where I was seeing the issue, so I'm gonna pass this ticket for now.

**Comment by AdamZMc** [comment]
Looks good!
