### ISSUE TITLE
New features are not recognized when trying to select them to merge with another feature

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#326]
Using the Merge Features option on a newly created feature is not recognizing that feature when trying to select it from the plasmid or sequence map.

![merge new feat](https://user-images.githubusercontent.com/21211903/40333905-c463ac70-5d0f-11e8-80b2-938eaf5e4ac0.gif)

**Comment by XimeMora** [comment]
This looks good now!

**Comment by AdamZMc** [comment]
This issue has been resolved!
