### ISSUE TITLE
onSave callback not returning correct sequence end when spanning origin

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#327]
This appears to only occur when you edit a feature to span the origin.

To reproduce:
1. Create any arbitrary sequence (assume length is 20)
2. Create a feature that starts from position 15 to 20
3. Edit feature to have the end position span the origin (e.g end at position 5)
4. Click save to trigger the onSave callback.

The sequenceData object that is returned in the onSave function contains the features object with an end of 0.

**Comment by tnrich** [comment]
@hplahar is the sequence linear or circular?

**Comment by hplahar** [comment]
Ah, it was circular but I was setting that incorrectly in the sequence data for openVE so it thought it was linear. Issue resolved. Thanks!
