### ISSUE TITLE
Not able to fully delete sequence!

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#328]

**Comment by tnrich** [comment]
You should now be able to select and delete the whole sequence

**Comment by XimeMora** [comment]
@tnrich are you referring to delete the sequence from inside the vector editor, selecting all the base pairs in the sequence map and pressing the "delete" key?

**Comment by XimeMora** [comment]
Whole sequence can be deleted 👍

**Comment by AdamZMc** [comment]
Looks good!
