### ISSUE TITLE
Copy options are including features and parts when they are not selected

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#329]
When deselecting the right click options Copy > Copy Options > Include: Features, Partial Features, Parts, Partial Parts all partial and full features and parts are being copied.
![copy options](https://user-images.githubusercontent.com/21211903/40389573-a76021fe-5dc7-11e8-9410-e3d8ee633c82.gif)

**Comment by tnrich** [comment]
This should be ready to go now @XimeMora

**Comment by XimeMora** [comment]
@tnrich the issue mentioned before is fixed but selecting only Partial Features and/or Partial Parts is not working, although they work if Features and Parts options are selected too. Do full Features and Parts need to be selected in order for the partials to work?

![copy options](https://user-images.githubusercontent.com/21211903/40865532-8eace6e0-65ad-11e8-81bd-62e69b718b43.gif)

**Comment by tnrich** [comment]
Good catch Xime, I'll need to add in logic to make it clear that unchecking features also unchecks partial features (like in old ve)

**Comment by XimeMora** [comment]
Copy options are working nicely! 👍

**Comment by AdamZMc** [comment]
Looks good!
