### ISSUE TITLE
Select, then copy AA translation

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#331]
@tnrich, is this currently possible? If not, this would be very helpful - but maybe it's already a feature and I'm missing how to do this.

**Comment by gmcarthuriv** [comment]
@tnrich, I think the right-click menu is broken in LIMS. @christopher-lamkin, is LIMS using the latest openVE?

**Comment by tnrich** [comment]
@gmcarthuriv seems like it is working for me on limsdev: 

![image](https://user-images.githubusercontent.com/2730609/40736304-8723fbf0-63f2-11e8-851b-ff7819e2666e.png)


@christopher-lamkin or @tgreen7 can you confirm that this is working for you all?

**Comment by tnrich** [comment]
@siobhandavis hmm i can confirm https://lims-release-qa.herokuapp.com/dna-sequences/795#sequenceEditorFullscreen=true is not working. 

It appears to work on OVE standalone so as long as the latest version of OVE 7.1.2 makes it into the lims release branch then this functionality should work.

**Comment by siobhandavis** [comment]
I'll talk to chris and taoh about it. thanks!

**Comment by christopher-lamkin** [comment]
Updated QA Instructions:
1. Go to a sequence record view
2. Open up the Vector Editor
3. Highlight a portion of the DNA sequence underneath Sequence Map
4. Right click the highlighted portion, click copy, copy AA Sequence
5. Paste to make sure it saves to the clipboard
