### ISSUE TITLE
Make sure excessive red isn't shown on the sides of aligned regions

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#333]
Instead of: 
![image](https://user-images.githubusercontent.com/2730609/41262672-08ff6058-6d97-11e8-9109-43c78d77cbe1.png)

It should not show the red at the start and the end: 
![image](https://user-images.githubusercontent.com/2730609/41262683-172f3946-6d97-11e8-9d37-802832efcf6e.png)

**Comment by XimeMora** [comment]
Looks good.
