### ISSUE TITLE
Add Revision History to Vector Editor

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#334]
We need to implement versioning like in app.teselagen.com (Google style rollback)

![versioning](https://user-images.githubusercontent.com/21211903/41323106-762d76f4-6e61-11e8-8a68-dfeedf8d6557.PNG)

**Comment by tnrich** [comment]
@hplahar  and @craftjk Here's the api I'm thinking makes the most sense as a user of this version history: 

```js
// getSequenceAtVersion: (versionId) => teselagenSequenceData             
// getVersionList: () => [{ versionId: "51241", dateChanged: "12/30/1990", editedBy: "Hector Plahar", revisionType: "Feature Add"//can be left blank and will be excluded }]             
// (already provided unless using VersionHistoryView directly) onSave: (event, sequenceDataToSave, editorState, onSuccessCallback) => { //same onSave handler as normal// },                   
// (not necessary unless using VersionHistoryView directly) exitVersionHistoryView() => {}
// (not necessary unless using VersionHistoryView directly) getCurrentSequenceData: () => teselagenSequenceData  //called upon initialization      
    
```

Does that make sense to y'all and seem like a reasonable api?

**Comment by hplahar** [comment]
So if I understand this correctly, the embedding application (e.g. ICE) will be responsible for providing the implementation details of this to use version history?
As a first pass this sounds good. Might want to consider paging parameters (start/offset and limit) for getVersion().

**Comment by hplahar** [comment]
Ok, works for me. Is it up to the application to determine the revisionType?

**Comment by tnrich** [comment]
Yes, if that column is left blank it will not show up though.

**Comment by tnrich** [comment]
@hplahar and @craftjk 
I've published the VersionHistoryView. It can be accessed through the editor if desired (by adding the "versionHistoryTool" to the tool list). Or as a standalone module. It displays in full screen by default. 

![image](https://user-images.githubusercontent.com/2730609/43744786-951d822a-9990-11e8-8af7-b27881bc642b.png)


![image](https://user-images.githubusercontent.com/2730609/43744795-9c9d01e2-9990-11e8-83ee-350f9950d139.png)


The API is documented here: 
https://github.com/TeselaGen/openVectorEditor#versionhistoryview

Please let me know if you need any help getting it set up.

**Comment by XimeMora** [comment]
@tnrich @craftjk I don't see the View Version History option in HDE yet.

**Comment by tnrich** [comment]
@tgadam @craftjk in order for this to work we'll need to start tracking sequence versions on the hde backend. 

@XimeMora I think we should close this ticket because the OVE-related work for this has been finished. We should open a new ticket in HDE for tracking the sequence history on the backend.

**Comment by XimeMora** [comment]
@tnrich can we keep this ticket open and QA the revision history by itself here http://teselagen.github.io/openVectorEditor/#/VersionHistoryView ?
Also create that new ticket about tracking the sequence history on hde? We already have this one https://github.com/TeselaGen/hde/issues/1645 but is a general one.

**Comment by tnrich** [comment]
Sure you can do that. The version history at http://teselagen.github.io/openVectorEditor/#/VersionHistoryView is not connected to a real backend so it is somewhat contrived but still should demonstrate the tool.

**Comment by XimeMora** [comment]
Ok @tnrich I can take a look at that :)

**Comment by XimeMora** [comment]
The version history looks good on the vector editor by its own but we still need to test the functionality inside hde when it's ready, I'll pass this ticket for now.

**Comment by mfero** [comment]
@XimeMora @tnrich is this available in DESIGN now?

**Comment by tnrich** [comment]
@mfero no the backend has not been implemented in design yet

**Comment by mfero** [comment]
@tnrich Ok, Adam is oversubscribed so I guess this will wait.

**Comment by mfero** [comment]
This ticket was closed before the interface was implemented. I'll continue with a new ticket.
