### ISSUE TITLE
OVE --> Properties > Genbank > Make Genbank textbox wider

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#335]
_From @XimeMora on June 13, 2018 20:46_

### Describe what's going wrong/what needs to change.
Make Genbank textbox wider
### Steps to reproduce the behavior
OVE > Properties > Genbank
### Screenshots/gif of issue
![genbank](https://user-images.githubusercontent.com/21211903/41377096-e53a40aa-6f0f-11e8-8ce6-a559d1be9132.PNG)

_Copied from original issue: TeselaGen/hde#1656_

**Comment by XimeMora** [comment]
The textbox looks better now, but when resizing the window it is not adjusting properly, it sticks to the left side, @tnrich can we make it centered?

![genbank](https://user-images.githubusercontent.com/21211903/41561353-887de2a2-72fe-11e8-848f-15af34de429c.gif)

Also, is it possible to make the base pairs aligned like in the old ve?

![genbank aligned](https://user-images.githubusercontent.com/21211903/41561430-c8c52b5e-72fe-11e8-9187-d10b8e1382c4.PNG)

**Comment by tnrich** [comment]
This should be fixed now

**Comment by XimeMora** [comment]
This looks better now on http://teselagen.github.io/openVectorEditor/
HDE still needs to update it @craftjk

**Comment by AdamZMc** [comment]
Looks good.
