### ISSUE TITLE
Highlight remains when a different sequence is opened

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#336]
Select some base pairs in the sequence map or plasmid and then open a new sequence, you will see that the highlight remains rendered for the same number of base pairs that were selected in the previous sequence. 

![highlight](https://user-images.githubusercontent.com/21211903/41494449-f4ef8aa0-70c7-11e8-9aff-0f5261510382.gif)

**Comment by tnrich** [comment]
Okay this should be fixed in HDE

**Comment by XimeMora** [comment]
This has been fixed!

**Comment by AdamZMc** [comment]
Looks good!

**Comment by XimeMora** [comment]
This is a regression, the issue is happening again
