### ISSUE TITLE
Dialog windows - Change Submit button to Cancel and Save buttons

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#338]
Change Submit button to Cancel and Save buttons in the dialog windows as we have in Peony's vector editor. 

- [x] Create Feature
- [x] Create Part
- [x] Create Primer
- [x] Edit Feature
- [x] Edit Part

![no submit](https://user-images.githubusercontent.com/21211903/41627243-61f468aa-73d4-11e8-93d7-9db026e0b699.PNG)

![cancel-save](https://user-images.githubusercontent.com/21211903/41627247-6554d976-73d4-11e8-8dd4-089296e0fa9f.PNG)

**Comment by XimeMora** [comment]
Buttons have been changed but there is a couple of small issues with these options:

- In the "Add Feature" and "Edit Feature" dialogs the buttons are cut off.

![screen shot 2018-07-23 at 5 54 45 pm](https://user-images.githubusercontent.com/21211903/43107218-97d9ad30-8ea1-11e8-944b-70baced815e9.png)

- In the "Add Part" and "Add Primer" dialogs clicking Cancel button makes the _Required_ warning appear for the Name field.

![screen shot 2018-07-23 at 5 58 36 pm](https://user-images.githubusercontent.com/21211903/43107395-720a8a10-8ea2-11e8-8a2e-de6cb39fee7c.png)

**Comment by tnrich** [comment]
Good catches, these should both be fixed now

**Comment by XimeMora** [comment]
Looks good!

**Comment by AdamZMc** [comment]
Everything looks good! Moving along.
