### ISSUE TITLE
Adjust OVE to the full screen by default

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#339]
In HDE when opening the vector editor there's a blank space at the bottom, the editor should adjust to the full screen like it does for LIMS.

![blank space](https://user-images.githubusercontent.com/21211903/41630616-b5f712e4-73e4-11e8-82f7-83f5b729deba.PNG)

**Comment by mfero** [comment]
This issue was moved to TeselaGen/hde#1711
