### ISSUE TITLE
Editing the feature type is not changing the color in the plasmid view

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#341]
Changing the feature type through right-click > Edit Feature > select a different feature type is changing the color of the feature in the sequence map but not in the plasmid view.

![feature color](https://user-images.githubusercontent.com/21211903/42246135-527c872a-7ed0-11e8-9dab-853c0859f34d.gif)

**Comment by XimeMora** [comment]
@tnrich this is still happening.

**Comment by tnrich** [comment]
Fixed
