### ISSUE TITLE
Properties > Cutsites > Strand info is blank

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#343]
In the Properties tab > Cutsites selecting a cutsite shows the number of cuts, position and strand in a table but the strand column is empty, we should add "palindromic" as we have it in the main app:

![ove strand](https://user-images.githubusercontent.com/21211903/42248876-be3238b4-7edc-11e8-99d4-5459bd22ac72.PNG)

![palindromic](https://user-images.githubusercontent.com/21211903/42248871-b87a2ce2-7edc-11e8-8ec8-bd3e7623550e.PNG)

**Comment by tnrich** [comment]
Nice catch @XimeMora this should be fixed now

**Comment by XimeMora** [comment]
Looks good!

**Comment by AdamZMc** [comment]
Issue has been resolved!
