### ISSUE TITLE
Alignments > Dark mode's white font illegible

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#345]
![screen shot 2018-07-05 at 11 32 40 am](https://user-images.githubusercontent.com/35508772/42341333-980c8aec-8047-11e8-80bc-a26ede9095f7.png)

Font color of the text in nucleotides & name panel should be compatible with dark mode

**Comment by XimeMora** [comment]
Looks much better now! 👍

**Comment by AdamZMc** [comment]
Text is legible. Moving on.
