### ISSUE TITLE
Alignments > Sync scrolling vertically between alignment view/minimap

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#348]
Especially when the user has aligned many sequences, vertically scrolling through the alignment view should probably sync with the vertical scroll in the minimap, else it's easy to lose track of where you are/where the sequences should be

![screen shot 2018-07-05 at 6 16 50 pm](https://user-images.githubusercontent.com/35508772/42355020-9edbd58e-807f-11e8-93ce-ff7eca32e7fd.png)

**Comment by XimeMora** [comment]
Aligning many sequences is not working on hdedev and the standalone ove, it is only working on limsdev where I'm not sure that the issue mentioned in this ticket is working fine @tiffanydai can you take a look at this?:

![screen shot 2018-08-16 at 1 39 31 am](https://user-images.githubusercontent.com/21211903/44192532-69f69700-a0f5-11e8-903c-fc26507a358c.png)

**Comment by XimeMora** [comment]
Scrolling vertically in the minimap is showing with blue/yellow color the sequences displayed/not displayed in the alignment view 👍
