### ISSUE TITLE
Text in header tabs cut off in firefox

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#352]
When viewing OVE in firefox, the tops of the text in cut off. See attached screenshot
![screenshot from 2018-07-11 16-32-57](https://user-images.githubusercontent.com/1694026/42604547-2ee4736e-8528-11e8-83c3-08ebd0dd746f.png)

**Comment by hplahar** [comment]
Looks like the mac is the exception. Happens on linux and windows boxes.

**Comment by tnrich** [comment]
I'll need some help from a developer with access to a windows/linux computer @craftjk

**Comment by tnrich** [comment]
This should be fixed in open-vector-editor@10.1.45  @hplahar
