### ISSUE TITLE
Select Inverse doesn't work if selection starts at origin

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#353]
Not sure if this is a JBEI issue but while viewing sequence,  I selected from bp 1 to 77 and clicked on "Select Inverse". The highlighted selection disappeared and the text at the footer (next to Select Inverse)  reads "Selecting NaN bps from 78 to NaN".

**Comment by XimeMora** [comment]
This has been fixed!

**Comment by AdamZMc** [comment]
Looks good!
