### ISSUE TITLE
"Drop Fasta or Genbank files to view them in the editor" Window after creating a new Alignment

### ISSUE THREAD

**Issue by AdamZMc** [TeselaGen/openVectorEditor#362]
In the Dark Theme: DNA Materials > Alignment Tool > Create a new alignment > Adjust newly created alignment's zoom and a window containing the words "Drop Fasta or Genbank files to view them in the editor" pops up for an unknown reason in illegible text color.

![screen shot 2018-08-07 at 9 47 17 pm](https://user-images.githubusercontent.com/36317055/43816870-abb46cbe-9a8b-11e8-8129-bcb5b49202d4.png)

**Comment by tnrich** [comment]
This tool is being reworked and probably deprecated in favor of a newer version.
