### ISSUE TITLE
Part strand direction cannot be reversed

### ISSUE THREAD

**Issue by meisenstat** [TeselaGen/openVectorEditor#364]
When you click edit part, and change positive to negative, it automatically changes it back to positive.

![screencast 2018-08-10 13-59-31](https://user-images.githubusercontent.com/13423840/43981316-30ee69d6-9ca6-11e8-98ee-1c715cce4895.gif)

**Comment by meisenstat** [comment]
Similar to this, the notes aren't being saved when editing features from the properties page

**Comment by XimeMora** [comment]
This has been fixed.
