### ISSUE TITLE
Part Translation duplicates instead of recognizing it has already been called

### ISSUE THREAD

**Issue by meisenstat** [TeselaGen/openVectorEditor#365]
If you click on view translation for a part more than once, that translation shows up the amount of times you clicked it instead of a single time.

Right click part > View Translation. Then look at the sequence map

![image](https://user-images.githubusercontent.com/13423840/43981537-12c665c0-9ca7-11e8-968a-7cea61368646.png)

**Comment by meisenstat** [comment]
Similar, you are unable to delete translations in the properties tab.

**Comment by tnrich** [comment]
Okay the user should now be prompted if they're trying to make a translation that already exists:

![image](https://user-images.githubusercontent.com/2730609/44109514-1c9488c6-9fb2-11e8-92d9-26e2e7c210e0.png)

**Comment by tnrich** [comment]
The delete button is now disabled unless the translation type is `User Created`: 

![image](https://user-images.githubusercontent.com/2730609/44110953-fbc12b64-9fb5-11e8-9efc-4f70ab5e4f37.png)

**Comment by XimeMora** [comment]
This is working nicely.
