### ISSUE TITLE
Material Availability dropdown not pushing change

### ISSUE THREAD

**Issue by meisenstat** [TeselaGen/openVectorEditor#366]
When you change the availability of a material under properties and reload the page, the availability is reset to its original state.

![screencast 2018-08-10 14-48-11](https://user-images.githubusercontent.com/13423840/43982845-a081ae9c-9cac-11e8-977d-766d4e431af8.gif)

**Comment by tnrich** [comment]
@craftjk this is something that needs to be fixed on hde.

**Comment by tgadam** [comment]
we're going to be dropping support for this in Design. This value will be readonly and pulled from Build.
