### ISSUE TITLE
Add ability on sequences to "Create Parts from Type IIs Digest"

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#369]
From ticket https://github.com/TeselaGen/hde/issues/1860

Users should have the option to create parts based on a type IIs restriction enzyme digest. This option should be available by right clicking a single item in the sequence library and also from the vector editor > Properties > Parts > {new button at the bottom}. While we're at it make sure that the "Type" column is removed from the Parts table in VE (this is a separate but small issue. Features have Types, not Parts).

**Comment by tnrich** [comment]
Fixed by https://github.com/TeselaGen/hde/pull/2790

**Comment by tnrich** [comment]
Here are the tests in action: 
![new](https://user-images.githubusercontent.com/2730609/51493681-efe4d100-1d6a-11e9-9ac4-a1904f42a9c6.gif)

**Comment by siobhandavis** [comment]
@tnrich should I be able to do the type IIs digest part creation somewhere other than the library view? The ticket reads like I should be able to do this in the vector editor, but I don't see how.

**Comment by siobhandavis** [comment]
I saw that! I spun up the unique PR instance and passed the ticket. I made a new ticket, because the alignment of the checkboxes is funny, but the functionality is all there.

**Comment by tnrich** [comment]
It looks like it has the old version on  https://hde-release-qa.herokuapp.com/   @siobhandavis
