### ISSUE TITLE
OVE > Merging Features menu issues

### ISSUE THREAD

**Issue by AdamZMc** [TeselaGen/openVectorEditor#372]
- [ ] Cramped Feature dropdown layout.
- [ ] When merging features the menu notification is greyed out an therefore isn't clear to the user that a step is required.

![sequencemerging](https://user-images.githubusercontent.com/36317055/45015209-d28ab280-afd5-11e8-9c36-2a007f7bc9e8.gif)

**Comment by tnrich** [comment]
@AdamZMc what do you mean exactly by the 
>menu notification is greyed out
?

What is the menu notification?

Thanks!

**Comment by AdamZMc** [comment]
@tnrich Sorry about that. I was mainly pointing out that, as a user, I found the "Required" notification to be very subtle. I didn't initially notice the notification.
![screen shot 2018-10-21 at 11 26 04 pm](https://user-images.githubusercontent.com/36317055/47277760-c90ad900-d588-11e8-9fa9-ab4975005b91.png)

**Comment by tnrich** [comment]
@AdamZMc this should now be looking better and the error handling should look better too!

![image](https://user-images.githubusercontent.com/2730609/62082806-4e06db00-b20a-11e9-9a1f-aa3a0f8865b8.png)

**Comment by tnrich** [comment]
Closing until more issues are found ;)
