### ISSUE TITLE
Alignments Issue

### ISSUE THREAD

**Issue by AdamZMc** [TeselaGen/openVectorEditor#373]
Creating alignments seem to be stuck on the processing step. I created an alignment days ago and it is still processing. Because of this I am unable to test any Alignment Tool (Alignments) related tickets.
@tnrich
(The provided example is HDE but the same issue is with LIMS as well)
![malalignments](https://user-images.githubusercontent.com/36317055/45446882-e5ab1b80-b682-11e8-9b12-a3a8c347d878.gif)

**Comment by tnrich** [comment]
Closing as this issue is out of date now
