### ISSUE TITLE
Issues Editing Parts being used in designs

### ISSUE THREAD

**Issue by AdamZMc** [TeselaGen/openVectorEditor#374]
- [x] - Edit Part modal isn't centered.
- [ ] - Notes includes "[object Object]" by default.

![screen shot 2018-09-12 at 1 05 39 pm](https://user-images.githubusercontent.com/36317055/45450551-725ad700-b68d-11e8-884d-2f9207fd0ffb.png)

- [ ] - When adjusting increment buttons the modal texts will randomly get highlighted.
- [ ] - After saving the edited part, leaving OVE, then returning to the design's part, the edited part reverts.

![editingparts](https://user-images.githubusercontent.com/36317055/45450550-725ad700-b68d-11e8-9628-d1b6e81dc53d.gif)

**Comment by tnrich** [comment]
> - When adjusting increment buttons the modal texts will randomly get highlighted. 
working on a fix for this: https://github.com/palantir/blueprint/issues/3004

**Comment by tnrich** [comment]
Closing as the one remaining issue is being addressed in blueprint
