### ISSUE TITLE
Add Show Part Tags option in top menu

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#375]
We need to add an option to see part tags in the vector editor. We have that option in the old VE where the user can search for a particular part tag and the label of that part gets highlighted/in bold to identify it.  

![screen shot 2018-09-19 at 5 59 55 pm](https://user-images.githubusercontent.com/21211903/45786552-98a4e780-bc36-11e8-8c68-03755cf9398f.png)

**Comment by tnrich** [comment]
@deltuh-vee this could also be a good one for you to tackle if you're interested. We'd need to discuss more details but could be a fun one :)

**Comment by tnrich** [comment]
@deltuh-vee here's what the tag json should look like: 
```js 
const parts = [
  {
    name: "partWithTags",
    start: 10,
    end: 20,
    tags: [{ name: "status", description: "the status of the part", color: "blue", tagOptions: [
      {name: "ready", description: "this part is ready to use in a design", color: "green"},
      {name: "in progress", description: "this part is being worked on", color: "orange"},
      {name: "broken", description: "this part is broken", color: "orange"},
    ]}, { name: "tag2", description: "tag 2 description", color: "red"}],
  },
];
```

tags have name, color, and, description. But they can also have tagOptions, and tagOptions have name, color, and description

**Comment by tnrich** [comment]
And here's what tags look like in our app: 

![image](https://user-images.githubusercontent.com/2730609/88318211-41a74800-cccf-11ea-9c2d-67dd8291d053.png)

I think in OVE it will make sense to have tags appear in the Part Dropdown as a searchable list with tag options grouped on the same row. Paging won't be necessary. 

When a user clicks on a tag I think it should bold any parts that contain that tag?

**Comment by tnrich** [comment]
- [ ] set up a message if no parts have tags that there are no tagged parts to filter on.. 
- [ ] hook up partTagSelectValue and handlePartTagSelect in redux and connect to the part filter dropdown 
- [ ] actually hook up the logic to make the part label BOLD and highlight the part if that part is selected (based on partTagSelectValue)

**Comment by tnrich** [comment]
This has been implemented
