### ISSUE TITLE
Debug mode is enable in CircularViewUnconnected

### ISSUE THREAD

**Issue by weasteam** [TeselaGen/openVectorEditor#376]
When I am using `CircularViewUnconnected`, the code stopped at `if (!annotation.id) debugger;`

This stops the code from running. It might be good to remove the debug code in production.

**Comment by tnrich** [comment]
Hey @weasteam I'll make that check only occur when in development mode. It is important for annotations to have .id properties in order to track which annotation is highlighted, selected, etc..

**Comment by tnrich** [comment]
those debuggers are only in dev mode now: 
```
if (process.env.NODE_ENV !== "production" && !annotation.id) debugger;
```
