### ISSUE TITLE
LinearView does not working

### ISSUE THREAD

**Issue by weasteam** [TeselaGen/openVectorEditor#377]
the error is `could not calculate the length of undefined`, it happens in many places of `LinearView/index.js`

here is the fix:

at line 71
```
change 
sequenceData = _this$props$sequenceD === undefined ? {} : _this$props$sequenceD,
to 
sequenceData = _this$props$sequenceD === undefined ? {sequence:""} : _this$props$sequenceD,
```

at line 76
```
change 
sequenceData = _this$props$sequenceD2 === undefined ? {} : _this$props$sequenceD2;
to 
sequenceData = _this$props$sequenceD2 === undefined ? {sequence:""} : _this$props$sequenceD2;
```

at line 193
```
change
sequenceLength: sequenceData.sequence.length
to
sequenceLength: sequenceData.sequence ? sequenceData.sequence.length : 0
```

**Comment by tnrich** [comment]
@weasteam are you using the <LinearView/> or <LinearViewUnconnected/> ?

http://teselagen.github.io/openVectorEditor/#/LinearView

is an example of the <LinearView/> component and it seems to be working fine on that demo page and in our apps. You should generally pass a well-formed sequenceData object to any of the Linear/Circular/Row views.

That said, I'll go ahead and add the checks you're suggesting. 

Thanks!
