### ISSUE TITLE
Manually entering base pairs in Linear View offscreen

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/openVectorEditor#378]
If you create a new linear sequence and try to manually enter the base pairs, the editor appears off screen on the left side. 

If you switch to Plasmid view this works fine.

**Comment by tgadam** [comment]
![linear-editing-bug](https://user-images.githubusercontent.com/42746585/46496296-b1400080-c7e5-11e8-8ecc-a8042241ac5d.gif)

**Comment by tnrich** [comment]
Thanks @tgadam I should have a fix soon.

**Comment by tnrich** [comment]
@tgadam I'm not able to reproduce on https://hdedev.teselagen.com/ right now.

![tag](https://user-images.githubusercontent.com/2730609/46613708-8e328b00-cb1c-11e8-99e2-f64196163367.gif)

**Comment by tnrich** [comment]
hey QA people, can you see if you can still reproduce this? Thanks!

**Comment by XimeMora** [comment]
This is working fine for me.
