### ISSUE TITLE
Genbank joins are not handled correctly by VE

### ISSUE THREAD

**Issue by mfero** [TeselaGen/openVectorEditor#379]
@tnrich During the Novozymes tutorial in Copenhagen, NZ (Novozymes) noticed that...

Genbank joins are not handled correctly by VE. See file: SP_04_2060417.gb
See how Snapgene treats this sequence. They are interpreting the Genbank sequence correctly by showing dotted line between the features. Note also that we are not currently displaying feature labels, but that is in another ticket I think...

From TG after being parsed in and using Properties -> Genbank Viewer

LOCUS       SP_04_2060417_copy         125 bp    DNA     linear    09-OCT-2018
FEATURES             Location/Qualifiers
     source          1..125
                     /label="unspecified"
     sig_peptide     1..47
                     /label="SP_04_2060417"
     sig_peptide     116..125
                     /label="SP_04_2060417"
ORIGIN      
        1 atggcggtcc ttagcgtgct ccttcccatt accttccttc tctcgaggta agctcaccca
       61 tagatgctgc cctatagtgg atgccctaat ctaacagcgg ctgatcttca ttcagtgtta
      121 ccggc     
//

Original From Novozymes, (from .dna file from Snapgene)

LOCUS       SP_04_2060417                 125 bp ds-DNA     linear   UNA 13-JUN-2018
DEFINITION  natural linear DNA
ACCESSION   .
VERSION     .
KEYWORDS    .
SOURCE      natural DNA sequence
ORGANISM  unspecified
REFERENCE   1  (bases 1 to 125)
AUTHORS   Novozymes1
TITLE     Direct Submission
JOURNAL   Exported Jun 13, 2018 from SnapGene 4.1.2
            http://www.snapgene.com
FEATURES             Location/Qualifiers
     source          1..125
                     /organism="unspecified"
                     /mol_type="genomic DNA"
     sig_peptide     join(1..47,116..125)
                     /label=SP_04_2060417
ORIGIN
        1 atggcggtcc ttagcgtgct ccttcccatt accttccttc tctcgaggta agctcaccca
       61 tagatgctgc cctatagtgg atgccctaat ctaacagcgg ctgatcttca ttcagtgtta
      121 ccggc
//

**Comment by mfero** [comment]
![image](https://user-images.githubusercontent.com/7561861/46658566-4dd21c00-cbb3-11e8-8f3f-c08ca0988c77.png)

**Comment by tnrich** [comment]
@mfero how important are joined features to their workflow? It will definitely take a bit of work to get this feature.

**Comment by mfero** [comment]
We can move this to "normal" priority, but users do notice that this is missing.

We should work up a little gsheet feature comparison between Snapgene and VE to see where we need to add features that are not covered in other ways by  our platform.

**Comment by tnrich** [comment]
Hey Mike that sounds good. I'll drop the priority of this issue and start a feature comparison gsheet

**Comment by tnrich** [comment]
@mfero how does this visualization look to you: 

![image](https://user-images.githubusercontent.com/2730609/47686702-d2ec9780-db99-11e8-987a-59f66180d499.png)

The highlighted red annotation has multiple joined locations.

**Comment by tnrich** [comment]
And when highlighted:
![image](https://user-images.githubusercontent.com/2730609/47686859-979e9880-db9a-11e8-8c79-b7cae8e98676.png)

**Comment by tnrich** [comment]
I'm going to make it a little thinner: 
![image](https://user-images.githubusercontent.com/2730609/47737116-63c08300-dc2d-11e8-843e-a8c8b8ce5f80.png)

**Comment by tnrich** [comment]
Okay, added a similar visualization to the RowView: 
![image](https://user-images.githubusercontent.com/2730609/47754110-13f6b180-dc57-11e8-9eae-0b2a846e8a79.png)
and the LinearView: 
![image](https://user-images.githubusercontent.com/2730609/47754191-4d2f2180-dc57-11e8-8766-27079e4dd14e.png)

**Comment by tnrich** [comment]
A list of what is still left to do for this: 

- [ ] parse genbanks with joins into tg json, parse teselagen json with joins into genbank file with joins (and make that the default mode)
- [ ] update the lims/hde data models to support locations (json?) on features
- [ ] update OVE to allow for adding/deleting/expanding/shrinking locations within a feature
- [ ] display feature locations (if present) in the feature properties window

**Comment by tnrich** [comment]
Here is a first pass at the edit joined locations interface in OVE: 
![image](https://user-images.githubusercontent.com/2730609/47925754-27cf2d00-de7c-11e8-9d9f-32981ffa1107.png)

![image](https://user-images.githubusercontent.com/2730609/47925852-5c42e900-de7c-11e8-869a-1205fddf2c21.png)

![image](https://user-images.githubusercontent.com/2730609/47925884-6cf35f00-de7c-11e8-83a0-5902d511e089.png)

**Comment by tnrich** [comment]
Hey @hplahar I'm wondering if you'll want to support "joined feature locations" in ICE or if you'll want the new functionality disabled. You'd need to make sure your data model can handle this if you want to allow the functionality. You can see what it looks like here: 

http://teselagen.github.io/openVectorEditor/#/Editor

Let me know if you have any questions.

**Comment by XimeMora** [comment]
This is working nicely!
