### ISSUE TITLE
Switch import/export icons

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#381]
feedback from @hplahar: 

![screen shot 2018-10-22 at 2 52 00 pm](https://user-images.githubusercontent.com/35508772/47321667-56dad880-d60a-11e8-83c5-80443b582d27.png)
The down-arrow icon should be for exporting/downloading to the computer, and the up-arrow should be for importing into OVE

@tnrich

**Comment by tnrich** [comment]
Seems slightly arbitrary IMO but I'll switch them now.

**Comment by XimeMora** [comment]
Looks good!
