### ISSUE TITLE
Clicking on the edges of the import/export buttons

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#382]
feedback from @hplahar: 

![screen shot 2018-10-22 at 3 02 29 pm](https://user-images.githubusercontent.com/35508772/47322059-82aa8e00-d60b-11e8-94b4-de9051949931.png)
For the import and export buttons, only clicking in the center of the button triggers it. Clicking near the edges of the button doesn't work

@tnrich

**Comment by tnrich** [comment]
good catch

**Comment by XimeMora** [comment]
This has been fixed.
