### ISSUE TITLE
Scroll while selecting

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#384]
feedback from @hplahar: 

![screen shot 2018-10-22 at 3 14 52 pm](https://user-images.githubusercontent.com/35508772/47322573-4f68fe80-d60d-11e8-928d-34c3bbfa025f.png)
When the user is highlighting the sequence and reaches the end of what is shown in the window, the window should scroll to allow the user to continue expanding the selection (as the old Vector Editor does)

@tnrich

**Comment by tnrich** [comment]
Whoops this is related to recent changes I've made to fix issues with the sequenceInputBubble losing focus if opened right after highlighting/clicking in the sequence. I'll try to see if there is a workaround that fixes both cases.

**Comment by tnrich** [comment]
After thinking it over, it seems like the best thing to do is to just disable inserting sequence while a user drag is occurring. A user will now get this warning:

![image](https://user-images.githubusercontent.com/2730609/47367155-f98b6980-d693-11e8-976e-ee5bb527fe4a.png)

This has allowed me to revert the change that was breaking the scroll while selecting.

One slight downside is that it takes about 1 second to be sure that a user drag has ended so if they try to drag and then immediately insert they'll still get this message. However that seems like a very unusual use case unless someone is just messing around in the editor.

**Comment by XimeMora** [comment]
Scroll while selecting is working nicely.
