### ISSUE TITLE
'Type' box too short in 'Add Feature' dialog

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#385]
feedback from @hplahar: 

![img_2634](https://user-images.githubusercontent.com/35508772/47323356-42014380-d610-11e8-9fad-56f789c52565.jpg)
In JBEI, the 'Type' box is too short in the 'Add Feature' dialog, and the bottom buttons are a little cut off

![screen shot 2018-10-22 at 3 37 48 pm](https://user-images.githubusercontent.com/35508772/47323405-868cdf00-d610-11e8-85a2-3b06cc20bf6d.png)
That isn't happening in our app, but the dialog is a bit blurry in ours (edit: @tgreen7 and I looked into the blurriness, and it seems to happen when the transform/translate lands between pixels...seems to be a separate issue)

@tnrich

**Comment by tnrich** [comment]
This should already be fixed via @tgreen7 's css fix for inline labeled components. jbei will need to get a newer version of OVE with the fix in it.

**Comment by XimeMora** [comment]
This has been fixed! 👍
