### ISSUE TITLE
Sequence Alignment tool > settings should persist

### ISSUE THREAD

**Issue by tgreen7** [TeselaGen/openVectorEditor#387]
_From @gmcarthuriv on September 6, 2018 23:29_

@christopher-lamkin, @tiffanydai, @tnrich, @mfero,

As a user, I expect that my settings/preferences persist. For example, if I turn "DNA colors" **off** and the "features" **on** for one sequence alignment, I expect the next alignment to also have these settings. I also expect the zoom level to persist. Adjusting for each alignment takes a significant amount of time.

![image](https://user-images.githubusercontent.com/17152701/45190211-a21f6000-b1f1-11e8-9715-1819456ba5d4.png)

----

![image](https://user-images.githubusercontent.com/17152701/45190273-004c4300-b1f2-11e8-9379-27b9e775057a.png)

_Copied from original issue: TeselaGen/lims#1261_

**Comment by tgreen7** [comment]
_From @tnrich on September 13, 2018 18:51_

Working on this now. There are a few things to note -- I am planning on saving these settings to localstorage by default. That will make them persist across browser sessions. I think persisting this to a DB would be overkill and more work than its worth. 

Also, because pairwise alignments and MSA style alignments are so different I won't be sharing their default view settings. 

Does that sound okay to you @gmcarthuriv ?

**Comment by tgreen7** [comment]
_From @tnrich on September 17, 2018 22:48_

Once alignments are working again on limsdev this can be tested

**Comment by tgreen7** [comment]
_From @XimeMora on September 19, 2018 21:56_

@tnrich @tgreen7 I guess alignments are still not fully working on limsdev? I get a blank page trying to create a pairwise alignment, or is this another bug?

**Comment by tgreen7** [comment]
_From @XimeMora on September 25, 2018 1:14_

Alignments are still not properly working, @tnrich are you still working on that or these are new bugs?:

![alignment](https://user-images.githubusercontent.com/21211903/45987275-2f5a1580-c036-11e8-9f69-f3060ee7f203.gif)

![screen shot 2018-09-24 at 7 54 25 pm](https://user-images.githubusercontent.com/21211903/45987320-5ca6c380-c036-11e8-9f41-1b02c350f574.png)

**Comment by tnrich** [comment]
@tiffanydai let's pair on this issue?

**Comment by tnrich** [comment]
Closing this as it is now outdated
