### ISSUE TITLE
Position Menu and Menu shortcuts on separate lines

### ISSUE THREAD

**Issue by mfero** [TeselaGen/openVectorEditor#393]
Position menus and toolbars as in "old app". Please include "last edit" string in preparation for re-implementation of google docs style roll back feature.

**OLD VE**
![image](https://user-images.githubusercontent.com/7561861/46802141-d3dd9680-cd5c-11e8-88be-f7afc2250610.png)

**NEW VE**
![image](https://user-images.githubusercontent.com/7561861/46802084-a264cb00-cd5c-11e8-8092-ff3326a4246e.png)

**Comment by XimeMora** [comment]
Menus are on separate lines now.
