### ISSUE TITLE
VE > Sequence Map panel > GenBank label improvements

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#410]
_From @gmcarthuriv on August 28, 2018 20:13_

@tnrich, @christopher-lamkin, @craftjk, @mfero,

- space between feature "arrow" and the ring (see the red arrow in the first image below)
- **OR** place the feature "arrow" on the ring (an example of this is given in the second screenshot below - from Genome Compiler)

![image](https://user-images.githubusercontent.com/17152701/44748096-bcf02700-aac3-11e8-97e0-a2513fc28a67.png)

----

![image](https://user-images.githubusercontent.com/17152701/44748223-148e9280-aac4-11e8-8016-7428443af527.png)

_Copied from original issue: TeselaGen/hde#2547_

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on August 28, 2018 20:23_

From old VE (in Peony):

![image](https://user-images.githubusercontent.com/17152701/44748821-9501c300-aac5-11e8-8cb5-a377427bc569.png)

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 23:43_

It will now have a bit more room between features and the axis (when the axis has no tick numbers showing): 
![image](https://user-images.githubusercontent.com/2730609/44885004-6fb2b780-ac73-11e8-98a2-6746e9b8263c.png)

Also made the axis thickness slightly smaller

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on November 21, 2018 2:5_

@tnrich, @tiffanydai, @craftjk, @christopher-lamkin, @mfero,

IMO, the text/font size should also be severely reduced. It's a bit intense now.

![image](https://user-images.githubusercontent.com/17152701/48814172-a2a69d80-ecee-11e8-991f-0616a653a872.png)

**Comment by tnrich** [comment]
I believe this has been fixed 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/2730609/170152310-f637c040-bdf0-400d-8e92-c07f97b02b92.png">
