### ISSUE TITLE
VE > Sequence Map panel > ring/line made black or white (depending on mode/theme)

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#411]
_From @gmcarthuriv on August 28, 2018 20:15_

@tnrich, @christopher-lamkin, @craftjk, @mfero,

No mo' yella.

- white ring/line in dark mode/theme
- black ring/line in light mode/theme

![image](https://user-images.githubusercontent.com/17152701/44748287-43a50400-aac4-11e8-8601-73ac6829f5d4.png)

_Copied from original issue: TeselaGen/hde#2546_

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 23:52_

I guess this is just personal preference but I don't think the black ring looks very good: 

![image](https://user-images.githubusercontent.com/2730609/44885328-0df34d00-ac75-11e8-95c7-d5d622266211.png)

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 23:53_

@mfero @gmcarthuriv  thoughts?

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on August 30, 2018 23:53_

How about dark grey?

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 23:54_

versus: 
![image](https://user-images.githubusercontent.com/2730609/44885350-4bf07100-ac75-11e8-842f-a4e1d62d6f7e.png)

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on August 30, 2018 23:54_

Or black outlines with a white middle?

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 23:55_

![image](https://user-images.githubusercontent.com/2730609/44885384-76422e80-ac75-11e8-8025-8ecd9f56dba1.png)

![image](https://user-images.githubusercontent.com/2730609/44885405-88bc6800-ac75-11e8-9b3e-8767b185c335.png)

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 23:56_

I like the white fine :)

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on August 30, 2018 23:57_

The white with black outlines looks pretty good, @tnrich!

The reason I suggested black is because it works fairly well in the old VE (Peony):

![image](https://user-images.githubusercontent.com/17152701/44885437-af7a9e80-ac75-11e8-931d-98dea8cab1ef.png)

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 23:58_

I like white :)

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 23:59_

![image](https://user-images.githubusercontent.com/2730609/44885502-0aac9100-ac76-11e8-8fc2-e92d7b4628ea.png)

**Comment by XimeMora** [comment]
Looks good!
