### ISSUE TITLE
VE > Sequence panel > GenBank features are too fat > eschew labels

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#412]
_From @gmcarthuriv on August 28, 2018 20:27_

New vs. old:

![image](https://user-images.githubusercontent.com/17152701/44748901-d1cdba00-aac5-11e8-991a-e304f7f399fc.png)

_Copied from original issue: TeselaGen/hde#2545_

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on August 28, 2018 20:29_

@tnrich, @christopher-lamkin, @craftjk, @mfero

**Comment by siobhandavis** [comment]
_From @tiffanydai on August 28, 2018 21:48_

Labels available on hover

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 22:1_

@tiffanydai can you paste in a screenshot please ?

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on September 4, 2018 8:0_

@tnrich, @tiffanydai - happy to discuss for clarity, if you'd like.

**Comment by tnrich** [comment]
Closing as this is old
