### ISSUE TITLE
VE > Parts display > smart scaling

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#413]
_From @gmcarthuriv on August 28, 2018 20:58_

@tnrich, @christopher-lamkin, @craftjk, @mfero

Parts displayed should be improved with better scaling.

**OLD VE**
![image](https://user-images.githubusercontent.com/17152701/44750452-430f6c00-aaca-11e8-904c-d8a82cba0ab2.png)

**NEW VE**
![image](https://user-images.githubusercontent.com/17152701/44750469-50c4f180-aaca-11e8-9443-c4d60445763a.png)

_Copied from original issue: TeselaGen/hde#2544_

**Comment by siobhandavis** [comment]
_From @tnrich on October 21, 2018 21:51_

@gmcarthuriv I know we talked about this a little already. Can you explain again clearly what you want exactly for this one? Is it that the width of the parts gets smaller for every part that is added (down to some threshold like 2px or something?)? Thanks!

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on October 21, 2018 22:57_

@tnrich, I think there are a couple mechanisms that would help.

My current thinking is that only some of the Parts would show up in a single view and that the user could somehow scroll through the Parts layer if there are more Parts than can be displayed at once. In addition, I think your suggestion of changing the relative size of the Parts as more are added is a good one. My original idea was to have the number of displayed Parts vary according to the size of the plasmid map (the smaller the map, the more Parts could be displayed based on the available space) - "smart" scaling.

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on October 21, 2018 22:58_

@tnrich, I think there are a couple mechanisms that would help.

My current thinking is that only some of the Parts would show up in a single view and that the user could somehow scroll through the Parts layer if there are more Parts than can be displayed at once. In addition, I think your suggestion of changing the relative size of the Parts as more are added is a good one. My original idea was to have the number of displayed Parts vary according to the size of the plasmid map (the smaller the map, the more Parts could be displayed based on the available space) - "smart" scaling.

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on October 21, 2018 23:0_

@tnrich, I think there are a couple mechanisms that would help.

My current thinking is that only some of the Parts would show up in a single view and that the user could somehow scroll through the Parts layer if there are more Parts than can be displayed at once. In addition, I think your suggestion of changing the relative size of the Parts as more are added is a good one. My original idea was to have the number of displayed Parts vary according to the size of the plasmid map (the smaller the map, the more Parts could be displayed based on the available space) - "smart" scaling.

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on October 21, 2018 23:0_

@tnrich, I think there are a couple mechanisms that would help.

My current thinking is that only some of the Parts would show up in a single view and that the user could somehow scroll through the Parts layer if there are more Parts than can be displayed at once. In addition, I think your suggestion of changing the relative size of the Parts as more are added is a good one. My original idea was to have the number of displayed Parts vary according to the size of the plasmid map (the smaller the map, the more Parts could be displayed based on the available space) - "smart" scaling.

**Comment by tnrich** [comment]
Closing this as stale
