### ISSUE TITLE
OVE > Sequence map not showing the cut sites

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#414]
_From @XimeMora on October 17, 2018 18:47_

### Describe what's going wrong/what needs to change.
In the Vector Editor the Sequence map is not showing the cut sites the second time that the user selects the option to see them.

_Copied from original issue: TeselaGen/hde#2543_

**Comment by tnrich** [comment]
Can you please provide a video reproducing this issue @XimeMora

**Comment by XimeMora** [comment]
It seems to be working now. Closing the ticket.
