### ISSUE TITLE
Genbank joins are not handled correctly by VE

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#416]
_From @XimeMora on October 17, 2018 2:0_

### Describe what's going wrong/what needs to change.
Genbank joins are not handled correctly by VE:

See file: SP_04_2060417.gb
Note, see how Snapgene treats this sequence. They are interpreting the Genbank sequence correctly.

****** From TG after being parsed in and using Properties -> Genbank Viewer ******

LOCUS       SP_04_2060417_copy         125 bp    DNA     linear    09-OCT-2018
FEATURES             Location/Qualifiers
     source          1..125
                     /label="unspecified"
     sig_peptide     1..47
                     /label="SP_04_2060417"
     sig_peptide     116..125
                     /label="SP_04_2060417"
ORIGIN      
        1 atggcggtcc ttagcgtgct ccttcccatt accttccttc tctcgaggta agctcaccca
       61 tagatgctgc cctatagtgg atgccctaat ctaacagcgg ctgatcttca ttcagtgtta
      121 ccggc     

****** Original From Novozymes, (from .dna file from Snapgene) *******

LOCUS       SP_04_2060417                 125 bp ds-DNA     linear   UNA 13-JUN-2018
DEFINITION  natural linear DNA
ACCESSION   .
VERSION     .
KEYWORDS    .
SOURCE      natural DNA sequence
ORGANISM  unspecified
REFERENCE   1  (bases 1 to 125)
AUTHORS   Novozymes1
TITLE     Direct Submission
JOURNAL   Exported Jun 13, 2018 from SnapGene 4.1.2
            http://www.snapgene.com
FEATURES             Location/Qualifiers
     source          1..125
                     /organism="unspecified"
                     /mol_type="genomic DNA"
     sig_peptide     join(1..47,116..125)
                     /label=SP_04_2060417
ORIGIN
        1 atggcggtcc ttagcgtgct ccttcccatt accttccttc tctcgaggta agctcaccca
       61 tagatgctgc cctatagtgg atgccctaat ctaacagcgg ctgatcttca ttcagtgtta
      121 ccggc

----------------------------------------------------------------------------
SP_06_3146816 copy      54                              null    [object Object] 2018-10-09T08:25:53.919Z        2018-10-09T08:25:53.919Z
SP_07_3149386 copy      75                              null    [object Object] 2018-10-09T08:25:53.919Z        2018-10-09T08:25:53.919Z
GOI-Anig_glucoamylase copy      1920                            null    [object Object] 2018-10-09T08:25:53.919Z        2018-10-09T08:25:53.919Z

_Copied from original issue: TeselaGen/hde#2541_

**Comment by XimeMora** [comment]
Duplicate #379
