### ISSUE TITLE
OVE > Enzyme manager broken

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#417]
_From @XimeMora on October 17, 2018 1:51_

### Describe what's going wrong/what needs to change.
Enzyme manager in VE broken! No way to see current enzymes. Adding enzymes I know cuts… does not show cuts n times message (says cuts 0 times)… able to add same enzyme more the once etc...

### Screenshots/gif of issue
![screen shot 2018-10-16 at 6 48 57 pm](https://user-images.githubusercontent.com/21211903/47057113-3c20e380-d174-11e8-9f77-308fa3db7046.png)

![screen shot 2018-10-16 at 6 48 41 pm](https://user-images.githubusercontent.com/21211903/47057103-30cdb800-d174-11e8-9b79-1f3464009fd5.png)

_Copied from original issue: TeselaGen/hde#2540_

**Comment by tnrich** [comment]
@XimeMora can you revisit this and make an issue or a checkbox for each thing that is broken with the enzyme manager. Thank you!

**Comment by XimeMora** [comment]
@tnrich I think I copy-pasted the issue from someone else so I don't understand exactly what was the issue(s). I can test the Restriction Enzymes Manager as part of the regression testing and see if it is working fine, but as far as I remember it was working. I think we can close this ticket.

**Comment by tnrich** [comment]
Okay thanks. Can you close this one if it all checks out?
