### ISSUE TITLE
OVE > Multi-select broken

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#418]
_From @XimeMora on October 17, 2018 1:27_

### Describe what's going wrong/what needs to change.
In Vector Editor Ctr + click to highlight different parts in the sequence (Shift click selection) is broken.

_Copied from original issue: TeselaGen/hde#2539_

**Comment by tnrich** [comment]
@XimeMora is this a feature that has been requested by customers?

**Comment by tnrich** [comment]
I don't believe this worked in the old app

**Comment by XimeMora** [comment]
This is what I'm referring to:

![shift-click](https://user-images.githubusercontent.com/21211903/49972738-33d8f080-fef8-11e8-9ae8-a2ddb28c7b2e.gif)

I'm checking on hde and it kind of works sometimes, it seems buggy:

![shift-click bad](https://user-images.githubusercontent.com/21211903/49972855-8dd9b600-fef8-11e8-8951-0b52fae09320.gif)

**Comment by tnrich** [comment]
this can be QA'd here in a few minutes: http://teselagen.github.io/openVectorEditor/#/Editor

**Comment by XimeMora** [comment]
Looks good!
