### ISSUE TITLE
OVE > Sequence Map > Hide/Show cut sites issue

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#420]
_From @AdamZMc on September 13, 2018 21:41_

### Describe what's going wrong/what needs to change.
In the Sequence Map the Hide/Show cut sites option hides/shows the recognition site boxes while most of the cut sites remain visible. 
### Screenshots/gif of issue
![cutrecognize](https://user-images.githubusercontent.com/36317055/45517342-b2d85480-b762-11e8-97fe-e5b7db50328f.gif)

_Copied from original issue: TeselaGen/hde#2537_

**Comment by tnrich** [comment]
Got it! Good catch @AdamZMc

**Comment by XimeMora** [comment]
This is still happening on hde.

**Comment by tnrich** [comment]
This will be fixed once hde updates to latest OVE

**Comment by XimeMora** [comment]
This has been fixed!
