### ISSUE TITLE
OVE: Show/Hide Features

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#423]
_From @lutan07 on November 16, 2018 22:8_

### Describe what's going wrong/what needs to change.

tooltip always show "hide feature"

### Screenshots/gif of issue

![untitled](https://user-images.githubusercontent.com/45047136/48649932-2556f200-e9a9-11e8-9802-254777f7e23a.gif)

_Copied from original issue: TeselaGen/hde#2478_

**Comment by tnrich** [comment]
This should be fixed now

**Comment by XimeMora** [comment]
Fixed!
