### ISSUE TITLE
OVE > Add zoom in/out option to the tool bar

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#424]
_From @XimeMora on September 5, 2018 5:21_

### Describe what's going wrong/what needs to change.
From Elliot: Add independent zoom to vector editor.
### Steps to reproduce the behavior
We had this in the old vector editor
### Screenshots/gif of issue
![screen shot 2018-09-05 at 12 16 31 am](https://user-images.githubusercontent.com/21211903/45072625-6f665200-b0a1-11e8-896f-1a2c6a22f15d.png)

_Copied from original issue: TeselaGen/hde#2162_

**Comment by siobhandavis** [comment]
_From @craftjk on September 6, 2018 0:23_

@tnrich this is requested by Dow, do you think we can add this functionality soon?

**Comment by siobhandavis** [comment]
_From @tnrich on September 6, 2018 17:13_

@craftjk I haven't made this a priority but I'm sure it could be implemented if I did so. It seems like there might still be more critical issues to work on.

**Comment by siobhandavis** [comment]
_From @tnrich on September 6, 2018 18:37_

@craftjk zooming v1 has already been implemented for linear view if you want me to hook up a little zoom bar for the linear view. It was built to support zooming in the alignment view.

**Comment by siobhandavis** [comment]
_From @XimeMora on October 23, 2018 19:45_

There's still no zoom option in the vector editor.

**Comment by tnrich** [comment]
Closing in favor of more recent zoom tickets
