### ISSUE TITLE
VE > Properties > GenBank > text is not legible in dark mode/theme

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#425]
_From @gmcarthuriv on August 28, 2018 21:5_

@tnrich, @christopher-lamkin, @craftjk, @mfero

![image](https://user-images.githubusercontent.com/17152701/44750827-57a03400-aacb-11e8-9643-9a33d6012c86.png)

_Copied from original issue: TeselaGen/hde#2128_

**Comment by siobhandavis** [comment]
_From @tnrich on August 30, 2018 22:28_

ready once teselagen-react-components is updated to v24.0.2 or beyond :)

**Comment by XimeMora** [comment]
Looks good!
