### ISSUE TITLE
Autosave in OVE seems not to be saving fast enough or not registering some actions

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#427]
_From @XimeMora on August 22, 2018 4:29_

### Describe what's going wrong/what needs to change.
I'm deleting base pairs in the sequence map and a toastr message tells me "Sequence deleted successfully" but if I go to the sequence library and then open the same sequence again some of the base pairs that I deleted are still present.

### Screenshots/gif of issue
![autosave](https://user-images.githubusercontent.com/21211903/44442769-a87ace80-a599-11e8-9c24-6ae85cd79351.gif)

_Copied from original issue: TeselaGen/hde#2088_

**Comment by XimeMora** [comment]
@tnrich it seems that this is still saving very slowly so when I go back to the library and come back to the vector editor some of the base pairs that I deleted are still there.
