### ISSUE TITLE
VE > Edit Part - "Notes" field is not being saved

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#428]
_From @XimeMora on February 15, 2018 22:35_

### Describe what's going wrong/what needs to change.
In the Add/Edit Part window there is a field for Notes, this seems to be saved after clicking Submit button but after saving the sequence, closing VE and going back to that part the Notes field shows "[object Object]" instead.
### Steps to reproduce the behavior
Open a sequence in VE > Create or Edit an existing part adding text in the Notes field > click Submit > click Save button from the menu bar > go to the Parts library > open that part in VE > right-click Edit Part
### Screenshots/gif of issue
![screen shot 2018-02-15 at 2 21 12 pm](https://user-images.githubusercontent.com/21211903/36284536-d12eda9a-125c-11e8-8ec1-75e0b6df8bea.png)

_Copied from original issue: TeselaGen/hde#748_

**Comment by siobhandavis** [comment]
_From @mmatena on March 11, 2018 18:17_

In Peony, the notes are stored as key-value pairs (that allow for duplicate keys) while open-vector-editor appears to treat them as simple strings. The parsers treat the notes as key-values pairs.

**Comment by tnrich** [comment]
I believe this has been fixed!
