### ISSUE TITLE
VE: Opening a Part is not scrolling to the highlight in the Sequence Map

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#429]
_From @XimeMora on January 19, 2018 1:32_

### Describe what's going wrong/what needs to change.
From the Part library opening a part is highlighting it in the plasmid view but it is not scrolling to the highlighted part in the Sequence view.
### Steps to reproduce the behavior
DNA Parts library > double-click a part 
### Screenshots/gif of issue
![sequence map highlight](https://user-images.githubusercontent.com/21211903/35130376-1a2a86a0-fc86-11e7-93dc-5ce6dbf4cc17.gif)

_Copied from original issue: TeselaGen/hde#589_

**Comment by siobhandavis** [comment]
_From @XimeMora on July 6, 2018 2:30_

Ticket on OVE https://github.com/TeselaGen/openVectorEditor/issues/251

**Comment by tnrich** [comment]
closing as  #251 covers this
