### ISSUE TITLE
Sequence Editor > Create Part from sequence selected via "cmd + i" not working

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#431]
_From @gmcarthuriv on November 25, 2018 4:16_

@craftjk, @tiffanydai, @tnrich, @mfero,

- Select a sequence region that goes to 3' end of DNA Sequence
- Select inverse sequence via "cmd + i"
- Create new Part via right-click and select "Create > New Part"
- You will see that the Part doesn't begin at basepair 1 (it begins with the final basepair of the Sequence)

![image](https://user-images.githubusercontent.com/17152701/48975430-78bde580-f024-11e8-89fe-4524e8989f03.png)

_Copied from original issue: TeselaGen/hde#2517_

**Comment by siobhandavis** [comment]
_From @tnrich on November 25, 2018 18:35_

@gmcarthuriv I can't reproduce. Are the steps I'm doing correct? 

![tag](https://user-images.githubusercontent.com/2730609/48982957-d3dfee80-f09d-11e8-901d-360ee38f6bc3.gif)

Thanks

**Comment by siobhandavis** [comment]
_From @tnrich on November 25, 2018 18:36_

Here's a useful screen recording tool in case you want to take a gif of it https://download.cnet.com/LICEcap/3000-2094_4-75984664.html

**Comment by siobhandavis** [comment]
_From @gmcarthuriv on November 27, 2018 8:20_

@tnrich, try it in HDE - different behavior than the standalone openVE. I can confirm that it works as expected in openVE.

**Comment by siobhandavis** [comment]
_From @tnrich on November 27, 2018 21:10_

@gmcarthuriv I've spotted what the issue is there. It appears that your sequence is in "Linear" mode. I wonder why it would be doing that in linear mode..

**Comment by siobhandavis** [comment]
_From @mfero on November 30, 2018 0:6_

@siobhandavis can you move this ticket to OVE?

**Comment by tnrich** [comment]
Closing this in favor of #437 which should solve this issue.
