### ISSUE TITLE
Export sequence option not working from icon in top menu

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#432]
@tnrich Export sequence option is not working from icon in top menu

![screen shot 2018-12-01 at 1 25 53 am](https://user-images.githubusercontent.com/21211903/49325454-3d318880-f508-11e8-9b26-c58a87b5a322.png)

Error in console:

![screen shot 2018-12-01 at 1 25 33 am](https://user-images.githubusercontent.com/21211903/49325457-402c7900-f508-11e8-85ce-f302e3ffdece.png)

**Comment by tnrich** [comment]
Good catch thanks ximena. I'm on it

**Comment by XimeMora** [comment]
@tnrich in HDE

**Comment by tnrich** [comment]
@XimeMora test again?

**Comment by XimeMora** [comment]
It is working now 👍
