### ISSUE TITLE
Find Tool > Highlight All gets deselected when closing modal

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#433]
@tnrich The option to Highlight All when using the Find tool gets deselected when closing the modal, that selection should persist, because the DNA and Amino Acids stayed highlighted so when opening that modal and selecting Highlight All again it does the opposite.

![find](https://user-images.githubusercontent.com/21211903/49416049-46a43600-f73e-11e8-8748-859fc9c853b3.gif)

**Comment by tnrich** [comment]
Fixed this and have set up an e2e test for it in OVE.

**Comment by XimeMora** [comment]
I tested on hdedev-qa and it doesn't look fixed there.
