### ISSUE TITLE
Properties > Translations > Delete button disabled

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#435]
@tnrich 
In the Properties > Translations > the Delete button is greyed out.

**Comment by tnrich** [comment]
Certain translations cannot be deleted

**Comment by XimeMora** [comment]
@tnrich which ones can and which ones can't be deleted?

**Comment by tnrich** [comment]
Ones that are of type "cds feature" and "ORF" are cannot be deleted. 

"User created" translations can be

**Comment by tnrich** [comment]
![image](https://user-images.githubusercontent.com/2730609/49818770-70ee8880-fd28-11e8-9061-a82a01b948a6.png)

I've added that to make it clearer

**Comment by XimeMora** [comment]
Looks good!
