### ISSUE TITLE
When in Full Screen > Minimize Tab tooltip shows up on the opposite side of the actual button

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#436]
@tnrich
When in Full Screen > Minimize Tab tooltip shows up on the opposite side of the actual button 

![screen shot 2018-12-04 at 3 13 08 am](https://user-images.githubusercontent.com/21211903/49431355-eaa7d480-f772-11e8-92c5-f96ba04c1da0.png)

**Comment by XimeMora** [comment]
This is still happening.

**Comment by tnrich** [comment]
On hde?

**Comment by XimeMora** [comment]
@tnrich yeah on hde, I don't know if it has the latest version of ove.
