### ISSUE TITLE
Add warning to Circular view when viewing linear sequence

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#437]
#431

**Comment by tnrich** [comment]
I've added this warning: 

![image](https://user-images.githubusercontent.com/2730609/49817479-2cadb900-fd25-11e8-9e54-bfb59319a202.png)

When viewing a linear sequence in the circular view. Hopefully that will be enough @gmcarthuriv

**Comment by XimeMora** [comment]
Looks good.
