### ISSUE TITLE
Creating a new feature is showing a warning when the feature spans the origin

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#438]
@tnrich
Creating a new feature is showing a warning in the Start and End fields "Range must fit within sequence" when the feature spans the origin and the feature can't be created.

![screen shot 2018-12-12 at 4 35 17 am](https://user-images.githubusercontent.com/21211903/49864354-f37a5500-fdc7-11e8-958b-cab0adbceba8.png)

**Comment by tnrich** [comment]
Good catch!

**Comment by XimeMora** [comment]
Fixed!
