### ISSUE TITLE
Pairwise Alignment not opening when submitting from the vector editor

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#439]
@tnrich

When in vector editor submitting the sequence to Pairwise Alignment seems to work because the record appears in the library but double-clicking to open it shows a blank page and the following error:

![screen shot 2018-12-12 at 4 53 06 am](https://user-images.githubusercontent.com/21211903/49865332-49e89300-fdca-11e8-970d-443c80133fe7.png)

The same happens when using the "Align Sequences" context menu from the Sequences library on hde.

It is working fine if submitting from the hde top menu/Explorer though.

**Comment by tnrich** [comment]
@tiffanydai do you mind taking a look at this one?

**Comment by tiffanydai** [comment]
@tnrich yeah i assigned it to me, i know what's going wrong and will push a fix today

**Comment by tnrich** [comment]
awesome!

**Comment by XimeMora** [comment]
This has been fixed!
