### ISSUE TITLE
Version history causes application to exit fullscreen mode

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#445]
1. Open OpenVE in fullscreen mode with version history enabled
2. Click on "View History" Icon

Results: Full screen mode is lost with the headers not showing up anymore. The app also seems to be rendering behind some of the widgets of the embedding app (ICE in this case).

 Attached are two screenshots: one showing fullscreen mode and the second showing what happens after clicking the "View history" icon

![history](https://user-images.githubusercontent.com/1694026/52242065-5c42f280-288a-11e9-8137-2b635d81d5cf.png)
![history2](https://user-images.githubusercontent.com/1694026/52242072-5ea54c80-288a-11e9-8835-583ef7e2100d.png)

@tnrich

**Comment by tnrich** [comment]
@hplahar can you give me a URL where I can see it occurring? I don't think I can reproduce this locally.

**Comment by tnrich** [comment]
Okay @hplahar, I've pushed a fix. Can you try the latest ove version 7.1.39?
