### ISSUE TITLE
Ability to add custom logic to the Add/Edit feature dialog

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#446]
This is a request coming from jagpreet.kaur@bayer.com

Basically they want a way to add additional custom logic to the Add/Edit Feature dialog to support their workflow. 

As a first pass I'm providing a way to pass additional components as props to the <Editor/> component.

**Comment by tnrich** [comment]
An example of doing this can be seen here: 

http://teselagen.github.io/openVectorEditor/#/EditoroverrideAddEditFeatureDialog=true

The code looks like: 

```js
<Editor AddOrEditFeatureDialogOverride={MyCustomComponent}/>
```

**Comment by jjkaur** [comment]
@tnrich :Thank you so much for addressing our issue so quickly! This is exactly what we were looking for.

**Comment by tnrich** [comment]
Closing this. Let me know if you have any issues @jjkaur
