### ISSUE TITLE
Back button getting confused when in standalone mode and viewing version history

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#447]
More info coming

**Comment by tnrich** [comment]
@hplahar I can't reproduce this in the standalone editor demo (http://teselagen.github.io/openVectorEditor/#/Standalone). The back button seems to work fine there.

Can you provide me a link where I can reproduce this one?

**Comment by hplahar** [comment]
Try using registry-test2.jbei.org now. I have updated it to 8.0.5.
Open sequence in "full" vector editor, then click on "history icon", then "back" then "Close fullscreen mode" icon.

**Comment by tnrich** [comment]
@hplahar could you post the code your using to instantiate the editor here please

**Comment by hplahar** [comment]
$scope.vEeditor = $window.createVectorEditor("createDomNodeForMe", {
                        editorName: "vector-editor",
                        doNotUseAbsolutePosition: true,
                        isFullscreen: true,
                        shouldAutosave: true,
                        disableSetReadOnly: true,
                        handleFullscreenClose: function () { // this will make the editor fullscreen by default, and will allow you to handle the close request
                            $scope.vEeditor.close();         // handle vector editor root removal and clean up
                        },

                        getSequenceAtVersion: function (versionId) {
                            return openVEData.sequenceData;
                            // teselagenSequenceData
                        },

                        getVersionList: function () {
                            return [{
                                versionId: "51241",
                                dateChanged: "01/11/2019",
                                editedBy: "Hector Plahar",
                                revisionType: "Feature Add"
                            },
                                {
                                    versionId: "51241",
                                    dateChanged: "01/11/2019",
                                    editedBy: "Hector Plahar",
                                    revisionType: "Feature Add"
                                },
                                {
                                    versionId: "51241",
                                    dateChanged: "01/11/2019",
                                    editedBy: "Hector Plahar",
                                    revisionType: "Feature Remove"
                                }]
                        },

                        onSave: function (event, sequenceData, editorState, onSuccessCallback) {
                            // omitted for brevity
                        },

                        onCopy: function (event, copiedSequenceData, editorState) {
                            var clipboardData = event.clipboardData || window.clipboardData || event.originalEvent.clipboardData;
                            clipboardData.setData('text/plain', copiedSequenceData.sequence);
                            openVEData.selection = editorState.selectionLayer;
                            openVEData.openVECopied = copiedSequenceData;
                            clipboardData.setData('application/json', JSON.stringify(openVEData));
                            event.preventDefault();
                        },

                        onPaste: function (event, editorState) {
                            var clipboardData = event.clipboardData || window.clipboardData || event.originalEvent.clipboardData;
                            var jsonData = clipboardData.getData('application/json');
                            if (jsonData) {
                                jsonData = JSON.parse(jsonData);
                                jsonData = jsonData.openVECopied;
                            }
                            return jsonData || {sequence: clipboardData.getData("text/plain")}
                        },

                        PropertiesProps: {
                            propertiesList: [
                                "features",
                                "translations",
                                "cutsites",
                                "orfs"
                            ]
                        },
                        ToolBarProps: {
                            //name the tools you want to see in the toolbar in the order you want to see them
                            toolList: [
                                "versionHistoryTool",
                                // "saveTool",
                                "undoTool",
                                "redoTool",
                                "cutsiteTool",
                                "featureTool",
                                "orfTool",
                                "findTool",
                                "visibilityTool"
                            ]
                        }
                    });

                    $scope.vEeditor.updateEditor({
                        readOnly: remote.remote || !entry.canEdit,
                        sequenceData: openVEData.sequenceData,
                        annotationVisibility: {
			    parts: false,
                            orfs: false,
                            cutsites: false
                        },
                        annotationsToSupport: {
                            features: true,
                            translations: true,
                            parts: false,
                            orfs: true,
                            cutsites: true,
                            primers: false
                        },
                        panelsShown: [
                            [
                                {
                                    id: "circular",
                                    name: "Plasmid",
                                    active: true
                                },

                                {
                                    id: "rail",
                                    name: "Linear Map",
                                    active: false
                                },
                                {
                                    id: "properties",
                                    name: "Properties",
                                    active: false
                                }
                            ],
                            [
                                {
                                    id: "sequence",
                                    name: "Sequence Map",
                                    active: true
                                }
                            ]
                        ]
                    })
                };

**Comment by tnrich** [comment]
Thanks Hector I'll get back to you later today!

**Comment by tnrich** [comment]
This should be fixed in open-vector-editor@8.0.28
