### ISSUE TITLE
Requesting an onSequenceChange Event

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/openVectorEditor#456]
@tnrich

My team has a need to respond to sequence being inserted/replaced/cut from the vector map.  When sequence is inserted/replaced, we would like to add a part that marks the change as a helpful landmark for users.  Also, when sequence is changed, we would like to remove features that overlap the change (and potentially additional features not overlapped by the change).  One way that might enable us is an `onSequenceChange` event that passes in coordinates on the new state of the sequence where the change is located (and potentially also coordinates of the previous state where sequence was removed).  We are certainly open to more straightforward ways of doing this that may already exist but haven’t found a solution that isn’t an awful code smell.  Is there already a different way to mark changes the user has made to the vector as helpful landmarks or are there plans?  Thank you for all of you hard work building this module; it is amazing!

I have pasted images of 1) before the change, 2) after the sequence change (replace) current state and 3) the desired outcome after the change (replace)

1) before the change
![Screen Shot 2019-03-14 at 8 27 56 AM](https://user-images.githubusercontent.com/4339551/54362226-8e3c3700-4636-11e9-9f90-3a3c9bf6caa6.png)

2) after the sequence change (replace) current state
![Screen Shot 2019-03-14 at 8 28 36 AM](https://user-images.githubusercontent.com/4339551/54362263-9dbb8000-4636-11e9-9f6c-3dd32db2c92e.png)

3) the desired outcome after the change (replace)
![Screen Shot 2019-03-14 at 8 22 50 AM](https://user-images.githubusercontent.com/4339551/54362348-c5aae380-4636-11e9-8d12-07bccd3d1695.png)

**Comment by tnrich** [comment]
Hey @ericsturman yep I can definitely see why you would want to have some more customizability around the insert/replace/delete. 

I think a custom defined sequenceChanged callback that allows inserting custom logic before the sequence update action is fired makes sense. 

I'll look into implementing this and let you know.

**Comment by tnrich** [comment]
@ericsturman do you want to be alerted of actions that say reverse complement or complement the sequence? Or only insert and deletes?

**Comment by tnrich** [comment]
Hey @ericsturman I added a first pass at a `beforeSequenceInsertOrDelete` handler. The demo for it can be seen here: 

http://teselagen.github.io/openVectorEditor/#/Editor?beforeSequenceInsertOrDelete=true

In the demo I'm basically doing what you asked for in your question but for inserts only. I don't modify the delete:


```js

//the following gets passed as a prop to the <Editor/> component:
              beforeSequenceInsertOrDelete: (
                sequenceDataToInsert,
                existingSequenceData,
                caretPositionOrRange
              ) => {
                window.toastr.info("beforeSequenceInsertOrDelete triggered");
                if (!sequenceDataToInsert.size) return;
                return {
                  //override the sequenceDataToInsert
                  sequenceDataToInsert: {
                    ...sequenceDataToInsert,
                    parts: [
                      ...sequenceDataToInsert.parts,
                      {
                        name: "CHANGED_SEQUENCE",
                        start: 0,
                        end: sequenceDataToInsert.size - 1
                      }
                    ]
                  },
                  //override the existingSequenceData
                  existingSequenceData: {
                    ...existingSequenceData,
                    ...["parts", "features", "primers"].reduce((acc, key) => {
                      const annotations = existingSequenceData[key];
                      acc[key] = annotations.filter(
                        a =>
                          !isRangeOrPositionWithinRange(
                            caretPositionOrRange,
                            a,
                            existingSequenceData.size
                          )
                      );
                      return acc;
                    }, {})
                  }
                };
              }
            
```

**Comment by ericsturman** [comment]
@tnrich ,

Thank you so much for the quick response!  This looks like the right solution and I have started incorporating/testing it.  I will give you an update on Monday.

Have a great weekend.
Eric

**Comment by ericsturman** [comment]
@tnrich Thank you for this feature it works perfectly for us.  One thing we did notice is that the `annotationVisiblity` settings in our editor props object is getting overwritten (we are setting `primers: false` but they are displaying anyway (this was working for us before the upgrade to 8.0.14).  I tested this locally with the OVE project locally and it seems to not be working there either...are you seeing this behavior on your end?

**Comment by tnrich** [comment]
@ericsturman thanks for the heads up on that. I can reproduce it locally so I'll set up a test for it!

**Comment by tnrich** [comment]
I've published v8.0.19. That should fix the visibilities setting issue. I've set up a test for it too

**Comment by ericsturman** [comment]
@tnrich confirmed...thank you!

**Comment by tnrich** [comment]
Hmm my fix actually introduced another bug where now annotationVisibility is being overridden when toggling readOnly or certain other props. I'm going to try to set up a test for that bug now and fix it!

**Comment by tnrich** [comment]
v8.0.20 contains the final fix!

**Comment by tnrich** [comment]
Let me know if you have any issues. Closing this
