### ISSUE TITLE
Add Additional Enzymes > Create your own enzyme > Add the number of cuts

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#460]
@tnrich 
From the cutsites menu when selecting Add Additional Enzymes > Create your own enzyme > the number of cuts should be displayed next to the enzyme name.

![Screen Shot 2019-04-05 at 7 22 19 PM](https://user-images.githubusercontent.com/21211903/55663219-d505f280-57d8-11e9-8c42-0788e3e953df.png)

![Screen Shot 2019-04-05 at 7 22 43 PM](https://user-images.githubusercontent.com/21211903/55663223-e0591e00-57d8-11e9-9f8b-42880abcf283.png)

**Comment by tnrich** [comment]
Closing as this is no longer how we add enzymes (done in settings now)
