### ISSUE TITLE
Can't change a sequence from circular to linear

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#461]
@tnrich
Trying to change a sequence from Circular to Linear from Properties > General is not working and it is throwing an error:

![Screen Shot 2019-04-06 at 1 40 22 AM](https://user-images.githubusercontent.com/21211903/55666513-2d56e780-580d-11e9-9009-f7c5d4f8dff8.png)

**Comment by tnrich** [comment]
This has been fixed in OVE now. It will make it to HDE in a bit. I'm going to wait until tests are passing on master consistently!
