### ISSUE TITLE
Request for GC content on selected sequence region.

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/openVectorEditor#464]
@tnrich

We are considering adding the ability for users to know the GC content of a selected region of sequence.  This seems like a feature that would have fairly broad appeal.  I have attached a screenshot with the suggested change to the lower status bar where selection coordinates are displayed.  We would be interested in alternative solutions as well.

Thank you,
Eric
![Screen Shot 2019-04-08 at 11 53 09 AM](https://user-images.githubusercontent.com/4339551/55742461-5df97580-59f5-11e9-8134-f82112912d7d.png)

**Comment by tnrich** [comment]
Hey @ericsturman let me run this by @eabeliuk and @njhillson. Seems like it would indeed be a universally useful feature. Also we could possibly have it be user/implementer toggle-able. 

Would this be something you'd be interested in making a PR for @ericsturman? I've update the readme to include more detailed steps for outside developer contributions: https://github.com/TeselaGen/openVectorEditor#outside-developer-set-up-steps

**Comment by ericsturman** [comment]
I am fine with making a PR...thanks!

**Comment by tnrich** [comment]
Awesome! Let me know if you need help with anything or get stuck for some reason. Good luck!

**Comment by tnrich** [comment]
Closed via https://github.com/TeselaGen/openVectorEditor/pull/467 
Nice work @ericsturman 💯
