### ISSUE TITLE
Search for amino acid sequences in the sequence viewer

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#471]
The search functionality only appears to apply to the DNA sequences in the HDE/LIMS sequence viewer. It would be useful to be search for selected amino acid sequences as well for translated CDSs.

**Comment by siobhandavis** [comment]
TG-299

**Comment by siobhandavis** [comment]
@tnrich if you have any bandwidth to pick this up, that would be awesome. Thanks!

**Comment by tnrich** [comment]
Closing as this can already be done via the wrench option dropdown in the search tool

**Comment by tnrich** [comment]
Closing as this can already be done via the wrench option dropdown in the search tool
