### ISSUE TITLE
Search/find tool > field should always be expanded

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#474]
@tnrich, @tiffanydai, @craftjk, @siobhandavis,

Having to click on the magnifying glass icon just to be able to drop in a sequence for searching is really annoying. It would be better to simply have the field/bar expanded permanently.

![image](https://user-images.githubusercontent.com/17152701/57741257-e57b7980-7670-11e9-8ed8-d901feb95d50.png)

**Comment by tnrich** [comment]
@gmcarthuriv you can also toggle that using Cmd-F 

Could that be useful for you? I am a little hesitant to give that option just because it takes up more space in the toolbar and could cause the icons to wrap on small screens.

**Comment by gmcarthuriv** [comment]
@tnrich, the shortcut will work well - thanks.
