### ISSUE TITLE
Closing a search is inefficient

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#475]
@tnrich, @tiffanydai, @craftjk, @siobhandavis,

As a user, I expect my search to close when clicking the "x" to the left of the find/search bar. Instead, it just hides the search bar and leaves the sequence query.

![image](https://user-images.githubusercontent.com/17152701/57741435-a568c680-7671-11e9-92e1-88d7eacd15da.png)

![image](https://user-images.githubusercontent.com/17152701/57741336-430fc600-7671-11e9-822b-ab5f1317e5df.png)

![image](https://user-images.githubusercontent.com/17152701/57741535-1b6d2d80-7672-11e9-9809-eb32fda433f6.png)

![image](https://user-images.githubusercontent.com/17152701/57741529-14461f80-7672-11e9-8494-56c9c12edbe6.png)

**Comment by tnrich** [comment]
We've discussed this before here: https://github.com/TeselaGen/hde/issues/2953

>>Closing the search box does not clear the search (i.e., it does not delete the query). To clear the search box, I have to select the query and delete it. I would expect that clicking the "x" on the left side of the search box would clear the search box, not simply hide it.

>Peony does not clear the highlights when closing. If we want to make it that way I can

I am fine to change it to do it differently. I would propose that we make it like the built in chrome find tool. Where the search is cleared when closing, but upon re-open, the last search text is still being searched for and selected for easy "paste-over": 

![image](https://user-images.githubusercontent.com/2730609/57871514-55e3e100-77be-11e9-934d-3837caceb886.png)

Does that sound alright?

**Comment by gmcarthuriv** [comment]
@tnrich - sounds reasonable. Let's give it a shot!

**Comment by gmcarthuriv** [comment]
@tnrich, I think I've identified the real issue here. The problem, in my opinion, is that the highlight persists even after clicking away or pressing ESC or other similar actions. The only way I've found to remove the highlight is to delete the string in the search/find box. However, if this were similar to the Chrome tool, then the highlight would disappear after clicking elsewhere.

**Comment by tnrich** [comment]
Hey @gmcarthuriv I've already made a release where the functionality you're looking for has landed. you can try it out here: http://teselagen.github.io/openVectorEditor/#/Editor

The search layers now disappear whenever the box is closed which can be by hitting the close icon or by hitting esc: ![findtool](https://user-images.githubusercontent.com/2730609/58601794-501ae080-823f-11e9-8255-9a5e5c0b0ef4.gif)

Please let me know if this is still missing something. 


It probably hasn't yet made it to hde/lims but it should be there by the next release.
