### ISSUE TITLE
Find/search sequence requires clicking for selection

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#476]
@tnrich, @tiffanydai, @craftjk, @siobhandavis,

As a user, I expect to be able to act immediately after a sequence is found via search. For example, I should be able to right-click and make a Part immediately after finding a sequence via the find tool. Currently, however, the sequence is only highlighted and requires an additional action (clicking on the highlighted sequence) before being able to work with it.

For searches that return multiple hits, I understand the need to select the desired one - but if it's a unique return, then I would expect full selection (not just highlighting).

![image](https://user-images.githubusercontent.com/17152701/57741626-8454a580-7672-11e9-89e8-3cee9d8277d3.png)

![image](https://user-images.githubusercontent.com/17152701/57741668-c0880600-7672-11e9-8784-82e03c9ef0c5.png)

**Comment by tnrich** [comment]
Good idea @gmcarthuriv . I've made it so right clicking a search layer will automatically select the search layer. This will make it into the next OVE release
