### ISSUE TITLE
Oversized fonts for GenBank feature labels

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#478]
@tnrich, @tiffanydai, @craftjk, @siobhandavis,

I would encourage bringing the font size down some for GenBank feature labels. It's fairly intense on my monitor (which is an ultrawide).

![image](https://user-images.githubusercontent.com/17152701/57742215-1cec2500-7675-11e9-8442-ef79d8c8add0.png)

**Comment by tnrich** [comment]
@gmcarthuriv I think I've got a first pass of what you're looking for working on a branch. @tiffanydai  could you take a look at the `tnrScaleDownLargeLabels` branch on a large screen monitor and see what you think. The labels max font size should essentially be capped around 16px: 

![image](https://user-images.githubusercontent.com/2730609/58454536-a0752f80-80d3-11e9-8acc-0f1dab85fc0c.png)

![image](https://user-images.githubusercontent.com/2730609/58454641-f34ee700-80d3-11e9-834b-62b60e2e0ea1.png)

**Comment by tiffanydai** [comment]
The proportions look better on my monitor (27"). Would you prefer the labels even smaller, @gmcarthuriv ? 

before: 
![image](https://user-images.githubusercontent.com/35508772/58501531-866e3800-8139-11e9-9218-c0f1a5d04208.png)

after: 
![image](https://user-images.githubusercontent.com/35508772/58501549-8ff7a000-8139-11e9-8c77-37b13897e652.png)

**Comment by tnrich** [comment]
I'll publish this as is right now and we can iterate if it still isn't meeting your needs @gmcarthuriv

**Comment by gmcarthuriv** [comment]
@tnrich, @tiffanydai - sweet! Looks great!
