### ISSUE TITLE
Custom tab or Custom properties tab

### ISSUE THREAD

**Issue by jjkaur** [TeselaGen/openVectorEditor#486]
@tnrich

Hello Thomas,
Is there any way to add custom properties tab or custom tab in OVE? Here is the screenshot for reference.
![17463A1A-AE77-4E88-9B0D-28FF5D063B84](https://user-images.githubusercontent.com/17455433/61649538-4ded6500-ac77-11e9-9c4d-a8b3ace2e453.jpg)

**Comment by tnrich** [comment]
Hey @jjkaur yes this should now be possible. I had to make a couple small tweaks but you should be able to view the demo page for an example of how to do this. 

![image](https://user-images.githubusercontent.com/2730609/61669774-2659c500-ac96-11e9-8654-774b8d02b49e.png)


To see it in action just go to http://teselagen.github.io/openVectorEditor/#/Editor and click either the "Customize tabs" or  "Customize property tabs" toggles.

Here's how to create a regular custom tab:
```
//override the panelsShown redux state adding your custom tab wherever you see fit:
updateEditor(store, "DemoEditor", {
  panelsShown: [ 
    [ //the first row of tabs
      {
        id: "rail",
        name: "Linear Map",
        active: true
      },
      {
        id: "myCustomTabId",
        name: "My Custom Tab",
        //canClose: true //optionally make it closeable
      }
    ],
    [ //the second row of tabs
      {
        id: "sequence",
        name: "Sequence Map",
      },
      {
        active: true,
        id: "circular",
        name: "Circular Map"
      },
      {
        id: "properties",
        name: "Properties"
      }
    ]
  ]
})

//create the custom tab component:
const MyCustomTab = connectToEditor(({ sequenceData = {} }) => {
  //you can optionally grab additional editor data using the exported connectToEditor function 
  return {
    sequenceData
  };
})(function(props) {
  console.info("These are the props passed to our Custom Tab:", props);
  return (
    <div>
      <h3>Hello World, I am a Custom Tab</h3>
      <h4>sequenceLength: {props.sequenceData.sequence.length}</h4>
    </div>
  );
});

//and pass the custom tab component to the editor via the panelMap prop such that the key matches the panel id:
<Editor panelMap={{ 
  myCustomTabId: MyCustomTab
}} />
```


And here's how to create a custom properties tab:
```js
//create your custom tab:
const MyCustomTab = connectToEditor(({ sequenceData = {} }) => {
  //you can optionally grab additional editor data using the exported connectToEditor function 
  return {
    sequenceData
  };
})(function(props) {
  console.info("These are the props passed to our Custom Tab:", props);
  return (
    <div>
      <h3>Hello World, I am a Custom Tab</h3>
      <h4>sequenceLength: {props.sequenceData.sequence.length}</h4>
    </div>
  );
});

//and pass it to the <Editor/> via PropertiesProps
PropertiesProps: {
  propertiesList: [
    {name: "Custom", Comp: MyCustomTab},
    "general",
    "features",
    {
      name: "parts",
      additionalFooterEls: (
        <Button
          onClick={() => {
            window.toastr.success(
              "properties overrides successfull"
            )
          }}
        >
          propertiesProps parts footer button
        </Button>
      )
    },
    "primers",
    "translations",
    "cutsites",
    "orfs",
    "genbank"
  ]
}

```

Let me know if you have any issues getting this to work or if you're confused by anything. Cheers!

**Comment by jjkaur** [comment]
Excellent. Thank you so much for the awesome product and this quick feature. It works perfectly :-)

**Comment by tnrich** [comment]
Thanks! Glad to hear it! Just out of curiosity, what are you putting in your custom tab?

**Comment by jjkaur** [comment]
We have few extra fields associated to a vector like comments, alias, synonyms. Also we have certain rules on who can view or edit that information. So we put that as part of the custom tab under Properties.

**Comment by hi-asan** [comment]
@tnrich 您好，我想了解一下，通过umd的方式如何去自定义面板呢，非常感谢您

**Comment by hi-asan** [comment]
@tnrich Hello, I want to know how to customize the panel through umd, thank you very much, the front-end library I use now is vue

**Comment by hi-asan** [comment]
<img width="541" alt="image" src="https://github.com/TeselaGen/openVectorEditor/assets/12293038/65dc3a1f-596f-4e38-9861-2d66d0f29528">

I can do it this way, but every time I switch the panel to here, the test will re-render itself and execute the mount function. As a result, I have to manage his data outside
