### ISSUE TITLE
Add version number to "Help->About"

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#493]
@tnrich Can you add the version number to "Help->About" Will be super helpful to quickly figure out which version user is on.

**Comment by tnrich** [comment]
Yep! Good idea, I'll add it!

**Comment by tnrich** [comment]
I've added it here: 
![image](https://user-images.githubusercontent.com/2730609/63048249-f95e9380-be8a-11e9-885c-2236d206324c.png)

and here: 
![image](https://user-images.githubusercontent.com/2730609/63048266-024f6500-be8b-11e9-8a29-328d08a8056b.png)

I'll let you know when that gets released.

**Comment by tnrich** [comment]
@hplahar This has been released!

**Comment by hplahar** [comment]
@tnrich great. thanks
