### ISSUE TITLE
"Remove duplicated features" option

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#546]
@tnrich
It will be useful to have an option to enable a user remove all (and leave just 1 - not sure what the right term for that is) instances of duplicated features. So, if there is a feature that occurs multiple times, with the same name and location, the feature will enable removal of all but 1 of that feature. See the attached screenshot for a use case where it will help

<img width="1429" alt="Screen Shot 2019-10-23 at 12 12 15 PM (1)" src="https://user-images.githubusercontent.com/1694026/67436464-4b1a4d00-f5a3-11e9-9e6c-c798cc63cb86.png">

**Comment by tnrich** [comment]
Hey @hplahar I went ahead and added a Remove Duplicate Features/Parts/Primers dialog to the app: 

![image](https://user-images.githubusercontent.com/2730609/67539140-e8957f80-f67c-11e9-90d4-111fb53841c3.png)

It can be accessed via the Tools Menu or the Properties panel or by right clicking a feature/part/primer and selecting "Remove Duplicate Features/Parts/Primers" 

It is enabled by default in open-vector-editor@10.1.14 and you can play with it here: http://teselagen.github.io/openVectorEditor/#/Editor

**Comment by hplahar** [comment]
That's great @tnric . Thanks for the quick turnaround
