### ISSUE TITLE
Add Manage Enzyme Groups Functionality; Add Ability to remove/hide enzymes from the single cutter grouping.

### ISSUE THREAD

**Issue by jjkaur** [TeselaGen/openVectorEditor#561]
@tnrich

In the cutsites property tab, all the single cutters are group together but there isn't a way to remove/hide one or more restriction enzymes from the single cutter grouping.Many of our users using OpenVectorEditor has requested for this functionality as they work with big list of single cutters. Many suggested to have a checkbox in the table of cutsite to hide/show the restriction enzymes.

**Comment by tnrich** [comment]
@jjkaur If you'd like to add this specific functionality I would be more than happy to a PR. I am not sure I'll be able to get around to fixing this immediately as I have other priorities on my plate at the moment. 

I'll let you know when that changes but for now I don't think I can fix this. Feel free to ask questions about anything if you do try to make the fix though. 

-Thomas

**Comment by jjkaur** [comment]
Thanks for the response. I will try to make the changes and submit a PR.

**Comment by tnrich** [comment]
@jjkaur cool! Let me know how it goes

**Comment by tnrich** [comment]
@jjkaur just checking in with you. Have you made much progress?

**Comment by jjkaur** [comment]
@tnrich : Not yet. I was on vacation. I will work with Eric to see what is needed for the PR.

**Comment by tnrich** [comment]
Linking https://github.com/TeselaGen/lims/issues/4410 and looping in @mfero and @tiffanydai 

@jjkaur @ericsturman I have been thinking about trying to improve the enzyme management system for a bit now. I have a branch I'm trying some stuff out on. I'm still working through what the UX might be and how it might work with both localstorage and a user configured db.

Here's a little bit of what I'm thinking so far: 

- [ ] Add a new "Manage Enzymes" dialog where users can create their own custom groups of enzymes 
- [ ] The Manage Enzymes dialog will be accessible from the existing cutsite filter dropdown as well as from "File>Tools>Manage Enzymes" and the cutsite properties list. 
- [ ] The Manage Enzymes dialog will have 3 "built-in" groups: "Common Enzymes", "All Enzymes", and "User-created Enzymes"
- [ ] Users will be able to create and save their own enzyme groups by selecting enzymes in other groups and moving them to the group of their choice:

![image](https://user-images.githubusercontent.com/2730609/76247707-38747d80-61fd-11ea-935c-b9abb526f27e.png)

- [ ] A list of helpful "Select..." options will allow users to quickly find the enzymes they might be looking for based on specific properties: 


![image](https://user-images.githubusercontent.com/2730609/76248018-bdf82d80-61fd-11ea-871b-6d7d815c02ae.png)

- [ ] Hovering an enzyme will show a preview of that enzyme in the bottom portion of the dialog: 
![image](https://user-images.githubusercontent.com/2730609/76248139-f992f780-61fd-11ea-9840-f1e78ce773bc.png)


- [ ] The user-created enzyme groups will then be available within the Cutsite filter dropdown at the top near "Single Cutters" 

- [ ] users should be able to easily uncheck any given enzyme from the currently selected group (single cutters, double cutters, my special enzyme group)
![image](https://user-images.githubusercontent.com/2730609/76257059-31a23680-620e-11ea-8462-132dc3567d50.png)

- [ ] there should be built-in storage of user preferences to localStorage and an exposed api for saving the groups to a desired backend (probably something like `window.updateUserEnzymeGroups` and `window.getUserEnzymeGroups`) 


Please note, the screenshots provide are quite rough and have not been styled to look nice. That said, any and all feedback is welcome. I think this is generally a step in the right direction but I also think that it might take a few iterations to get the UX flowing nicely. I'll update this ticket when I have a v1 that people can try out.

**Comment by tnrich** [comment]
Linking https://github.com/TeselaGen/lims/issues/4759 here

**Comment by jjkaur** [comment]
We had to develop a custom user based restriction enzyme list tool. Our user maintains a big master list of restriction enzymes. Cloners wanted to create a smaller user based custom restriction enzyme lists based on the selection from the master list. 
With the above mentioned features we will be able to remove our custom tool for the user based restriction enzyme groups. Also the ability to remove and hide the enzymes from the single cutter group will be really helpful for our cloners. Thank you for the awesome product :-)

**Comment by tnrich** [comment]
This has been released.
