### ISSUE TITLE
Add feature labels to LinearMap with label lines.

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/openVectorEditor#578]
@tnrich

Our users would like to be able to view all of the feature labels in the linear map.  Currently, the labels are inside the feature only for features larger than the label text size.  We would like to add the option to remove those labels and include them with the cutsite labels (with a different font style).  We would also like to make the lines always visible and change the style on hover, much like the circular view.  I wanted to get your thoughts.  I have added an image with only the cutsites including a hover.

![linear_view_labels](https://user-images.githubusercontent.com/4339551/74966609-f9f95900-53dc-11ea-9e53-67e08592b28c.png)

**Comment by tnrich** [comment]
Hey @ericsturman this is definitely something I'd be happy to accept a PR for if you're feeling up to doing it. I do think it should be too tough to implement. I've played around with different label strategies before and think it would be good to support multiple options. 

I'll take a look at the code and try to point you in the right direction

**Comment by tnrich** [comment]
@ericsturman just to get you started on this, I made a branch with a few changes on it. Here's the PR for it: https://github.com/TeselaGen/openVectorEditor/pull/579

**Comment by tnrich** [comment]
@ericsturman just a heads up that I made a little todo list in the PR of things that will need to be implemented

**Comment by tnrich** [comment]
Ok @ericsturman great work! 

I just released open-vector-editor@10.1.51 which has your changes and a few tweaks of my own. I adjusted the label drawing to fix labels from bunching up at the end of the "row". I also made the font family monospace to better be able to tell if a label would fit in a feature or not. I also centered the label inside the annotation better. 

Can you please try it out and see if you can find any issues with it. 

I think this is a really big usability enhancement, so great job getting this pushed through!

**Comment by tnrich** [comment]
@ericsturman going to close this issue. Feel free to re-open or make a new issue if anything arises.
