### ISSUE TITLE
Can't get a basic installation for React to work

### ISSUE THREAD

**Issue by onoufriosm** [TeselaGen/openVectorEditor#594]
I followed the installation guide on the Readme page on a fresh create-react-app project and I'm getting an error on missing packages.

This is what I did:
1. Fresh CRA installation
2. `yarn add install-peerdeps open-vector-editor`
3. `install-peerdeps open-vector-editor --dev --only-peers` 
4. render `<Editor {...editorProps}/>`

And I get the following error:
`Can't resolve '@blueprintjs/core'` 
which I understand is the first dependency in the devDependencies of this project.

Any ideas to get around this?

Thanks in advance.

@tnrich

**Comment by tnrich** [comment]
Hey @onoufriosm sorry about that. It looks like there are several packages that should be in the package.json peerDependencies field that aren't there currently. I'm trying out a fresh CRA install right now and will update the peerDependencies so this works out of the box.

**Comment by tnrich** [comment]
@onoufriosm I'm putting together a little example repo that will document how to use the <Editor/> in a CRA app. I'll let you know when that's ready to go. 

I'm sure you saw the docs but you can also use the editor as a UMD module like so: 
```html
<link rel="stylesheet" type="text/css" href="https://unpkg.com/open-vector-editor/umd/main.css"> 
<script type="text/javascript" src="https://unpkg.com/open-vector-editor/umd/open-vector-editor.js"></script>

<script>
const editor = window.createVectorEditor(yourDomNodeHere || "createDomNodeForMe", editorProps); /* createDomNodeForMe will make a dom node for you and append it to the document.body*/
editor.updateEditor(editorState);	
</script>
```

**Comment by onoufriosm** [comment]
@tnrich Thanks for the quick response. 

Unfortunately the script above ("https://unpkg.com/open-vector-editor/umd/open-vector-editor.js") errors for me on line 152026. Let me know if you are having the same issue and if you manage to get the CRA version to work.

**Comment by tnrich** [comment]
Hmm that's interesting to hear. I'll look into the unpkg issue you're mentioning. Maybe a bug was introduced recently? In any case I'll be setting up some more tests to make sure that that always is working :)

I'll let you know about the CRA stuff shortly

**Comment by tnrich** [comment]
Hey @onoufriosm here is where you can see how to run the app in a CRA environment. https://github.com/tnrich/ove-react-demo-repo

If you clone that repo you can see it working and see how to set up the redux store/provider and initialize the editor. You should just clone it and run: 
```
yarn
yarn start
```

I bundled all the deps into open-vector-editor@10.1.61 so you shouldn't have to worry about installing peer deps any more when setting it up in your own CRA app.

**Comment by tnrich** [comment]
Hey you can see a working version of the editor running using the UMD/unpkg code here: https://github.com/TeselaGen/openVectorEditor/blob/master/demo/public/UMDDemo.html

**Comment by tnrich** [comment]
Let me know if you have any more questions @onoufriosm or run into any other issues getting the editor set up and running to your liking. I'll close this one for now

**Comment by onoufriosm** [comment]
Thanks a lot! I can confirm that it's working now.
