### ISSUE TITLE
[Question] Initialize editor in edit mode

### ISSUE THREAD

**Issue by onoufriosm** [TeselaGen/openVectorEditor#599]
@tnrich

How can we initialize the editor in edit mode?

**Comment by tnrich** [comment]
You'll need to pass an onSave callback to allow for edit mode and readOnly=false

**Comment by onoufriosm** [comment]
I think my description wasn't clear. I can initialize the editor to not be read only i.e. I can see the lock toolbar icon to switch between edit and read only mode. 

What I'm trying to achieve is as soon as the editor opens to switch in edit mode.

**Comment by tnrich** [comment]
Hey @onoufriosm you're right, my last answer was a little hasty! You'll need to actually pass 

```
updateEditor({readOnly: false, ...additionalSettingsHere})
```

You'll need to do it in `updateEditor` because `isReadOnly` is managed as redux state so that you don't have to worry about tracking it (a user can set it themselves if they're given that option).

**Comment by onoufriosm** [comment]
Perfect works! Thanks!
