### ISSUE TITLE
Blueprint css spills to global css

### ISSUE THREAD

**Issue by onoufriosm** [TeselaGen/openVectorEditor#604]
@tnrich

Installing openVectorEditor adds styles coming from the blueprint package. Unfortunately this includes css rules for `a` tags, `body`, `html` e.t.c which clash with existing css rules in a project.

**Possible solution:**
Prepend the entire stylesheet with a unique css selector (e.g. `.open-vector-editor`) to avoid this issue?

**Comment by tnrich** [comment]
Hey @onoufriosm could you maybe dig around in the blueprint issues and see if anyone has experienced this before with their styles polluting the global ones? Maybe we can follow what they recommend doing there. If not could you ask a question to them and link it here please? 

Thanks!

**Comment by tnrich** [comment]
@onoufriosm 
I found this one: https://github.com/palantir/blueprint/issues/3194 

It looks like maybe we just have to deal with it? I don't really have access to the blueprint stylesheet to prepend anything to it as far as I can tell.

**Comment by onoufriosm** [comment]
Agreed this is a palantir issue. 

I'll fork the `teselagen-react-components` repo and see if I can wrap the css in another class. Is `teselagen-react-components` the only repo using the blueprint css?

**Comment by tnrich** [comment]
@onoufriosm that is correct. Sorry for the delayed response

**Comment by tnrich** [comment]
Closing this as it is outside the scope of OVE/TRC

**Comment by flange-ipb** [comment]
Good news @tnrich and @onoufriosm!
I have a hacky solution, which actually works! It embeds OVE into an iframe.

### Considerations:
#### iframe
I'm using the `srcdoc` attribute instead of `src` to include the iframe content. I'm confident this avoids any cross-origin issues. The inline content needs to be HTML-escaped.

#### rescaling the size of the iframe
- after loading its content (preview mode) using `onload` of the iframe,
- after clicking the "Open Editor" button (resize iframe to fullscreen using styles),
- after clicking the "Close Fullscreen Mode" button (resize iframe to preview mode)

As you can see, I'm registering onclick events on these buttons to execute the resizing. After clicking, the next button is created by OVE and I can register the onlick event in the next tick.

#### Interacting with OVE
use the variable `getIframe().contentWindow.editor`

### Code
```html
<html>
  <head>
    <script type="application/javascript">
      function getIframe() {
        return document.getElementById("iframe");
      }
      function resize() {
        var iframe = getIframe();
        iframe.width  = iframe.contentWindow.document.body.scrollWidth + 20;
        iframe.height = iframe.contentWindow.document.body.scrollHeight + 20;
      }
      function iframeToFullscreen() {
        // style from https://stackoverflow.com/a/14738668
        getIframe().setAttribute("style", "position:fixed; top:0; left:0; bottom:0; right:0; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;")
      }
      function iframeToSmallSize() {
        getIframe().setAttribute("style", "border:none;")
      }
      function addOnClickEventToButton(buttonClass, fn) {
        var button = getIframe().contentDocument.getElementsByClassName(buttonClass)[0];
        button.addEventListener("click", function() {
          fn.call();
        });
      }
      function addOnClickEventToOpenButton() {
        addOnClickEventToButton("bp3-button bp3-intent-primary", function() {
          iframeToFullscreen();
          
          // do this in the next tick
          setTimeout(function() {
            addOnClickEventToCloseButton();
          }, 0);
        });
      }
      function addOnClickEventToCloseButton() {
        addOnClickEventToButton("bp3-button bp3-minimal ve-close-fullscreen-button", function() {
          iframeToSmallSize();
          
          // do this in the next tick
          setTimeout(function() {
            addOnClickEventToOpenButton();
          }, 0);
        });
      }
    </script>
  </head>
  <body>
    <iframe id="iframe" style="border:none;" allowfullscreen="true" onload="resize(); addOnClickEventToOpenButton();" srcdoc="
      <html>
        <head>
          <link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;main.css&quot; />
        </head>
        <body>
          <script type=&quot;text/javascript&quot; src=&quot;open-vector-editor.js&quot;></script>
          <div id=&quot;targetId&quot;></div>
          <script type=&quot;text/javascript&quot;>
            var editor = window.createVectorEditor(document.getElementById(&quot;targetId&quot;), {
              withPreviewMode: true
            });

            editor.updateEditor({
              readOnly: true,
              sequenceData: {
                circular: false,
                sequence:
                  &quot;gtagagagagagtgagcccgacccccgtagagagagagtgagcccgacccccgtagagagagagtgagcccgacccccgtagagagagagtgagcccgaccccc&quot;,
                features: [
                  {
                    id: &quot;2oi452&quot;,
                    name: &quot;I'm a feature :)&quot;,
                    start: 10,
                    end: 20
                  }
                ]
              }
            });
          </script>
        </body>
      </html>
    ">
      Your browser doesn't support iframes.
    </iframe>
  </body>
</html>
```

What do you think?
