### ISSUE TITLE
Add Double Click to Edit Annotation

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/openVectorEditor#608]
George from Arzeda has suggested allowing users to double click on a feature annotation and edit it instead of having to right click. This was how the previous vector worked.

@tnrich

**Comment by tnrich** [comment]
- [ ] edit features on dbl click
- [ ] edit parts on dbl click 
- [ ] view warnings on dbl click
- [ ] highlight warning range on single click

**Comment by tnrich** [comment]
This should all land in open-vector-editor@10.1.66 @tgadam

**Comment by gmcarthuriv** [comment]
@tnrich, the feature implementation on the demo site is fantastic - nice work!

cc: @tgadam
