### ISSUE TITLE
Troubles Displaying Circular View without Redux

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/openVectorEditor#627]
@tnrich
I am trying to display the CircularViewUnconnected using the `tnrich/ove-react-demo-repo` with the following code and am only getting the size and name labels for the view but no features/parts/axis (there are no errors in the dev console).  Would it be possible to get an example or suggestions on how to display a static view of a vector without redux?  I have attached the code and a screenshot of the browser.

Thanks,
Eric

![Screen Shot 2020-07-15 at 10 51 59 AM](https://user-images.githubusercontent.com/4339551/87567396-dd123a80-c689-11ea-9a91-e1489629bf27.png)
![Screen Shot 2020-07-15 at 10 52 20 AM](https://user-images.githubusercontent.com/4339551/87567417-e0a5c180-c689-11ea-9232-3a5ad1aed6ba.png)

**Comment by tnrich** [comment]
Hey @ericsturman I'll look into it and get back to you. This should certainly be possible. 

One thing you could try in the meantime is using the top level export <SimpleCircularOrLinearView/> component and see if you have better results. Here's the demo for that: 

http://teselagen.github.io/openVectorEditor/#/SimpleCircularOrLinearView?circular=true

It is not a redux connected component. Here's the source code for that demo: 

```
<SimpleCircularOrLinearView
          {...{
            ...(this.state.hideNameAndInfo && { hideName: true }),
            ...(this.state.hoverPart && { hoveredId: "fakeId1" }),
            ...(this.state.changeSize && { height: 500, width: 500 }),
            // annotationVisibility: {
            //   cutsites: this.state.showCutsites
            // }

            ...(this.state.toggleSelection && {
              selectionLayer: { start: 2, end: 30 }
            }),
            partClicked: () => {
              window.toastr.success("Part Clicked!");
            },
            partRightClicked: () => {
              window.toastr.success("Part Right Clicked!");
            },

            sequenceData: {
              // annotationLabelVisibility: {
              //   parts: false,
              //   features: false,
              //   cutsites: false,
              //   primers: false
              // },
              // annotationVisibility: {
              //   axis: sequenceData.circular
              // }
              ...(this.state.noSequence
                ? {
                    noSequence: true,
                    size: this.state.limitLengthTo50Bps ? 50 : 164
                  }
                : {
                    sequence: this.state.limitLengthTo50Bps
                      ? "GGGAAAagagagtgagagagtagagagagaccacaccccccGGGAAAaga"
                      : "GGGAAAagagagtgagagagtagagagagaccacaccccccGGGAAAagagagtgagagagtagagagagaccacaccccccGGGAAAagagagtgagagagtagagagagaccacaccccccGGGAAAagagagtgagagagtagagagagaccacacccccc"
                  }),
              name: "Test Seq",
              circular: this.state.circular, //toggle to true to change this!
              features: [
                {
                  name: "Feat 1",
                  id: "fakeId2",
                  color: "green",
                  start: 1,
                  end: 20
                }
              ],
              parts: [
                {
                  name: "Part 1",
                  id: "fakeId1",
                  start: 10,
                  end: 20,
                  ...(this.state.togglePartColor && { color: "override_red" })
                },
                {
                  name: "Part 2",
                  id: "fakeId2",
                  start: 25,
                  end: 30,
                  ...(this.state.togglePartColor && { color: "override_blue" })
                }
              ]
            }
          }}
        />
```

**Comment by ericsturman** [comment]
Thank you for the quick response... unfortunately I get the following error when using `SimpleCircularOrLinearView`: `browser.js:38 Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(withHandlers(Component))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(withHandlers(Component))".`

**Comment by tnrich** [comment]
Hmm I'll look into that as well! Thanks @ericsturman

**Comment by tnrich** [comment]
@ericsturman this option should be live in open-vector-editor@10.1.84 

You should be able to see a demo here http://teselagen.github.io/openVectorEditor/#/SimpleCircularOrLinearViewNoRedux in a few minutes. 

Just pass a `noRedux=true` to SimpleCircularOrLinearView or Linear/CircularViewUnconnected to be able to render it outside of a redux context.

**Comment by tnrich** [comment]
I'm going to close this. Please feel free to re-open if you still experience any sort of issue.

**Comment by ericsturman** [comment]
@tnrich this is working perfectly... Thank you!
