### ISSUE TITLE
Is it possible to run two or more instances of OVE?

### ISSUE THREAD

**Issue by MarcelBolten** [TeselaGen/openVectorEditor#659]
Hi Thomas (@tnrich),

I try to integrate OVE in [eLabFTW](https://github.com/elabftw/elabftw) (an electronic lab notebook). Using the provided [umd version](https://github.com/TeselaGen/openVectorEditor#via-npm) it is working the way I want. OVE is a really cool tool!
However, eLabFTW has the option to attache files to an experiment and they are presented in a thumbnail overview.
My idea is to use the `withPreviewMode` feature and generate previews this way. For a single file it works great but if there are two or more files the previews all look the same (see below) even though the parsed files shows the expected different sequences.
Is it due to my lack of JS knowledge (I'm not all too experienced) and I need to dig deeper to make it work or is it not possible at all with the umd version of OVE?
Any help and/or comment is highly appreciated.

Cheers,
Marcel

![grafik](https://user-images.githubusercontent.com/65481677/96087368-998dbf00-0e78-11eb-8322-0357a903bc53.png)
![grafik](https://user-images.githubusercontent.com/65481677/96087284-76fba600-0e78-11eb-86ee-ab84463c7ffc.png)

**Comment by tnrich** [comment]
Hey @MarcelBolten I'm glad to hear that OVE is being used for your electronic lab notebook! OVE should indeed be able to handle multiple separate sequences but perhaps the UMD code hasn't been set up well for doing that. I'll look into it and let you know. Cheers, Thomas!

**Comment by tnrich** [comment]
@MarcelBolten I've updated the UMD demo to demonstrate how to set up multiple unique instances. I did catch a possible state collision between UMD editors and fixed it so I'd use open-vector-editor@12.0.4 or higher. Here's the link to the demo http://teselagen.github.io/openVectorEditor/UMDDemo.html and a screenshot of what that looks like:  

![image](https://user-images.githubusercontent.com/2730609/96165123-0fbe1000-0ed1-11eb-84d7-06391c7bf6c1.png)


And here's what the code looks like: 

```const editor = window.createVectorEditor("createDomNodeForMe", {
        withPreviewMode: true,
        // isFullscreen: true,
        showMenuBar: true
      });
      /* createDomNodeForMe will make a dom node for you and append it to the document.body*/
      editor.updateEditor({
        editorName: "FirstSequence",
        sequenceData: {
          circular: true,
          sequence:
            "gtagagagagagtgagcccgacccccgtagagagagagtgagcccgacccccgtagagagagagtgagcccgacccccgtagagagagagtgagcccgaccccc",
          features: [
            {
              id: "2oi452",
              name: "I'm a feature :)",
              start: 10,
              end: 20
            }
          ]
        }
      });
      const editor2 = window.createVectorEditor("createDomNodeForMe", {
        withPreviewMode: true,
        // isFullscreen: true,
        showMenuBar: true,
        editorName: "AnotherSequence"
      });
      /* createDomNodeForMe will make a dom node for you and append it to the document.body*/
      editor2.updateEditor({
        sequenceData: {
          name: "Another Sequence",
          circular: false,
          sequence: "gtaacccccc",
          features: [
            {
              id: "agog98",
              name: "2nd Feature",
              type: "CDS",
              start: 1,
              end: 5
            }
          ]
        }
      });
      const editor3 = window.createVectorEditor("createDomNodeForMe", {
        withPreviewMode: true,
        // isFullscreen: true,
        showMenuBar: true,
        editorName: "YetAnotherSequence"
      });
      /* createDomNodeForMe will make a dom node for you and append it to the document.body*/
      editor3.updateEditor({
        sequenceData: {
          name: "Wait for Me!",
          circular: true,
          sequence:
            "gtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaaccccccgtaacccccc",
          features: [
            {
              id: "19f0fjj",
              name: "abcd",
              type: "RBS",
              start: 1,
              end: 5
            },

            {
              id: "24t2t",
              name: "pj1",
              type: "CDS",
              start: 10,
              end: 50
            },
            {
              id: "82020000",
              name: "pj3",
              type: "CDS",
              start: 10,
              end: 50
            }
          ]
        }
      });```

**Comment by tnrich** [comment]
Let me know how that works for you and if you run into any other issues :)

**Comment by MarcelBolten** [comment]
@tnrich thank you very much!
Great support, fast response. 🎉 just awesome.
Now it works as expected.

There is a new little issue though:
After expansion to full screen mode the rotate functionality for circular plasmids works only for the first instance smoothly.
In other instances the text shows some wired behavior and the features don't move at all. Can be observed in the [UMD demo](http://teselagen.github.io/openVectorEditor/UMDDemo.html) too.

![grafik](https://user-images.githubusercontent.com/65481677/96191456-f8931880-0ef8-11eb-8030-a7e1fa18c102.png)

Is there a way to disable the rotate functionality i.e. hide the slider and arrows in the upper left corner? That would be good enough for me as a work around.

Cheers, Marcel

**Comment by tnrich** [comment]
@MarcelBolten that's an interesting bug you've found. I'll work on fixing that at some point. In the meantime I made the rotation optional in open-vector-editor@12.0.10. You should be able to pass `withRotateCircularView:false` to hide the circular view. 

```
const editor3 = window.createVectorEditor("createDomNodeForMe", {
       withRotateCircularView:false
        withPreviewMode: true,
        showMenuBar: true,
        editorName: "YetAnotherSequence"
      });
```

**Comment by tnrich** [comment]
I've made a new issue for the rotation weirdness you've found and will close this one in the meantime :) 

Let me know if you hit any other snags. 

Thomas
