### ISSUE TITLE
Menu dropdowns sometimes obscure other menu items

### ISSUE THREAD

**Issue by mjsteichen** [TeselaGen/openVectorEditor#670]
@tnrich

Firstly, open-vector-editor is freaking awesome. Thanks for sharing it on github! 🌈 

### Summary
If a menu is long enough to extend beyond the viewport, it shifts upward, such that it obscures other items in the menu. For example in this screenshot, if I hover over 'Edit" I am no longer able to see "View", "Tools", and "Help".
![image](https://user-images.githubusercontent.com/7410006/101545814-6e51b880-396d-11eb-8bd1-87e30dbc0066.png)

### How to repro
This is reproducible on [the demo](http://teselagen.github.io/openVectorEditor/#/Editor) if you zoom your browser in a bit and click the "File" menu and hover from left to right.

### Potential improvement
Add a vertical scrollbar if the menu will extend beyond the viewport, similar to how vscode and other apps handle this situation.
![image](https://user-images.githubusercontent.com/7410006/101546651-b9200000-396e-11eb-916c-c2761870eb75.png)

### Code
I dug around and noticed that you're using [blueprint PopOvers](https://github.com/TeselaGen/teselagen-react-components/blob/7565fe4cddbb5854a0e3fcdfb6d0442c627cdace/src/MenuBar/index.js#L253), which looks to support this: https://blueprintjs.com/docs/#core/components/popover. Popper, the library blueprint uses, has some properties themselves: https://blueprintjs.com/docs/#core/components/popover.modifiers 

In any case, this is definitely a nit-pick non-critical issue, but I thought I'd file it while I debug more and look into a patch/workaround.

**Comment by tnrich** [comment]
Hey @mjsteichen! Thanks for your interest in OVE! I've definitely noticed the overlay issue you bring up. I think the solution you suggest definitely sounds like the right way to handle it.

Let me know how it goes trying to find a solution for it. If you find one I'd be happy to incorporate it into the underlying components package (https://teselagen.github.io/teselagen-react-components/#/MenuBar https://github.com/TeselaGen/teselagen-react-components/blob/master/src/MenuBar/index.js#L253) 

Cheers!

**Comment by tnrich** [comment]
@mjsteichen any updates on this one? :)

**Comment by mjsteichen** [comment]
@tnrich Sorry for radio silence- have not had a chance to knock this out yet. Very busy at work and my personal life has been entirely consumed by raising a very energetic puppy 🐶

**Comment by tnrich** [comment]
@mjsteichen no worries I understand the struggle!

**Comment by tnrich** [comment]
Hey @mjsteichen and @marcelbolten

I finally got around to taking a look at this issue and think I was able to come up with a good fix (in the teselagen-react-components repo)

Here's what long menu scrollbars should look like now:
![image](https://user-images.githubusercontent.com/2730609/128781682-c0094d2b-8e6e-40be-ae34-ec43dd68219e.png)

**Comment by mjsteichen** [comment]
Awesome, that looks great. Thanks for taking a look and for the heads up.
