### ISSUE TITLE
Translation start in frames -2 and -3 are inverted.

### ISSUE THREAD

**Issue by kelmazouari** [TeselaGen/openVectorEditor#680]
@tnrich

Translation start in frames -2 and -3 are inverted
Frame -2:
![image](https://user-images.githubusercontent.com/10584220/106029591-8ae8b200-60cd-11eb-8fb5-3b55a082b919.png)

Frame -3
![image](https://user-images.githubusercontent.com/10584220/106029719-a784ea00-60cd-11eb-9ee2-5deaa9e4c2ee.png)

SnapGenes Frame -2
![image](https://user-images.githubusercontent.com/10584220/106030164-2aa64000-60ce-11eb-991e-f60dba1b1675.png)

Input genbank file:
[rev.txt](https://github.com/TeselaGen/openVectorEditor/files/5881989/rev.txt)

**Comment by tnrich** [comment]
Uh oh! Looks like a bug! I will need to dig into the source code to see where this issue is coming from. Good find!

**Comment by kelmazouari** [comment]
where can I find the translation module ? Is it part of OVE ?
Thanks

**Comment by tnrich** [comment]
@kelmazouari it would be in ve-sequence-utils

https://github.com/TeselaGen/ve-sequence-utils/blob/master/src/findOrfsInPlasmid.js

**Comment by tnrich** [comment]
@kelmazouari sorry I pointed you to the wrong code actually. The code I referenced is for finding open reading frames, not entire frame translations. Here is the frame translations code:  https://github.com/teselagen/openVectorEditor/blob/master/src/selectors/translationsSelector.js#L76

**Comment by tnrich** [comment]
@kelmazouari ok I think I've found the issue. I've pushed a fix out in v13.0.4. Want to try that version out and let me know if it is fixed for you? 

Here's a screenshot of the fix: 
![image](https://user-images.githubusercontent.com/2730609/106049544-13019400-609b-11eb-93b4-e5b6c20766db.png)

It should also include better linear vs circular support 😄

**Comment by kelmazouari** [comment]
Thanks @tnrich , It's fixed.

**Comment by kelmazouari** [comment]
Thanks @tnrich, it's fixed.
