### ISSUE TITLE
Same translation frame selected twice

### ISSUE THREAD

**Issue by kelmazouari** [TeselaGen/openVectorEditor#681]
@tnrich
OVE extracts the ORF from the CDS feature and displays the right translation. However, the frame is not checked in the Full Sequence Translation menu item. It is then possible to select the same frame twice.

![image](https://user-images.githubusercontent.com/10584220/106388584-795e1d80-63df-11eb-98c5-a462d8ba1406.png)

**Comment by tnrich** [comment]
@kelmazouari if I'm understanding correctly then the functionality you're seeing is by design. CDS-translated features the span the sequence as well as ORFs that span the entire sequence are treated separately from the frame translations.

**Comment by kelmazouari** [comment]
@tnrich 
Yes.

**Comment by kelmazouari** [comment]
This behavior could be useful in the case of displaying protein sequences with annotated features. So I will close this issue.
