### ISSUE TITLE
Notes section overflows the modal window

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#682]
@tnrich

If an annotation contains several notes, the data overflows the annotation modal window and scrolling doesn't work. With enough notes, the save button for edits to the annotation cannot be seen. This happened on firefox and chrome
Hopefully the screenshot is self explanatory. Let me know if you need more details/cannot reproduce
<img width="494" alt="Screen Shot 2021-02-01 at 4 22 48 PM" src="https://user-images.githubusercontent.com/1694026/106534975-0c638a00-64aa-11eb-90ef-24d5c83ac14e.png">

**Comment by tnrich** [comment]
@hplahar thanks! This should be fixed in open-vector-editor@13.0.9

**Comment by tnrich** [comment]
@hplahar an improved draggable/resizable dialog should have landed in open-vector-editor@13.0.10

The edit part/feature window should now do a better job at setting its initial size

Feel free to try it out at http://teselagen.github.io/openVectorEditor/#/Editor

**Comment by hplahar** [comment]
@tnrich : Looks good. Thanks for the quick turnaround
