### ISSUE TITLE
Tooltips being cut off in full screen OVE

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#689]
![image](https://user-images.githubusercontent.com/2730609/107286580-9f09a900-6a15-11eb-8db7-a986b9d8e0a9.png)

**Comment by tnrich** [comment]
To fix this, when in full screen mode we should disable scrolling on the window.body

**Comment by MarcelBolten** [comment]
@tnrich
Maybe an related issue: location of tooltips/options way below icon.
![image](https://user-images.githubusercontent.com/65481677/125576147-f3b586d3-95ef-4e3f-b715-0aa13aeb02de.png)
![image](https://user-images.githubusercontent.com/65481677/125576541-76af590f-b870-40fe-bd29-6cc662a93b66.png)


Setup: Using OVE within eLabFTW (example: https://demo.elabftw.net/experiments.php?mode=view&id=4480).  OVE enters full screen mode from preview mode. Location of tooltip/options seems to be related to preview mode location. Tested with Firefox and Edge.


![image](https://user-images.githubusercontent.com/65481677/125578772-26425aa5-feb2-49b4-8a79-29bc66ebd1b7.png)


Can also be reproduced on the umd demo (http://teselagen.github.io/openVectorEditor/UMDDemo.html) if `position: relative;
top: 100px;` are give to the body element.

**Comment by tnrich** [comment]
@MarcelBolten this looks like it is an underlying issue with either blueprintjs or the popper library that blueprint uses. We'll probably need to come up with a minimal reproduction of the error and air this issue there.

**Comment by MarcelBolten** [comment]
@tnrich could it be the same issue as #436 and wrapping the Tooltips in a div will solve it?
Tooltips:
https://github.com/TeselaGen/openVectorEditor/blob/f031616387729c8851fded8c7b8035635ff72f15/src/ToolBar/ToolbarItem.js#L68-L69
https://github.com/TeselaGen/openVectorEditor/blob/f031616387729c8851fded8c7b8035635ff72f15/src/ToolBar/ToolbarItem.js#L94-L95
fix via #436
https://github.com/TeselaGen/openVectorEditor/blob/f031616387729c8851fded8c7b8035635ff72f15/src/Editor/index.js#L651-L658
Maybe it holds true for popovers too (#670)?

**Comment by tnrich** [comment]
@MarcelBolten I just tried that out and wrapping the tooltip/popover with a div doesn't seem to fix the issue..

**Comment by MarcelBolten** [comment]
Hi @tnrich,

I looked a bit into the issue and tried to migrate from popover (deprecated since @blueprintjs/core v3.38.0) to [popover2](https://blueprintjs.com/docs/#popover2-package).
This seems to do the trick and the popovers/tooltips find their expected location. But it also breaks some features.
I never worked with React/Redux and Teselagen's Open Source Vector Editor Components along with the TeselaGen React Components are very extensive. I could provide a PR with my changes if that is of any interest and maybe with some guidance can fix the broken features.

Cheers,
Marcel

**Comment by tnrich** [comment]
> But it also breaks some features. 

Which features does it break?

**Comment by MarcelBolten** [comment]
@tnrich
> Which features does it break?

There are a few cypress tests that first failed after migration to popover2 (openVectorEditor and teselagen-react-components) but most of them I could make work again.
However, the FindBar is still not working as intended:
- It kind of works but after the first character is typed the input element is not responding anymore but the AnnotationSearchMatchComp shows some entries. I have to reload the page.
- Pasting a string that has no match, the input is editable.
- Pasting a DNA stretch with a match, the tool will find it and the input is editable.
- But if the pasted string matches something that can be listed by the AnnotationSearchMatchComp it freezes.

Do you have an idea what could be the problem?
Do you consider a migration to popover2 at all?

Cheers,
Marcel

**Comment by tnrich** [comment]
Hey @MarcelBolten 

>Do you consider a migration to popover2 at all?
Yep we will probably migrate to popover2 when we upgrade to blueprint 4 (which hasn't been released yet). This will be a large change to make and will probably not happen for some time however.

**Comment by tnrich** [comment]
Closing this as stale
