### ISSUE TITLE
[render C, L] - display / toggle features

### ISSUE THREAD

**Issue by salafrance** [TeselaGen/openVectorEditor#69]
display and hide features in circular and linear views

**Comment by tnrich** [comment]
Question about this: should we allow for different toggling across different views? Like being able to see features in the circular view but not in the row view?

**Comment by salafrance** [comment]
at least the way the old VE works, you only see one view or the other at a time, so toggle just works on whatever's showing currently.

**Comment by tnrich** [comment]
Hmm okay. I think that to begin with we can have the toggles apply to all views at once. If we want a finer granularity we can add that in later.
