### ISSUE TITLE
make GC % user toggle-able

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#690]
And persist the user preference to local-storage!

**Comment by tnrich** [comment]
@ericsturman a heads up that I am going to intentionally break how this feature was working as a new major release. Instead of the previous iteration where showGCContent was being passed in as an implementer-controlled prop, I am changing it to be a local-storage persisted view option:

![image](https://user-images.githubusercontent.com/2730609/107560793-a86c5000-6b92-11eb-97b3-bfaf140b1b39.png)

This gives more flexibility to the user to either show or hide the option. To allow for compatibility with the current defaults, this option won't be enabled default. But (!), I've added an example of how to enable it by default for your users. To do so you'll need to run the following code on window load:

```
window.localStorage.setItem("showGCContentByDefault", true)
```
(note this will still allow the user to override that preference locally).

Please let me know if this will be an ok change for you or if you need additional help. 

Cheers,
Thomas

**Comment by ericsturman** [comment]
@tnrich this should be fine... We are a little behind on OVE updates but this will be good to know when we do the update, hopefully soon... thank you for letting me know.

**Comment by tnrich** [comment]
@ericsturman the info I provided above is out of date so I deleted it. To keep the functionality you currently have, instead of passing `showGCContent` like you currently do, instead you'll need to pass 

```
showGCContentByDefault={true}
```

to the <Editor/>

**Comment by tnrich** [comment]
@ericsturman closing this as it has been implemented.
