### ISSUE TITLE
Restriction enzymes displayed on protein sequence

### ISSUE THREAD

**Issue by kelmazouari** [TeselaGen/openVectorEditor#714]
@tnrich
Hello,
Genpet protein sequence is correctly rendered.  However 'Show All' displays restriction enzymes on top of protein sequence.

**Comment by tnrich** [comment]
@kelmazouari can you please send a screenshot (or video) of this? I'm not seeing it on the demo page for a protein sequence: 

![image](https://user-images.githubusercontent.com/2730609/116118369-11337680-a672-11eb-8651-3ecbf7d1263e.png)

Thanks! Pushing a possible fix for you anyways but I'm worried that it won't work if your protein is not actually being displayed in isProtein mode. It should have a little "AAs" text below the name: 
![image](https://user-images.githubusercontent.com/2730609/116119264-17762280-a673-11eb-88cc-ba738acc37e9.png)

does it have that? 

Also lemme know if  v16.1.27 fixes the problem for you.

**Comment by kelmazouari** [comment]
![image](https://user-images.githubusercontent.com/10584220/116130326-5fc12f00-a6cb-11eb-8f01-d9d6e90abf53.png)

Extrenal Label not activated.
I tried with window.localStorage.setItem("externalLabels", true); no succees

Thanks

**Comment by tnrich** [comment]
@kelmazouari I assume you were meaning to respond to the thread in the other issue: https://github.com/TeselaGen/openVectorEditor/issues/715

**Comment by kelmazouari** [comment]
Thanks @tnrich 
isProtein was false. Sorry.
