### ISSUE TITLE
editor externalLabel=true not working

### ISSUE THREAD

**Issue by kelmazouari** [TeselaGen/openVectorEditor#715]
@tnrich
Hi,
Show Visibility Options > Labels > External Labels  display external labels.
Setting editor externalLabels=true doesn't display external labels.
Any suggestion how to set externalLabels default to true ?
Thanks

**Comment by tnrich** [comment]
Hey @kelmazouari sorry for the delayed response. You're trying to make it so external labels are always shown by default for a user? You can't force them to always be displayed but you can make it so it is on by default by controlling the localstorage value that toggles them on/off. 

Somewhere in your initialization code you can call
```
window.localStorage.setItem("externalLabels", true);
```
it might make sense to only do this if the value is unset so you could check for it first and only set it if it hasn't yet been set. 

Lemme know if this solves the issue for you

**Comment by tnrich** [comment]
From @kelmazouari (he posted in the wrong thread):
![image](https://user-images.githubusercontent.com/10584220/116130326-5fc12f00-a6cb-11eb-8f01-d9d6e90abf53.png)

Extrenal Label not activated.
I tried with window.localStorage.setItem("externalLabels", true); no succees

Thanks

**Comment by tnrich** [comment]
@kelmazouari I moved your comment above to the correct thread. That said I can assure you calling
```
window.localStorage.setItem("externalLabels", true)
``` 

works. 

Maybe try setting the "onlyShowLabelsThatDoNotFit" option to false to better be able to see the changes: 
![image](https://user-images.githubusercontent.com/2730609/116134215-827c2500-a684-11eb-855d-d259f4a5af2b.png)

Here's a video of me first setting externalLabels to false and then to true and reloading the demo page:

https://user-images.githubusercontent.com/2730609/116134254-8ad46000-a684-11eb-85b3-49c77ae8c00e.mov

**Comment by kelmazouari** [comment]
Thanks @tnrich,
External labels still not activated by default.
Could you please test it with this gp file. Thanks
[prot.txt](https://github.com/TeselaGen/openVectorEditor/files/6379650/prot.txt)

**Comment by tnrich** [comment]
@kelmazouari maybe dig into how localstorage works a bit and try some things out yourself. Your screenshot above was of the initial demo sequence. Does it work for you with the demo sequence? 

I can assure you that the feature is working properly including with your gp sequence: 

![image](https://user-images.githubusercontent.com/2730609/116156948-05ab7400-a6a1-11eb-9e74-f7f2af2b134c.png)

Not sure I can help much more beyond this..

**Comment by kelmazouari** [comment]
Hi @tnrich 
I had an issue with the update. It's fixed and it's woking. Many thanks
