### ISSUE TITLE
File import from URL

### ISSUE THREAD

**Issue by diegusleik** [TeselaGen/openVectorEditor#728]
@tnrich Hi. Thanks for this great tool.
I wonder if it is possible to programmatically import (and parse) a file from a URL. Thanks in advance.

**Comment by MarcelBolten** [comment]
Hi @diegusleik ,

Not sure if you found a way to do it but please have a look at https://github.com/elabftw/elabftw/blob/0bf0a06d3a5fa5cf8d7323f758d175fae3ada28a/src/ts/ove.ts#L221 for one possible way.

Cheers,
Marcel

**Comment by tnrich** [comment]
@diegusleik I can confirm that what @MarcelBolten suggested should indeed work. Just to break down what @MarcelBolten is doing is that they're using the bio-parsers npm package (https://www.npmjs.com/package/bio-parsers) to parse out a genbank/fasta/snapgene/ab1 file from whatever URL into the JSON format that OVE understands.

**Comment by diegusleik** [comment]
Thank you very much @MarcelBolten and @tnrich ! It works really fine.
