### ISSUE TITLE
Tables in Properties tab are severely truncated

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#729]
@tnrich,

The tables found in the Properties tab (General, Features, Parts, etc.) are all truncated. This requires scrolling through a lot of content to find the row of interest. For example, the screenshot below shows a truncated table for the Features of an arbitrary sequence. 88 features are selected, but I can only view 12 or 13 of them. There's so much more screen real estate below, so I would expect the table display to be much bigger.

![image](https://user-images.githubusercontent.com/17152701/120047596-f8a4dc00-bfe2-11eb-9900-0d24997b7db5.png)

**Comment by tnrich** [comment]
@gmcarthuriv yeah those sizings were a little tricky to get right and it looks like they're still not perfect. I'll play around with them and see if I can't fix em

**Comment by tnrich** [comment]
@gmcarthuriv this should be fixed in open-vector-editor@16.3.5
