### ISSUE TITLE
Description can be edited in readOnly mode

### ISSUE THREAD

**Issue by MarcelBolten** [TeselaGen/openVectorEditor#746]
Hi @tnrich,

If the readOnly mode is active it is possible to click the edit button under Properties -> General -> Description and edit it.

![image](https://user-images.githubusercontent.com/65481677/125697580-637c7f56-bf03-4607-9363-5691111129ca.png)

Is this a feature or a bug? It is confusing for me.
Cheers

**Comment by tnrich** [comment]
Definitely a bug. Thanks for reporting this @MarcelBolten 

Fixed in open-vector-editor@16.3.4
