### ISSUE TITLE
Are the font files required?

### ISSUE THREAD

**Issue by flange-ipb** [TeselaGen/openVectorEditor#749]
@tnrich

Hello,
I was wondering if any of OVE's functions become reduced if it is not able to load the font files. Do I really need them or is it enough to include only main.css and open-vector-editor.min.js?

Why do I care about the fonts?
* My laziness: I'd like to include OVE in a JavaEE web component project and I don't want to use npm (executing npm via Maven is a mess). I typically prefer downloading single files from [unpkg.com](https://unpkg.com/browse/open-vector-editor@16.3.4/umd/) in my build pipeline - and there are a lot of files ;)
* Licenses (n.b.: I'm not a lawyer):
  * icons-* come from the `@blueprintjs` dependency, which is [Apache 2.0](https://github.com/palantir/blueprint/blob/develop/packages/icons/LICENSE) licensed ... that's OK
  * ubuntu-mono-latin* come from the `typeface-ubuntu-mono` ([version 0.0.54](https://unpkg.com/browse/typeface-ubuntu-mono@0.0.54/)) dependency. To me, this one has an unclear license situation and I'm not willing to include them in my project. 

More about the license topic:
* [Wikipedia page about the Ubuntu fonts](https://en.wikipedia.org/wiki/Ubuntu_(typeface)#Ubuntu_Font_Licence)
* [The npm page of typeface-ubuntu-mono](https://www.npmjs.com/package/typeface-ubuntu-mono/v/0.0.54) claims to use a MIT license, but there is actually no clear hint to that in the [linked GitHub repo](https://github.com/KyleAMathews/typefaces/tree/v0.0.58).
* For me it is not obvious which version of Ubuntu Mono was used to create this package. The build process [seems to rely on local files on the developer's computer](https://github.com/KyleAMathews/typefaces/blob/v0.0.58/packages/ubuntu-mono/index.css) and is not transparent at all.

Best regards,
Frank

**Comment by tnrich** [comment]
@flange-ipb You should be fine not adding on any fonts. The monospace font styles have fallbacks to Lucida Console and Monaco.

**Comment by flange-ipb** [comment]
Very good! Thanks for clarification.

**Comment by flange-ipb** [comment]
Thanks to commit [93a491f95819c681df425ded7df619bd3f51c9d5](https://github.com/TeselaGen/openVectorEditor/commit/93a491f95819c681df425ded7df619bd3f51c9d5) there is now transparency about where to get Ubuntu Mono from and which version it is. It traces back to [fontsource/ubuntu-mono](https://github.com/fontsource/fontsource/tree/main/packages/ubuntu-mono) and it seems to use a version that is licensed under the [Ubuntu Font Licence](https://ubuntu.com/legal/font-licence). I know I'm the spoilsport again, but unfortunately, it fails to comply to the license terms, because it does not contain the license file.

**Comment by tnrich** [comment]
@flange-ipb what should be done to get the license file? Does it need to be added to this repo?

**Comment by flange-ipb** [comment]
Hi @tnrich!
[FontDrop](https://fontdrop.info/) told me that v0.80 of Ubuntu Mono is delivered with OVE, i.e. the Ubuntu Font License applies. You can find the license file [here](https://assets.ubuntu.com/v1/81e5605d-ubuntu-font-licence-1.0.txt) (that's a link from the previously referenced [license page](https://ubuntu.com/legal/font-licence)).
In my opinion, the license file should at least appear in the delivered [artifact](https://unpkg.com/browse/open-vector-editor@16.3.20/), probably in the _umd_ directory or in a separate license directory. The repo itself does not contain the font files. Thus, it may not be necessary to add the license file directly to the repo, instead the build pipeline could just download it.
