### ISSUE TITLE
updateEditor: Circularity of sequence is not taken into account

### ISSUE THREAD

**Issue by flange-ipb** [TeselaGen/openVectorEditor#750]
@tnrich

Hi again!
This concerns the second example in the [UMD Demo](https://teselagen.github.io/openVectorEditor/UMDDemo.html). The sequence that is inserted via updateEditor(...) is not circular, but after opening the editor the circular map is still selected. I would expect that it opens with the linear map.

Best regards,
Frank

**Comment by tnrich** [comment]
@flange-ipb the implementer has full control of which panels are shown and in which postions. See panelsShown here for more details on how to control that: https://github.com/TeselaGen/openVectorEditor#editorstate

**Comment by flange-ipb** [comment]
Hello @tnrich
Very good! Thanks for pointing me to `panelsShown`. I was actually wondering why this field consists of nested arrays and learned that this controls the left and right panels (or even more than two panels). This should be documented. ;)

Another thing: I saw the button "Focus Linear View" in the [universal demo](https://teselagen.github.io/openVectorEditor/#/Editor). How can this action be executed?

**Comment by tnrich** [comment]
If you click the info icon next to the "Focus Linear View" button you should see:
![image](https://user-images.githubusercontent.com/2730609/127048867-8156eae7-9e69-440e-ba0f-6cee2538b437.png)

**Comment by tnrich** [comment]
@flange-ipb bump :)
