### ISSUE TITLE
Ability to toggle labels for assembly annotations

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#757]
@tnrich,

Currently, labels can be turned on and off for for Features, Parts and Restriction Sites. However, it's often desirable to toggle Assembly Piece and Part Lineage annotations.

![image](https://user-images.githubusercontent.com/17152701/127893871-6979f559-bf2e-461e-8769-9ab8b54f4f83.png)

**Comment by gmcarthuriv** [comment]
Oh - also meant to include Warnings (to be complete).

**Comment by tnrich** [comment]
Released in open-vector-editor@16.3.11 @gmcarthuriv
