### ISSUE TITLE
Ability to change/increase number of labels displayed for assembly annotations

### ISSUE THREAD

**Issue by gmcarthuriv** [TeselaGen/openVectorEditor#758]
@tnrich,

Currently, limits on the number of displayed labels for Features, Parts and Restriction Sites can be changed/increased. It would be useful to add this functionality for labels of Assembly Piece and Part Lineage annotations.

![image](https://user-images.githubusercontent.com/17152701/127894269-b1596d93-3a08-439a-b512-5c9156ebf866.png)

**Comment by gmcarthuriv** [comment]
Oh - also meant to include Warnings (to be complete).

**Comment by tnrich** [comment]
Released in open-vector-editor@16.3.11 @gmcarthuriv
