### ISSUE TITLE
UI Bug - Shift in Highlighting Mismatches and Selection when Browser Zoom is not 100%

### ISSUE THREAD

**Issue by FadiBakoura** [TeselaGen/openVectorEditor#761]
@tnrich

There is a problem with the alignment viewer, there is a shift in highlighting mismatches and selection. This UI artifact happens only when the browser zoom is not 100%.

Kindly find below two images:
First image: when the browser zoom is 100%  (No artifact in below image)  
![image](https://user-images.githubusercontent.com/8144604/130600748-8d6d70ba-bd4e-41d2-84de-46fd3c3cff78.png)

Second image: when  the browser zoom is 125%  (There is artifact in below image)  
![image](https://user-images.githubusercontent.com/8144604/130600685-2defe609-06c9-4ab7-a195-54a7ffb07fd3.png)

Note,  the images taken from a 15.6 inch full hd laptop display

Thanks

**Comment by tnrich** [comment]
@FadiBakoura thanks for reporting this! I'll see if it's an easy fix

**Comment by tnrich** [comment]
@FadiBakoura what kind of computer are you on and what browser are you using? 

I'm not able to reproduce this rendering issue on my mac on chrome: 

Browser zoom at 125%:
![image](https://user-images.githubusercontent.com/2730609/130658894-54be5cee-4c0e-42f2-9346-e04e554808a7.png)

**Comment by FadiBakoura** [comment]
> what kind of computer are you on and what browser are you using?

Asus TUF gaming - Windows 10 - Chrome: Version 92.0.4515.159 (Official Build) (64-bit) 

Maybe the Screen resolution plays a role here, can u test different zoom levels?

**Comment by FadiBakoura** [comment]
That's strange that it's working on your ends.

The below image is from my coworker laptop:

![image](https://user-images.githubusercontent.com/8144604/131211529-c761f878-5a8b-4b4c-9b5a-70d78aaa4ada.png)

As you can see in the above image, at index 1310 (the mismatch right before it), there is a noticeable shift.

**Comment by tnrich** [comment]
Closing this as stale
