### ISSUE TITLE
Plugin  Documentation

### ISSUE THREAD

**Issue by tonyjiafan** [TeselaGen/openVectorEditor#767]
**please help me!**

Now I want to integrate this awesome plugin into my VUE project.
Is there a VUE version of this plugin?
If not, what is a good way for me to use this plugin in the VUE project? I need a more comprehensive API document corresponding to this plugin.
If you see this message, please help me.
thank you very much!

**I need more comprehensive documentation thanks！**

My email address: tonyjiafan@gmail.com

**Comment by tnrich** [comment]
Hey @tonyjiafan there is a standalone demo of OVE here http://teselagen.github.io/openVectorEditor/#/Standalone

You'll probably need to do something like that if you'd like to embed it in a non-react application. The standalone version uses a UMD build of the editor. You can read about the UMD build in the readme: 
https://github.com/TeselaGen/openVectorEditor#flavors-of-use-aka-embedded-in-the-editor-vs-standalone-and-umd-vs-react

Here's a link to the UMD standalone demo src code: 
https://github.com/TeselaGen/openVectorEditor/blob/master/demo/src/StandaloneDemo.js

**Comment by tonyjiafan** [comment]
thank you very much!
