### ISSUE TITLE
Remove Cypress key

### ISSUE THREAD

**Issue by rpavez** [TeselaGen/openVectorEditor#768]
Hi @tnrich hope you're doing great, this is a great project that I actually follow. Just would like to suggest as explained here https://docs.cypress.io/guides/dashboard/projects#Record-key its probably better not to expose Cypress Recording key seen here https://github.com/TeselaGen/openVectorEditor/blob/b26a2a7c0a670c62f4c7fd631984a743d0eac86c/package.json#L28 probably it's better to regenerate and use as an env variable.

**Comment by tnrich** [comment]
Hmm interesting thanks for the heads up @rpavez !! It is good to hear from you! 

I'll need to look into this further. Hope you're doing well ☺️
