### ISSUE TITLE
.ab1 alignment

### ISSUE THREAD

**Issue by kelmazouari** [TeselaGen/openVectorEditor#770]
@tnrich

Hi @tnrich ,
I can't create Pairwise Alignment for two .ab1 files. 
![image](https://user-images.githubusercontent.com/10584220/133558989-4af9e973-b2d5-49ca-87ab-b0feb0bc47ec.png)

Alignment is not displayed.
![image](https://user-images.githubusercontent.com/10584220/133559097-abf729ce-cb40-46de-9120-309fe4337946.png)

Thanks

**Comment by tnrich** [comment]
Hmm.. seems like a bit of an issue.. Can you please upload a zip file with the .ab1 files in question? Thanks!

**Comment by kelmazouari** [comment]
[ab1.zip](https://github.com/TeselaGen/openVectorEditor/files/7189363/ab1.zip)

**Comment by diegusleik** [comment]
Hey @kelmazouari,

I'm on a similar issue now. From [this post](https://github.com/TeselaGen/openVectorEditor/issues/712), I know that:

> Since OVE is just a visualization library, it doesn't provide any alignment tool out of the box, you'll need to hook it up to your own favorite alignment tool in order to get the actual alignment data you'd like to visualize

Do you have an alignment tool connected to your OVE? Which one? What is your response object?

**Comment by kelmazouari** [comment]
Hi @diegusleik ,
I am actually looking for ab1 file viewer/editor (screenshot below)

![image](https://user-images.githubusercontent.com/10584220/134198006-c3716fac-a762-4573-b2ab-46ba5ad97023.png)

**Comment by diegusleik** [comment]
Oh, sorry, I meant the alignment, not the ab1 file

**Comment by tnrich** [comment]
@kelmazouari @diegusleik I've started working on a way to overlay ab1 files on top of the sequence row view. Here's a preview of what it will look like: 

![image](https://user-images.githubusercontent.com/2730609/137361158-e1b67257-f268-4d50-9611-fadc70e82f18.png)

**Comment by kelmazouari** [comment]
@tnrich Excellent, thanks.

**Comment by tnrich** [comment]
A first version of this has been released in v17.0.0

You can play with it here: http://teselagen.github.io/openVectorEditor/#/Editor?showDemoOptions=false&searchInput=&chromatogramExample=true

**Comment by kelmazouari** [comment]
Thanks Thomas ;)


 <http://www.abnomx.com/>	Khalil El Mazouari, PhD
Founder, Managing Director
AbnomX <https://www.abnomx.com/> bv
Ghent Area, Belgium
***@***.*** ***@***.***>


Confidentiality Notice: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution of this information is prohibited, and may be punishable by law. If this was sent to you in error, please notify the sender by reply e-mail and destroy all copies of the original message. Please consider the environment before printing this e-mail.

**Comment by kelmazouari** [comment]
Thanks Thomas, Excellent job.

**Comment by tnrich** [comment]
Going to close this for now. Feel free to open any new issues!
