### ISSUE TITLE
chromatogramData: baseCalls not saved

### ISSUE THREAD

**Issue by kelmazouari** [TeselaGen/openVectorEditor#799]
@tnrich

Hi Thomas,

When editing and saving chromatogramData, the sequence is saved. However, baseCalls is not always saved or not saved correctly.
For example: when I changed the first C -> A and Save, the sequence is OK, but baseCalls keeps the old value. It is also not always working for deletion.

Sometimes it saves multiple insertions as String:
![image](https://user-images.githubusercontent.com/10584220/146635995-6474fa16-e3b4-471c-a310-51a8441dfba3.png)

Attached test.ab1 file. You can reproduce by editing the first bases.
Thanks in advance for your help.

[test.ab1.zip](https://github.com/TeselaGen/openVectorEditor/files/7739026/test.ab1.zip)

**Comment by tnrich** [comment]
Hey @kelmazouari I've fixed the issue you're seeing (also maybe just don't rely on base calls but instead use the sequenceData.sequence as the underlying source of truth. 

The updated version is 17.0.12
