### ISSUE TITLE
Any plan to support react17

### ISSUE THREAD

**Issue by weasteam** [TeselaGen/openVectorEditor#800]
@tnrich
Just want to check if react17 is going to be supported.

**Comment by tnrich** [comment]
Yep planning on updating soon!

**Comment by tnrich** [comment]
Published in open-vector-editor@17.1.4

**Comment by weasteam** [comment]
that is fast, thanks

**Comment by tnrich** [comment]
No problem! If you feel like it want to let us know if you're using OVE in your project: https://github.com/TeselaGen/openVectorEditor/issues/776 ?

Thanks!
