### ISSUE TITLE
Missing file in released npm package.

### ISSUE THREAD

**Issue by sunm19810-pki** [TeselaGen/openVectorEditor#801]
Hi @tnrich

I found the released package of open-vector-editor was not complete, such as the file src/utils/withStore.js is not included in the released npm package.

**Comment by tnrich** [comment]
Uh oh I'll look further into this today. Thanks!

**Comment by tnrich** [comment]
Thanks for the heads up.. looks like it is an issue with the `in-publish` package I use..

**Comment by tnrich** [comment]
Fixed this by no longer using in-publish which is no longer needed since npm v4
