### ISSUE TITLE
Feature requests Export/Copy of Expected Digest Image

### ISSUE THREAD

**Issue by jobabi** [TeselaGen/openVectorEditor#810]
Thanks for developing OVE. During the past I was using serial cloner which is unfortunately not anymore running on newer MAC OS system. Currently we are using OVE with eLABFTW, which is really useful. 

I have two feature request to further enhance the code

1)   I would like to change the DNA ladder so that I can choose the appropriate ladder for my experiments
    (The three ladders provided do not fit mine in the lab). If there would be a possibility to enter the band sizes of the desired ladder that would be nice

2)  The plasmid viewer /OVE shows you a nice picture of the expected digest. I would like to transfer this picture / table into the eLABFTW lab book, so that I can directly compare the expected pattern with the real experiment. If the the picture / table could be copied / exported that would helpful here.

Thank you for considering this suggestions

Jochen

@tnrich

**Comment by tnrich** [comment]
Hey @jobabi those both sound like pretty reasonable suggestions. Can you make a separate ticket for both of them and spec out how you'd like the user interface to be for both use cases? That would be a great first step I think. 

Also are you interested in leading the code development of either of these features if I provided a roadmap of how I thought they should be implemented once we've settled on a UI? No pressure if that isn't something you're comfortable with but thought I'd ask.

Thanks!
Thomas

**Comment by jobabi** [comment]
I have  splitted the two features. The request for the DNA Ladder can be found here:


For the export of the virtual DNA Digest picture, I think it would fine if one can use a right mouse click to open a small window that allows to save the picture. Similar to any Picture if you browse the internet. I assume that if the browser would be able to recognize the DNA Digest as a picture this would be done ?
(Unfortunately, I have a reasonable experience with DNA Plasmid stuff but none for coding.....)

**Comment by MarcelBolten** [comment]
Hi @tnrich

Maybe there could be an additional entry >Save to File< in the already existing context menu of the digest info which would allow users to download/export the selected data/the entire table as a csv or tsv file.
![image](https://user-images.githubusercontent.com/65481677/154787617-42c203a6-60b8-402e-9272-aca2337d4e1e.png)
The generated file could alternatively be transferred to a callback function which could be provide via `editorProps`, similar to `generatePng=true` and the `onSave` handler.

Likewise for the virtual digest, either a context menu >Save as Image< or an additional button would be nice. Here again, the file should be transferred to a callback function.

Cheers,
Marcel

**Comment by tnrich** [comment]
@jobabi I'm adding a copy to clipboard option here: 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/2730609/155819329-3a058ead-d8fc-40e1-bb6e-1e8023599d73.png">

Here's the pasted image: 

![image](https://user-images.githubusercontent.com/2730609/155819338-6824f91c-7c61-46a2-95bd-82a48a222146.png)

**Comment by tnrich** [comment]
@MarcelBolten I've added the ability to copy any datatable to the clipboard as a TSV (tab separated values): 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/2730609/156860581-99db7807-9166-4416-9701-6370678604db.png">

**Comment by tnrich** [comment]
Going to close but feel free to reopen if I missed something

**Comment by jobabi** [comment]
Thanks for adding my suggestions. I appreciate that. 

Copying row or table worked pretty fine in the demo. However, the option "copy cell" was not working in my hands.
More useful from my side would be the option to copy a column. I guess for everybody interested in Plasmid  digest the column with the "length" sorted form biggest to smallest fragments is the most important information.

The option to copy the picture is not working for me. I get the message back, that it was copied into the clipboard, but nothing is happening, when I try to paste it .

(My System: Firefox on MacOS 10.14.6)

**Comment by tnrich** [comment]
Hey @jobabi good idea with the column copy, I can add that as well as fix the cell copy. 

As for the copy image to clipboard it looks like Firefox does not support the ClipboardItem api I used to implement this feature - https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#browser_compatibility 

Not sure what to do about this as the other copy image solutions don't look great. I probably will not fix this on my end and wait for firefox to fix their ClipboardItem api and continue to display a warning to the user like so if the copy fails: 

<img width="646" alt="image" src="https://user-images.githubusercontent.com/2730609/157077133-dbbc6e18-eaf3-48b5-9030-40040e077c3d.png">

Did you not see this warning?

**Comment by tnrich** [comment]
@MarcelBolten  @jobabi as for copying the cell, that seems to be working for me. Can you send a short gif of that functionality not working for you? 

When copying the column, would you want the column header included or not?

**Comment by jobabi** [comment]
My Firefox (and Safari) which is having this problem is running on MacOS.
I didn´t find anything in the preferences to change.

**Comment by MarcelBolten** [comment]
> I didn´t find anything in the preferences to change. 

It is not accessible by the "preferences" menu but via [The Configuration Editor (about:config page)](https://support.mozilla.org/en-US/kb/about-config-editor-firefox).

**Comment by jobabi** [comment]
I changed that but still the clipboard is empty

**Comment by tnrich** [comment]
@jobabi is it giving you a success message?: 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/2730609/158418294-e3256ee0-f93c-401b-88bf-4226fe146e6b.png">

Or is it giving you an error message? 

If you're getting a success message, are you sure you're pasting it into a location that accepts clipboard images? That could also be the issue. You should also be able to paste screenshots directly in there by pressing `cmd+shift+ctrl+4`, taking a screenshot, and `cmd+v` pasting it in.  Also, try pasting the copied image in here. 

Let me know,
Thomas

**Comment by jobabi** [comment]
I receive the success message, but the clipboard just contains the previous content.
I tried to paste in various graphic and other software without success because the clipboard does not contain the image.
Screenshot is working, but copy paste would be easier to use

**Comment by tnrich** [comment]
@jobabi I think I may have figured out what was going wrong here. The copy image functionality requires that the site be secure (served over https) which the OVE demo page was not. I've updated the demo page to be served over https and also updated the code to hide the copy option if in an unsecure environment.

Let me know if the updated site solves it for you.

**Comment by jobabi** [comment]
Yes, no it is working. Thank you very much for your patient support in this question.
