### ISSUE TITLE
Feature requests - Custom DNA ladders

### ISSUE THREAD

**Issue by jobabi** [TeselaGen/openVectorEditor#811]
Hi, this is a new request for integration an option to adjust the DNA ladder.

I suggest to integrate this in the "virtual  digest" menu. When opening a new digest you get two sub menu´s "Virtual digest" showing the picture and "digest info" showing a table with detailed infos. Maybe one can add here a menu called "DNA ladder" that provide a list (or table) where you add / remove a individual DNA Ladder and enter the sizes of the DNA fragments of your individual ladder. 
(Alternatively, one can have side by side with the ladder drop down window a  called "manage ladder" )
 
![Screenshot 2022-02-18 at 08 52 14](https://user-images.githubusercontent.com/66642211/154641091-379f6fc5-5af4-4d0b-992f-9d0fa07b1290.png)

@tnrich

**Comment by jobabi** [comment]
Here is such an option from "Serial cloner"
<img width="584" alt="Screenshot 2022-02-18 at 08 55 21" src="https://user-images.githubusercontent.com/66642211/154641382-a1f03ba4-2310-4fa3-afc1-42baf0f5b62d.png">

Here you have even the option to have normal and sick marker bands, that would the superior option :-)

**Comment by tnrich** [comment]
@jobabi I'm adding a copy to clipboard option here: 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/2730609/155819329-3a058ead-d8fc-40e1-bb6e-1e8023599d73.png">

Here's the pasted image: 

![image](https://user-images.githubusercontent.com/2730609/155819338-6824f91c-7c61-46a2-95bd-82a48a222146.png)

**Comment by tnrich** [comment]
Hey @jobabi I've added a first pass of adding a custom ladder. Let me know if it works for you and if the UI makes sense. You can try it here: 

http://teselagen.github.io/openVectorEditor/#/Editor?searchInput=diges&focusDigestTool=true

**Comment by tnrich** [comment]
@jobabi let me know if the above changes will work for you. Thanks!

**Comment by jobabi** [comment]
HI tnrich, the changes worked fine for me in the demo. Thank you for your help

Jochen
