### ISSUE TITLE
Long sequence names being cut off

### ISSUE THREAD

**Issue by mfero** [TeselaGen/openVectorEditor#813]
@tnrich long sequence names are being cut-off, no tool tip to help out.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/7561861/157870029-bf0fefea-8cfb-428c-9b28-9f36ac8b127e.png">

**Comment by tnrich** [comment]
There was already a hover title on the name, but I updated it to have a nice little ellipsis: 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/2730609/158070127-9c90fed3-9b63-4d96-aa80-cd7c95e09eb3.png">

You can see that here: http://teselagen.github.io/openVectorEditor/#/Editor?longSequenceName=true 

Let me know if this solves your issue.

**Comment by mfero** [comment]
perfect. thanks!
