### ISSUE TITLE
Degenerated oligo/sequence binding improvement

### ISSUE THREAD

**Issue by hcdepaoli** [TeselaGen/openVectorEditor#817]
When entering oligo sequences with degenerated bases, it would be nice to have a savvy distinction between the universal base pairs (e.g., R should be a match for A or G). Currently, oligos with degenerated bases are shown in red regardless of binding specificity.

One possible output could be to show the oligo bp, which is traditionally shown in black, to be in red if it's degenerated+mismatch, or in blue if it's degenerated+match (e.g., R input pairing an A would be blue, but pairing a C would be red). N would always be blue.

@tnrich

**Comment by tnrich** [comment]
@hcdepaoli sounds like an elegant solution!

**Comment by tnrich** [comment]
This should land in OVE v17.5.3

**Comment by hcdepaoli** [comment]
Works really nice! Thank you, lovely addition!
