### ISSUE TITLE
scan for features

### ISSUE THREAD

**Issue by jobabi** [TeselaGen/openVectorEditor#825]
It would be cool to have a (Sequence) database of important features and to include a scan option for these features.

E.g. if you have a new plasmids without feature annotations, you may press the scan for feature button to search for features (from a database like the DMA Ladders?) and marked them in the sequence map. Ideally this database could be expanded like adding a new DNA ladder.

Thank you & best wishes

Jochen 

@tnrich

**Comment by MarcelBolten** [comment]
Hi @jobabi 

If you are used to python there is https://github.com/barricklab/pLannotate which does the trick but of course if such a feature would be included in OVE that would make the workflow easier.

**Comment by tnrich** [comment]
@MarcelBolten  @jobabi there is actually an auto-annotate feature "add-on" to OVE that sounds a lot like what you're wanting: 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2730609/173877282-3366c099-948d-43a9-bc1e-64cd51a5ac3d.png">

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/2730609/173877351-ed011814-cc95-46c5-872b-54f22a12d8f6.png">

You can try that functionality out here - https://teselagen.github.io/openVectorEditor/#/Editor?searchInput=autoano&withAutoAnnotateAddon=true&withGetCustomAutoAnnotateList=true

**Comment by MarcelBolten** [comment]
Nice add-on. It does what I would expect. For eLabFTW there is no plan to add any edit functionality soon. But maybe in the future.

**Comment by jobabi** [comment]
Thank you for the hint. I did not see the "autoAnnotateAddon". That is pretty cool and that what I was looking for.
