### ISSUE TITLE
Error parsing open-vector-editor/es/CircularView/style.css

### ISSUE THREAD

**Issue by nicolazilio** [TeselaGen/openVectorEditor#858]
@tnrich

Hello,

when building (react-scripts build) after upgrading to OVE 18.1.0, I receive this error

```
./node_modules/open-vector-editor/es/CircularView/style.css
ParserError: Syntax Error at line: 3, column 21
```

I traced back the error to [here](https://github.com/TeselaGen/openVectorEditor/blob/a577b07d4fe60410bfac89b6fcc7b8125fe9ff25/src/CircularView/style.css#L25)

```css
  background: linear-gradient(var(--bg), var(--bg)) content-box,
    linear-gradient(var(--v), #ccc 50%, transparent 0) 0 /
      min(100%, (50 - var(--p)) * 100%),
    linear-gradient(var(--v), transparent 50%, #4ac5ed 0) 0 /
      min(100%, (var(--p) - 50) * 100%),
    linear-gradient(to right, #ccc 50%, #4ac5ed 0);
```
adding `calc` to the operations with var(--x) solves the issue

```css
  background: linear-gradient(var(--bg), var(--bg)) content-box,
    linear-gradient(var(--v), #ccc 50%, transparent 0) 0 /
      min(100%, calc(50 - var(--p)) * 100%),
    linear-gradient(var(--v), transparent 50%, #4ac5ed 0) 0 /
      min(100%, calc(var(--p) - 50) * 100%),
    linear-gradient(to right, #ccc 50%, #4ac5ed 0);
```

**Comment by tnrich** [comment]
@nicolazilio interesting. I don't see builds failing for me. Would you mind putting a PR in with that change and I can publish a new version for you? 

Thanks!

**Comment by tnrich** [comment]
@nicolazilio bump on this one.

**Comment by nicolazilio** [comment]
Sure, I can do that, but maybe it's my set up that is 'weird'. I have adapted your plasmid viewer project  for my needs, see [here](https://github.com/helle-ulrich-lab/ove-plasmid-viewer/blob/main/package.json), and now I just update the version of OVE when you release a new one. Could this explain the difference?

**Comment by tnrich** [comment]
@nicolazilio it looks like you're building your app that uses ove as a dep using CRA. My guess would be that there is some difference between the underlying build system for CRA and what the OVE project uses - nwb (https://github.com/insin/nwb for now at least). 

Thanks in advance for the PR!

**Comment by tnrich** [comment]
@nicolazilio publishing v18.1.16 now. Let me know if that version fixes it for you.

**Comment by nicolazilio** [comment]
Yes, it works, thanks!
