### ISSUE TITLE
Usage of navigator.userAgent

### ISSUE THREAD

**Issue by NicolasCARPi** [TeselaGen/openVectorEditor#884]
Hello @tnrich,

I'm using OVE in [eLabFTW](https://github.com/elabftw/elabftw/) and came across this warning in Chrome dev tools:

![bug-ove](https://user-images.githubusercontent.com/3043706/226216470-1b989b62-da79-4679-8a83-e75977e5f3e6.png)

Given that `navigator.userAgentData` is [not yet supported in Safari and Firefox](https://caniuse.com/?search=navigator.userAgentData), and that `navigator.userAgent` might be enough for your use case, this issue is probably not a big deal, but I wanted to let you know in case you want to brush up the user agent detection in your codebase.

Best,
~Nico

**Comment by tnrich** [comment]
Hi @NicolasCARPi thanks for the heads up!

**Comment by tnrich** [comment]
Given what you said above about the lack of support for userAgentData in safari/firefox, I think I'll wait until this becomes an issue for someone. Maybe by that time userAgentData will be supported universally. Cheers!
