### ISSUE TITLE
Bug in ElabFTW implementation of openVectorEditor

### ISSUE THREAD

**Issue by nmontua** [TeselaGen/openVectorEditor#888]
@tnrich

Hi, would you be willing to help out with an issue in ElabFTW (which has openVectorEditor implemented, great software BTW). The copy AA sequence feature is broken for some reason.

https://github.com/elabftw/elabftw/issues/4261

**Comment by tnrich** [comment]
@nmontua sure ya this should be fixable. I've got other issues in my stack to work on first but will let you know when I get to this !

**Comment by MarcelBolten** [comment]
Hi Thomas (@tnrich),

I fixed it with PR https://github.com/elabftw/elabftw/pull/4265 but probably there are more bugs or at least potential for optimization in our OVE setup (https://github.com/elabftw/elabftw/blob/hypernext/src/ts/ove.ts).

I was wondering if you might want to take a look at our setup file but would also understand if you do not manage.

@nmontua  I think this issue can be closed.
