### ISSUE TITLE
How to generate a feature without an arrow

### ISSUE THREAD

**Issue by hi-asan** [TeselaGen/openVectorEditor#900]
The current strand only has positive and negative

![image](https://github.com/TeselaGen/openVectorEditor/assets/12293038/807359d5-33c0-423c-bc1d-f4894c12c05b)

I want to achieve the effect inside the red box

<img width="541" alt="image" src="https://github.com/TeselaGen/openVectorEditor/assets/12293038/1af661e5-f34d-4b4d-9610-9db07285baab">

Is there any way to do this

**Comment by tnrich** [comment]
See the demo option allowMultipleFeatureDirections=true here: 

https://teselagen.github.io/openVectorEditor/#/Editor?allowMultipleFeatureDirections=true

<img width="1440" alt="image" src="https://github.com/TeselaGen/openVectorEditor/assets/2730609/894c04a3-3f31-4bff-8ad1-b456a16c2237">


Lemme know if that does it for ya @hi-asan

**Comment by hi-asan** [comment]
Sorry, I did see and resolve this issue on the demo and forgot to turn off this question
