### ISSUE TITLE
update to version 18.3.4, yarn start error

### ISSUE THREAD

**Issue by avisajn** [TeselaGen/openVectorEditor#905]
@tnrich    I use "open-vector-editor": "18.0.0" is normal, when using 18.3.4, i want use handleAlignment function,  this error occurs. Sorry, I don't have a warehouse address to send out, i think because ""@hello-pangea/dnd"", "18.0.0"dont have "@hello-pangea/dnd", , Maybe,@hello-pangea/dnd's babel-loader is 9.1.x and mine is 8.1.x, what should I do if this is the problem here
I have to use the latest version,  Or is there any way to use 18.3.4 Thanks
![image](https://github.com/TeselaGen/openVectorEditor/assets/139226356/0ea0f4d5-94af-4802-8239-c901e7cb974f)
this is my dependency you can see
this is package.json
>  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@antv/x6": "^1.34.5",
    "@babel/core": "7.22.8",
    "@commitlint/cli": "^17.2.0",
    "@commitlint/config-conventional": "^17.2.0",
    "@logicflow/core": "1.2.0-next.2",
    "@logicflow/extension": "1.2.0-next.2",
    "@pmmmwh/react-refresh-webpack-plugin": "0.4.3",
    "@redux-devtools/extension": "^3.2.3",
    "@svgr/webpack": "5.5.0",
    "@teselagen/bio-parsers": "^0.1.18",
    "@testing-library/jest-dom": "^5.15.0",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@tinymce/tinymce-react": "^4.2.0",
    "@types/jest": "^29.2.1",
    "@types/node": "^18.11.9",
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "@types/react-redux": "^7.1.24",
    "@types/redux-form": "^8.3.5",
    "@typescript-eslint/eslint-plugin": "^5.42.1",
    "@typescript-eslint/parser": "^5.42.1",
    "ahooks": "^3.7.2",
    "antd": "^4.24.0",
    "axios": "1.1.3",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.0",
    "babel-loader": "8.1.0",
    "babel-plugin-named-asset-import": "^0.3.7",
    "babel-preset-react-app": "^10.0.0",
    "bfj": "^7.0.2",
    "camelcase": "^6.1.0",
    "case-sensitive-paths-webpack-plugin": "2.3.0",
    "css-loader": "4.3.0",
    "dotenv": "8.2.0",
    "dotenv-expand": "5.1.0",
    "eslint": "^8.27.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-react-app": "^6.0.0",
    "eslint-plugin-flowtype": "^5.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest": "^24.1.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.31.10",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-testing-library": "^3.9.2",
    "eslint-webpack-plugin": "^2.5.2",
    "file-loader": "6.1.1",
    "fs-extra": "^9.0.1",
    "html-webpack-plugin": "4.5.0",
    "husky": ">=6",
    "identity-obj-proxy": "3.0.0",
    "jest": "26.6.0",
    "jest-circus": "26.6.0",
    "jest-resolve": "26.6.0",
    "jest-watch-typeahead": "0.6.1",
    "lark-token": "1.0.14",
    "less": "^4.1.3",
    "less-loader": "7.3.0",
    "mini-css-extract-plugin": "0.11.3",
    "open-vector-editor": "18.0.0",
    "optimize-css-assets-webpack-plugin": "5.0.4",
    "pnp-webpack-plugin": "1.6.4",
    "postcss-flexbugs-fixes": "4.2.1",
    "postcss-loader": "3.0.0",
    "postcss-normalize": "8.0.1",
    "postcss-preset-env": "6.7.0",
    "postcss-safe-parser": "5.0.2",
    "prompts": "2.4.0",
    "re-resizable": "^6.9.9",
    "react": "^17.0.2",
    "react-app-polyfill": "^2.0.0",
    "react-beautiful-dnd": "^13.1.1",
    "react-color": "^2.19.3",
    "react-dev-utils": "^11.0.3",
    "react-dom": "^17.0.2",
    "react-refresh": "^0.8.3",
    "react-router-dom": "^6.4.2",
    "react-use-websocket": "3.0.0",
    "resolve": "1.18.1",
    "resolve-url-loader": "^3.1.2",
    "sass-loader": "^10.0.5",
    "semver": "7.3.2",
    "style-loader": "1.3.0",
    "terser-webpack-plugin": "4.2.3",
    "ts-pnp": "1.2.0",
    "typescript": "^4.8.4",
    "url-loader": "4.1.1",
    "webpack": "4.44.2",
    "webpack-dev-server": "3.11.1",
    "webpack-manifest-plugin": "2.2.0",
    "workbox-webpack-plugin": "5.1.4"
  },

**Comment by tnrich** [comment]
Hey @avisajn it's hard to give exact help without some sort of reproduction, but I would recommend trying to pin the @hello-pangea/dnd package to the version it was in ove 18.0.0 via the resolutions field: 

```
"resolutions": {
    "@hello-pangea/dnd": "X.X.X"  <---whatever version it was before it started breaking
}
```

try that and lemme know if it fixes it for ya.

**Comment by avisajn** [comment]
@tnrich 
This is ok, thank you very much
