### ISSUE TITLE
couldn't import protein sequence and correctly display

### ISSUE THREAD

**Issue by mega-bisharp** [TeselaGen/openVectorEditor#912]
my protein sequence from ncbi 
>AXN76052.1
MRCMSELVVFKANELAISRYDLTEHETKLILCCVALLNPTIENPTRKERTVSFTYNQYAQMMNISRENAYGVLAKATRELMTRTVEIRNPLVKGFEIFQWTNYAKFSSEKLELVFSEEILPYLFQLKKFIKYNLEHVKSFENKYSMRIYEWLLKELTQKKTHKANIEISLDEFKFMLMLENNYHEFKRLNQWVLKPISKDLNTYSNMKLVVDKRGRPTDTLIFQVELDRQMDLVTELENNQIKMNGDKIPTTITSDSHLHNGLRKTLHDALTAKIQLTSFEAKFLSDMQSKYDLNGSFSWLTQKQRTTLENILAKYGRI
result:
![image](https://github.com/TeselaGen/openVectorEditor/assets/74715960/323ff340-cf05-40cb-a0f2-065fcf1c45b6)
![image](https://github.com/TeselaGen/openVectorEditor/assets/74715960/48e0a7a9-1b4b-4957-aa4a-bd850f618164)

problem:
![image](https://github.com/TeselaGen/openVectorEditor/assets/74715960/9416fcdb-5525-4ac2-b0eb-c8664df5502b)
I think the type in here maybe "PROTEIN", not "DNA"

@tnrich

**Comment by tnrich** [comment]
@mega-bisharp can you please attach the file as a ZIP file here ? Thanks!

**Comment by mega-bisharp** [comment]
> @mega-bisharp can you please attach the file as a ZIP file here ? [Thanks!]
This is my protein sequences, thank you for your reply!
[seqdump.zip](https://github.com/TeselaGen/openVectorEditor/files/12414157/seqdump.zip)
@tnrich

**Comment by tnrich** [comment]
@mega-bisharp that file doesn't have a file extension that would indicate that it is a protein. We would need to guess based on the sequence content which can sometimes be risky..

**Comment by tnrich** [comment]
Also this is the new repo that OVE lives in - https://github.com/TeselaGen/tg-oss

**Comment by mega-bisharp** [comment]
> @mega-bisharp该文件没有表明它是蛋白质的文件扩展名。我们需要根据序列内容进行猜测，这有时可能是有风险的。

So, what's the correctly file extension for protein sequence? Thank you for your answer！
@tnrich

**Comment by tnrich** [comment]
@mega-bisharp I believe the format you're looking for is .faa since your data is in the fasta format:

<img width="1055" alt="image" src="https://github.com/TeselaGen/openVectorEditor/assets/2730609/d9927f17-b5f0-49e9-939b-77ecfe2443fd">


I'll actually need to update the code here https://github.com/TeselaGen/tg-oss/ (that's the new repo for ove/bio-parsers, this on is deprecated now) in order to handle .faa files correctly. I'll do that now

**Comment by tnrich** [comment]
@mega-bisharp ok, I've updated @teselagen/ove to v0.3.11 which should include automatic parsing of .faa files to protein. Let me know if that works for you :)
