### ISSUE TITLE
Cannot access the dropped sequence file - only the sequence data?

### ISSUE THREAD

**Issue by acostin** [TeselaGen/openVectorEditor#913]
@tnrich
Is there a way to access to dropped sequence file itself in the `onImport` or otherwise?

 I need to grab the file to get its name and extension, but `onImport` only gives me the sequence data. I see that `importSequenceFromFile` is being called beforehand which has access to the file, but not sure how I can get it from the editor object? Is there a way to do this, or would this be a new feature request?

Thanks

**Comment by tnrich** [comment]
Hi @acostin,

Please note that this repo has moved to https://github.com/TeselaGen/tg-oss/

I've published a new version of ove from there @teselagen/ove@0.3.10 which should fix your issue, the new onImport signature is as follows: 

<img width="401" alt="image" src="https://github.com/TeselaGen/openVectorEditor/assets/2730609/78b9ace5-4fe3-44f0-8426-e8be56c383aa">

Lemme know if this solves your issue :)

**Comment by acostin** [comment]
@tnrich

This works great, thanks!

**Comment by tnrich** [comment]
Glad to hear it!
