### ISSUE TITLE
Select-inverse of current selection via Cmd/crtl-I

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#92]
Cmd/ctirl-I should trigger a 'selectInverse' signal which causes the selection to be 'inverted'. We might need to discuss a bit more to hammer out exactly what 'inverted' should mean for all cases.

**Comment by thirdknife** [comment]
@tnrich does this means to deselect what's selected and select the rest?

**Comment by tnrich** [comment]
yup exactly

**Comment by thirdknife** [comment]
I dont think the current way support this, this will need a big change in setSelectionLayer?
